### ISSUE TITLE
Renaming temporary file failed: File exists

### ISSUE THREAD

**Issue by jackczhang** [nih-at/libzip#1]
I compile with mingw32 for windows, got ziptool.exe and libzip-4.dll.
When using command:
 ziptool.exe abc.zip add_dir abc

to add abc folder to abc.zip, i got this error.

**Comment by 0-wiz-0** [comment]
Did you build using configure or CMake?

**Comment by jackczhang** [comment]
configure and CMake all i have used, but get the same error.

**Comment by jackczhang** [comment]
My behaviour
1. create a achive file named abc.zip, include abc.txt
2. use ziptool to add a folder to it --> then error

**Comment by 0-wiz-0** [comment]
Start from scratch; use CMake to build; and then let me know which of the zip_source_win* files are used in your build, if any.

**Comment by jackczhang** [comment]
zip_source_window.c used, other files were not used.

**Comment by 0-wiz-0** [comment]
lib/CMakeLists.txt has
````
IF(WIN32)
  SET(LIBZIP_OPSYS_FILES
    zip_source_win32a.c
    zip_source_win32handle.c
    zip_source_win32utf8.c
    zip_source_win32w.c
  )
````
please find out why this doesn't trigger for you.

**Comment by jackczhang** [comment]
yeah, that's my mistake, didn't compile these files for windows.
BTW, is that possible to make using configure to compile it for windows?

**Comment by 0-wiz-0** [comment]
Can you try https://github.com/nih-at/libzip/commit/1796bea46602d66065f3f31e586aa4799313aa3b ? That tries teaching the configure script to recognize Windows and behave better.

**Comment by jackczhang** [comment]
Yes, configure script can support windows well now, tested under mingw32 in msys64.

**Comment by 0-wiz-0** [comment]
Thanks for testing! I'm glad it works now.
