### ISSUE TITLE
zip_fseek : Operation not supported

### ISSUE THREAD

**Issue by yeyiwen** [nih-at/libzip#100]
i use the source regress/fseek to test my archive,but it's report:Operation not supported

**Comment by 0-wiz-0** [comment]
fseek is not for testing archives. Try ziptool.
And you'll need to provide many more details if you want help - what exactly are you running, what platform, ...

**Comment by yeyiwen** [comment]
thanks for response i'm work on libzip with 1.5.2 version, i want to read data from a file in archive with specify offset
and i see a example from regress/fseek.c, but every time i run it, i got error like:./build/regress/fseek: zip_fseek failed: Operation not supported
what should i do, is this a wrong example




------------------ 原始邮件 ------------------
发件人: "Thomas Klausner"<notifications@github.com>; 
发送时间: 2019年5月19日(星期天) 晚上6:21
收件人: "nih-at/libzip"<libzip@noreply.github.com>; 
抄送: "叶艺文"<408207359@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nih-at/libzip] zip_fseek : Operation not supported (#100)




fseek is not for testing archives. Try ziptool.
 And you'll need to provide many more details if you want help - what exactly are you running, what platform, ...

**Comment by dillof** [comment]
I guess you're trying to seek while reading a compresssed file. This is not supported, because we cannot start decompressing in the middle.

**Comment by yeyiwen** [comment]
i got that, thanks a lot!



------------------ 原始邮件 ------------------
发件人: "Dieter Baron"<notifications@github.com>; 
发送时间: 2019年5月19日(星期天) 晚上7:04
收件人: "nih-at/libzip"<libzip@noreply.github.com>; 
抄送: "叶艺文"<408207359@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [nih-at/libzip] zip_fseek : Operation not supported (#100)




I guess you're trying to seek while reading a compresssed file. This is not supported, because we cannot start decompressing in the middle.
