### ISSUE TITLE
recurring crash

### ISSUE THREAD

**Issue by Old-Geek** [nih-at/libzip#101]
![Capture d’écran 2019-05-22 à 22 50 00](https://user-images.githubusercontent.com/45225489/58207957-0cc2ee00-7ce4-11e9-9b1f-0a626a0b82d7.png)

**Comment by 0-wiz-0** [comment]
That's just triggered by the malloc() in libzip - it could be a malloc/free problem in some other code instead, and this is the first malloc() call afterwards where it's detected.
Please debug this in more detail, for now I'll assume it's not a libzip bug.

**Comment by Old-Geek** [comment]
Ok, thank you for your reply.
