### ISSUE TITLE
buffer_clone()  logical error

### ISSUE THREAD

**Issue by 522428182** [nih-at/libzip#103]
error code:
    clone->first_owned_fragment = ZIP_MIN(buffer->first_owned_fragment, clone->nfragments - 1);

reason:
    if buffer->nfragments=1,buffer->first_owned_fragment=1, clone->nfragments=1,
    clone->first_owned_fragment will equal 0
    clone->fragments[0] will be free.

**Comment by 0-wiz-0** [comment]
`first_owned_fragment` is the index of the first fragment, which is zero-based.
`nfragments` is the number of fragments.
If there is only one fragment, its index is zero (0) and nfragments is one (1).
