### ISSUE TITLE
zip_open fails when trying to open a ZIP attached to an ELF executable

### ISSUE THREAD

**Issue by cellux** [nih-at/libzip#104]
I'd like to attach the zipped assets required by a program to the end of its ELF executable and then access the contents of the attached archive from the program by passing the path of the executable file to zip_open().

Unfortunately, when I'm trying to do this I get a "Not a zip archive" error.

It would be nice if libzip could support this use case. (I had the impression that the ZIP format has its central directory at the end for this reason.)

**Comment by 0-wiz-0** [comment]
This use case is definitely already supported.
Perhaps there is another problem in your zip archive? Hard to say from here.

**Comment by 0-wiz-0** [comment]
Hm, on reading this again I guess I misunderstood.
We already support the case where such a file is created by another tool.
Creating such a file with libzip is not yet supported, but the suggested API is documented in `TODO.md`:
````
zip_set_archive_prefix(struct zip *za, const zip_uint8_t *data, zip_uint64_t length);
const zip_uint8_t *zip_get_archive_prefix(struct zip *za, zip_uint64_t *lengthp);
````

**Comment by dillof** [comment]
> On 2019/05/28, at 07:59, Thomas Klausner <notifications@github.com> wrote:
> 
> Hm, on reading this again I guess I misunderstood.
> We already support the case where such a file is created by another tool.
> Creating such a file with libzip is not yet supported, but the suggested API is documented in TODO.md:
> 
> zip_set_archive_prefix(struct zip *za, const zip_uint8_t *data, zip_uint64_t length);
> const zip_uint8_t *zip_get_archive_prefix(struct zip *za, zip_uint64_t *lengthp);

Also, you will need to create your ELF binary first (or at least know how big it will be), because zip stores file offsets in the central directory, so you cannot prepend another file after the zip archive has been created.

yours,
dillo

**Comment by cellux** [comment]
Thanks for your input!

How about the following:

1. Create ELF
2. Create ZIP
3. Add sizeof(ELF) to all file offsets in the ZIP local and central directory headers
4. Attach patched ZIP to ELF (cat ZIP >> ELF)

Could libzip open the resulting file?

**Comment by dillof** [comment]
Yes, that would result in a valid zip archive that libzip can handle.
