### ISSUE TITLE
zip_open with empty file

### ISSUE THREAD

**Issue by malytomas** [nih-at/libzip#105]
Hi, I just run into a problem that libzip happily opens an empty file, even with ZIP_CHECKCONS, as if it was a valid archive. Is this intended? I would have expected it to fail. Thanks.

**Comment by 0-wiz-0** [comment]
So far we've accepted zero-byte files as empty valid zip archives. What are the disadvantages that you see?

**Comment by malytomas** [comment]
There are four possible situations:
1. File already exists and contains zip tables.
2. File exists but does not contain zip tables (this is the case with empty file).
3. File exists and contains corrupted zip tables.
4. File does not exist.

And several combinations of flags:
a) ZIP_CREATE - works with 1, 2, 4; fails with 3
b) ZIP_CREATE | ZIP_EXCL - works with 4; fails with 1, 2, 3
c) ZIP_EXCL - makes no sense: fails with 1, 2, 3, 4
d) 0 - works with 1; fails with 3, 4; what about 2?

Apparently, d) works with empty file and fails with non-empty file without zip tables.

I want to reliably distinguish 1. and 2. cases, but the inconsistency makes it impossible. And there are no other flags that would allow separating 1. and 2. cases.

Specifically, I want to test if file is an actual zip archive - that it is the 1. category. I do that by trying to open the file with zip_open.

Could a new flag be added to specifically forbid empty files? Any other ideas?

(Note that testing the file in advance creates potential race condition.)

(Note that I compiled the above fails/works listing just by reading documentation, I did not actually test all of the situations.)

Hopefully this write-up makes my issue clear?

Thanks

**Comment by dillof** [comment]
Since we can't remember why we treat existing empty files as valid zip archives, we'll remove that special case.

**Comment by 0-wiz-0** [comment]
We've just fixed this, thanks for the report!

**Comment by malytomas** [comment]
I am now trying this and it is still opening empty files as archives. Do I have to somehow configure this?

```c++
zip_t *zip;
zip = zip_open("an_empty_file.txt", ZIP_CHECKCONS, nullptr);
```

Do I need to use zip_open_from_source instead?

Thanks for any guidance.

**Comment by 0-wiz-0** [comment]
Look at the change in the regression test suite - before the commit, `regress/open_empty_2.test` was successful, now it isn't.

**Comment by malytomas** [comment]
Is it possible to run the tests on windows?
This is as far as I could get:
```
$ ctest -VV --output-on-failure
UpdateCTestConfiguration  from :E:/personal/other/libzip/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :E:/personal/other/libzip/build/DartConfiguration.tcl
Test project E:/personal/other/libzip/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
        Start   1: add_dir.test

1: Test command: "C:\Program Files\Git\usr\bin\perl.exe" "E:/personal/other/libzip/build/regress/runtest" "E:/personal/other/libzip/regress/add_dir.test"
1: Test timeout computed to be: 10000000
]: E:/personal/other/libzip/build/regress/runtest: E:/personal/other/libzip/regress/add_dir.test:2: illegal int [0
1: E:/personal/other/libzip/build/regress/runtest: error in test case definition
  1/128 Test   #1: add_dir.test .....................................***Failed    0.10 sec
]:/personal/other/libzip/build/regress/runtest: E:/personal/other/libzip/regress/add_dir.test:2: illegal int [0
E:/personal/other/libzip/build/regress/runtest: error in test case definition
```
Similar for all other tests.

Also I did not found test output in the appveyor logs.

**Comment by 0-wiz-0** [comment]
We have no expertise with Windows - we rely on knowledgeable Windows users to help us out. Please let us know if you find a fix, it'd be great to run the tests on Windows as well. The driver script (runtest) is written in perl, and might need changes for Windows (and at least a perl installation).

**Comment by malytomas** [comment]
#127 related

**Comment by remicollet** [comment]
> Since we can't remember why we treat existing empty files as valid zip archives

For memory, some pieces of code use:
```
name = tempnam(...)
zip_open(name, 0, NULL)
```

BTW, fix is trivial
```
name = tempnam(...)
zip_open(name, ZIP_TRUNCATE, NULL)

```
