### ISSUE TITLE
`INT_MAX` undeclared

### ISSUE THREAD

**Issue by Vict0r-Lee** [nih-at/libzip#107]
I try to compile this library,but it didn't define this value.

**Comment by 0-wiz-0** [comment]
What compiler/operating system is that? `INT_MAX` is in ANSI C.
Perhaps there is an include missing somewhere, so please provide the full error message.

**Comment by Vict0r-Lee** [comment]
Centos 6.5 2.6.32-431.el6.x86_64
gcc (GCC) 4.4.7 
I'm sorry I was too busy yesterday.

**Comment by 0-wiz-0** [comment]
Please provide the full error message.

**Comment by prniii** [comment]
Do you have libressl installed...  I wound up with this same compile error, after I installed libressl in my /usr/local/lib, /usr/local/include ...   my user local is in the search path before other libraries.  Moving my /usr/local/include/openssl directory to /usr/local/include/openssl_libre let the cmake find the system openssl library, and things compiled fine.   this was with gcc 4.85 on CentOS 7.6.1810

**Comment by 0-wiz-0** [comment]
Not enough information to debug this.

**Comment by mckaygerhard** [comment]
same problem here

```
[   97s] [ 48%] Building C object lib/CMakeFiles/zip.dir/zip_crypto_openssl.c.o
[   97s] cd /usr/src/packages/BUILD/obj-i486-linux-gnu/lib && /usr/bin/cc  -DHAVE_CONFIG_H -Dzip_EXPORTS -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -fPIC -fvisibility=hidden -I/usr/src/packages/BUILD/obj-i486-linux-gnu/lib/.. -I/usr/src/packages/BUILD/lib    -o CMakeFiles/zip.dir/zip_crypto_openssl.c.o   -c /usr/src/packages/BUILD/lib/zip_crypto_openssl.c
[   97s] /usr/src/packages/BUILD/lib/zip_crypto_openssl.c: In function '_zip_crypto_hmac_new':
[   97s] /usr/src/packages/BUILD/lib/zip_crypto_openssl.c:78:25: error: 'INT_MAX' undeclared (first use in this function)
[   97s] /usr/src/packages/BUILD/lib/zip_crypto_openssl.c:78:25: note: each undeclared identifier is reported only once for each 
```

**Comment by mckaygerhard** [comment]
seems fixed by add +#include <limits.h>

**Comment by 0-wiz-0** [comment]
`zip_crypto_openssl.c` already includes `limits.h`:
https://github.com/nih-at/libzip/blob/master/lib/zip_crypto_openssl.c#L40

**Comment by mckaygerhard** [comment]
ok @0-wiz-0  but was not clarify in this issue.. that the problem.. you guys must work in organized way.. the comit was https://github.com/nih-at/libzip/commit/fd89e242d16128dedef08f47d99ae56aa19b0591#diff-386d94ee97a2afa44437da547b7e4b85fb28fc849c04477eb8eeb1a9a23f001c
