### ISSUE TITLE
failed compile with mingw-x64

### ISSUE THREAD

**Issue by s0uthwest** [nih-at/libzip#111]
**Compiler Error**
C:/Users/s0uthwes/Desktop/Projects/libzip/lib/zip_source_filep.c:639:13: error: 'O_CLOEXEC' undeclared (first use in this function)
  639 |     flags = O_CLOEXEC;
         |             ^~~~~~~~~
C:/Users/s0uthwes/Desktop/Projects/libzip/lib/zip_source_filep.c:639:13: note: each undeclared identifier is reported only once for each function it appears in
C:/Users/s0uthwes/Desktop/Projects/libzip/lib/zip_source_filep.c:647:31: error: macro "open" requires 3 arguments, but only 2 given
  647 |     if ((fd = open(name, flags)) < 0) {

**libzip Version**
latest version on github

**Operating System and Compiler**
Windows 10 (1903), mingw-x64

**Additional context**

**Comment by 0-wiz-0** [comment]
Does adding
````
#if !defined(O_CLOEXEC) && defined(O_NOINHERIT)
#define O_CLOEXEC O_NOINHERIT
#endif 
````
after the includes at the top of the file help?

**Comment by s0uthwest** [comment]
> Does adding
> 
> ```
> #if !defined(O_CLOEXEC) && defined(O_NOINHERIT)
> #define O_CLOEXEC O_NOINHERIT
> #endif 
> ```
> 
> after the includes at the top of the file help?

No.

**Comment by gnfalex** [comment]
Small patch

```
diff --git a/lib/compat.h b/lib/compat.h
index 41b7ddb..d6b9d37 100644
--- a/lib/compat.h
+++ b/lib/compat.h
@@ -95,8 +95,12 @@ typedef char bool;
 #define fileno _fileno
 #endif
 /* Windows' open() doesn't understand Unix permissions */
+#if !defined(O_CLOEXEC) && defined(O_NOINHERIT)
+#define O_CLOEXEC O_NOINHERIT
+#endif
+#define _zip_mkstempm(a, ...) mkstemp(a)
 #if defined(HAVE__OPEN)
-#define open(a, b, c) _open((a), (b))
+#define open(a, b, ...) _open((a), (b))
 #endif
 #if defined(HAVE__SNPRINTF)
 #define snprintf _snprintf
```

**Comment by 0-wiz-0** [comment]
Should be fixed by https://github.com/nih-at/libzip/commit/865240ed6f0c41a2f9dc64dc89ceefc355082a31
