### ISSUE TITLE
Unable to compile for X86_64 architecture - iOS Simulato (also, not working for iphone)

### ISSUE THREAD

**Issue by Arjunkalidas** [nih-at/libzip#115]
**Bug**
Unable to compile for iOS simulator or device.

**Expected Behavior**
Compilation should be successful as I have linked the framework and added libzip as part of embedded binaries as well.

**Observed Behavior**
`Undefined symbols for architecture x86_64:
  "_BZ2_bzDecompress", referenced from:
      _process in libzip_iOS
  "__zip_mkstempm", referenced from:
      _create_temp_output in libzip_iOS
  "_BZ2_bzCompressEnd", referenced from:
      _end in libzip_iOS
  "_BZ2_bzDecompressEnd", referenced from:
      _end in libzip_iOS
  "_deflateEnd", referenced from:
      _end in libzip_iOS
  "_BZ2_bzDecompressInit", referenced from:
      _start in libzip_iOS
  "_inflate", referenced from:
      _process in libzip_iOS
  "_crc32", referenced from:
      __zip_filerange_crc in libzip_iOS
      _zip_source_crc in libzip_iOS
      _crc_read in libzip_iOS
      _decrypt in libzip_iOS
      __zip_string_crc32 in libzip_iOS
     (maybe you meant: __zip_string_crc32)
  "_deflate", referenced from:
      _process in libzip_iOS
     (maybe you meant: _zip_algorithm_deflate_compress, _zip_algorithm_deflate_decompress )
  "_inflateEnd", referenced from:
      _end in libzip_iOS
  "_BZ2_bzCompress", referenced from:
      _process in libzip_iOS
  "_deflateInit2_", referenced from:
      _start in libzip_iOS
  "_BZ2_bzCompressInit", referenced from:
      _start in libzip_iOS
  "_inflateInit2_", referenced from:
      _start in libzip_iOS
  "_zError", referenced from:
      _zip_error_strerror in libzip_iOS
      _zip_error_to_str in libzip_iOS
  "_zip_secure_random", referenced from:
      _encrypt_header in libzip_iOS
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**To Reproduce**
1. Clone the libzip project from the GitHub
2. Open the Xcode folder and launch the libzip.xcodeproj project in Xcode
3. Build the project (it will be successful)
4. Pick the framework and the dylib files and link in the Xcode
5. The framework goes in target -> build phases - > Link Binary with Libraries
6. libz.dylib from the Frameworks folder of libzip project goes into the frameworks folder of your target application
7. When building, it will throw the error observed above.

**libzip Version**
1.5.2

**Operating System**
Mac OS Mojave version 10.14.5

<img width="259" alt="Screen Shot 2019-07-12 at 2 30 30 PM" src="https://user-images.githubusercontent.com/6784650/61150961-b76cb700-a4b2-11e9-9a04-1a997414961b.png">
<img width="898" alt="Screen Shot 2019-07-12 at 2 30 59 PM" src="https://user-images.githubusercontent.com/6784650/61150966-b9367a80-a4b2-11e9-88f4-b92942ea6bb0.png">

**Comment by 0-wiz-0** [comment]
Please try using cmake to generate an xcode project and use that instead.
