### ISSUE TITLE
Support for Deflate64 compressed files

### ISSUE THREAD

**Issue by agalanin** [nih-at/libzip#116]
**Description**
Please add support for Deflate64 compression method (at least for file decompression).

**Solution**
As far as I know Deflate64 is the same algorithm as Deflate but uses another dictionary size. InfoZip's unzip supports this compression method by using the same zlib's functions as for Deflate.

[example zipfile with Deflate64 compressed item](https://github.com/nih-at/libzip/files/3389049/issue58-test.zip)

**Comment by 0-wiz-0** [comment]
We would merge a patch with Deflate64 support, but we will not work on this in the foreseeable future.

**Comment by fcharlie** [comment]
@0-wiz-0 zlib actually provides the implementation code of the deflate64 algorithm [https://github.com/madler/zlib/tree/master/contrib/infback9](https://github.com/madler/zlib/tree/master/contrib/infback9) 

I think it is feasible to support deflate64, initially only need to provide decompression support.

**Comment by dillof** [comment]
Using the existing deflate implementation for your test file worked, so I enabled deflate64 decompression.

Could you please create a short test archive that contains a single line text file compressed with deflate64?

**Comment by dillof** [comment]
As Thomas pointed out, zlib does not include deflate64 support by default. I guess it worked by accident on this relatively small file.

**Comment by fcharlie** [comment]
> As Thomas pointed out, zlib does not include deflate64 support by default. I guess it worked by accident on this relatively small file.

The actual situation is that 7zip can create zip files that use Deflate64. In addition, Windows will also choose Deflate64 when the compressed file is large, then the problem is coming, whether it is libzip or minizip, this type of zip file cannot be decompressed, and zlib Infback9 should support the Deflate64 compression algorithm, so transplanting those files can support the decompression of zip files compressed in Deflate64 format.

**Comment by dillof** [comment]
Like Thomas said, we gladly accept pull requests or patches, but we won't get to implementing it in the foreseeable future ourselves.
