### ISSUE TITLE
calling zip_close after a function return corrupts the archive

### ISSUE THREAD

**Issue by mircodezorzi** [nih-at/libzip#117]
**Describe the Bug**
Whenever I try to call zip_close after the return a function, it's contents get corrupted and junk data is written to it.

**Expected Behavior**
No data corruption

**To Reproduce**

The following code will reproduce the bug:

```cpp
/* g++ main.cpp -lzip */
#include <zip.h>
#include <string>

zip *archive;

void write() {
	int error;
	archive = zip_open("archive.zip", ZIP_CREATE, &error);

	std::string foo = "Lorem ipsum dolor sit amet";
	zip_source *source = zip_source_buffer(archive, foo.c_str(), foo.size(), 0);
	int index = (int)zip_file_add(archive, "file", source, ZIP_FL_OVERWRITE);
}

int main() {
	write();
	zip_close(archive);
	return 0;
}
```

generated zip file: 124 bytes
generated file size: 26 bytes
contents: 26 garbage bytes

The following code generates the excepted output:

```cpp
/* g++ main.cpp -lzip */
#include <zip.h>
#include <string>

zip *archive;

void write() {
	int error;
	archive = zip_open("archive.zip", ZIP_CREATE, &error);

	std::string foo = "Lorem ipsum dolor sit amet";
	zip_source *source = zip_source_buffer(archive, foo.c_str(), foo.size(), 0);
	int index = (int)zip_file_add(archive, "file", source, ZIP_FL_OVERWRITE);
	zip_close(archive);
}

int main() {
	write();
	return 0;
}
```

generated zip file: 132 bytes
generated file size: 26 bytes
contents: expected string

**libzip Version**
- master on commit: `7fc6093`
- arch linux version: `1.5.2-2`

**Comment by dillof** [comment]
You create a zip_source_buffer with `freep` set to 0. This means, the source is not copying the buffer you pass in, and you have to ensure it is valid until `zip_close()` is called. In your first example, that is not the case, and thus the data is no longer valid when `zip_close()` tries to write it into the archive. Passing 1 as `freep` to `zip_source_buffer()` should fix the first example.

**Comment by mircodezorzi** [comment]
Passing 1 to `zip_soure_buffer()` gives me a `free(): double free detected in tcache 2`.

**Comment by dillof** [comment]
Sorry, I misremembered what `freep` does. It does not copy the buffer, but it assumes ownership of it (i. e. frees it when it's no longer needed). That doesn't work with C++ strings. So either you use variant two, or you make a copy (with malloc/strdup) and pass that to `zip_source_buffer` with `freep` set to 1.

**Comment by mircodezorzi** [comment]
Thanks, managed to fix my issue. I ended up using malloc + memcpy as I'm writing images and strdup won't do the job.
