### ISSUE TITLE
O_CLOEXEC not defined on windows

### ISSUE THREAD

**Issue by malytomas** [nih-at/libzip#121]
**Compiler Error**
error: C2065
description: 'O_CLOEXEC': undeclared identifier
https://github.com/nih-at/libzip/blob/7fc609382759a907d882fb0d3d7e4f6ab0519f35/lib/zip_source_filep.c#L639

**libzip Version**
commit 7fc609382759a907d882fb0d3d7e4f6ab0519f35

**Operating System and Compiler**
Windows, MSVC 2017 15.9.15

Here are relevant configuration options:
[CMakeLists.txt](https://github.com/nih-at/libzip/files/3512524/CMakeLists.txt)

**Compile command line**
```
/MP /GS /TC /W0 /Zc:wchar_t /I"" /I"" /I"" /Zi /Gm- /O2 /Ob1 /Fd"zip.dir\RelWithDebInfo\zip.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "NDEBUG" /D "_CRT_SECURE_NO_WARNINGS" /D "_CRT_NONSTDC_NO_DEPRECATE" /D "HAVE_CONFIG_H" /D "CMAKE_INTDIR=\"RelWithDebInfo\"" /D "_MBCS" /errorReport:prompt /WX- /Zc:forScope /Gd /MD /Fa"RelWithDebInfo/" /nologo /Fo"zip.dir\RelWithDebInfo\" /Fp"zip.dir\RelWithDebInfo\zip.pch" /diagnostics:classic
```

**Autodetected Configuration**
I will not upload that file since it contains potentially sensitive information (paths with names, etc.).
Ask me if you really need any more information.

**Additional context**
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open-wopen?view=vs-2019
O_CLOEXEC is not mentioned here.

**Comment by malytomas** [comment]
I just noticed that you do have appveyor set up, so you already know about the issue.
Sorry for spamming.

**Comment by malytomas** [comment]
According to https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-wfopen?view=vs-2019
```
N | Specifies that the file is not inherited by child processes.
```
so that could perhaps be used on windows.
But I have no experience with it, so please first verify if that is actually what you want?

**Comment by neolit123** [comment]
it's also not defined for a version of MINGW i tested locally: `gcc version 5.3.0`

this ticket also suggests it's missing on OSX:
https://bugs.python.org/issue26343

**Comment by 0-wiz-0** [comment]
Should be fixed by https://github.com/nih-at/libzip/commit/865240ed6f0c41a2f9dc64dc89ceefc355082a31
