### ISSUE TITLE
Unknown gnutls type names when compiling zip_winzip_aes.c

### ISSUE THREAD

**Issue by celan69** [nih-at/libzip#123]
In file included from /home/tech/webapp/src/libzip-1.5.2/lib/zip_crypto_gnutls.h:40,
                 from /home/tech/webapp/src/libzip-1.5.2/lib/zip_crypto.h:45,
                 from /home/tech/webapp/src/libzip-1.5.2/lib/zip_crypto_gnutls.c:38:
/usr/include/gnutls/crypto.h:35:10: error: unknown type name 'gnutls_cipher_algorithm_t'; did you mean 'gnutls_cipher_hd_t'?
          gnutls_cipher_algorithm_t cipher,
          ^~~~~~~~~~~~~~~~~~~~~~~~~
          gnutls_cipher_hd_t

libzip-1.5.2 compiling with gcc-8.3 on Solaris 11.4

FIX:
Reverse the inclusion order of gnutls/gnutls.h (should come first) and gnutls/crypto.h (should come second).

**Comment by 0-wiz-0** [comment]
Worked for me, but I switched them around if it helps. What gnutls version was that?

**Comment by celan69** [comment]
gnutls 3.5.16 as included in Solaris 11.4

**Comment by 0-wiz-0** [comment]
Ok, thanks.
