### ISSUE TITLE
[zipmerge] add option to append files instead of overwriting

### ISSUE THREAD

**Issue by haansn08** [nih-at/libzip#124]
**Description**
I have several source zip files containing CSV data files of the same name (`A.csv`).
I want to combine the zip files using `zipmerge` such that the target zip file contains a file `A.csv` with contents:
```
cat source1/A.csv source2/A.csv ...
```

Currently `zipmerge` only overwrites or ignores files with the same name.

**Solution**
Introducing a append flag `-A`, which when enabled does not override the files, but instead append them to eachother.

**Comment by 0-wiz-0** [comment]
This is a special case of very limited use. Many files do not make sense if you concatenate them this way.
