### ISSUE TITLE
It doesn't work very well on Android

### ISSUE THREAD

**Issue by LivedForward** [nih-at/libzip#125]
I used libzip on Android, and after compiling with NDK, I have the following problem as follows:

When reading a file in a zip file, the char array read is incomplete.
Using Zlib-1.2.11
Libzip0.9.3 occurs

When reading the zip file, the read failed and the error code 4 is returned.
ZIP_ER_SEEK 4 S Seek error
Using Zlib-1.2.11
Libzip1.2.0 occurs

ZIP_ER_SEEK
 A file seek error occurred.

When reading the zip file, the read failed and the error code 21 is returned.
ZIP_ER_INCONS 21 Zip archive inconsistent
Using Zlib-1.2.11
Libzip1.0.1 occurs

The parameter of flags of zip_open function I used is 0.

**Comment by 0-wiz-0** [comment]
Due to limited manpower, we are not providing support for old versions of libzip, so please retry all your problems with the latest version (1.5.2).
Also, please file separate bug reports for separate problems; and provide more information on the actual code and zip archives you are using. Thanks.
