### ISSUE TITLE
The META-INF/CERT.RSA character array in the read apk file is incomplete.

### ISSUE THREAD

**Issue by LivedForward** [nih-at/libzip#129]
I am using libzip1.5.2 to read a file in apk on Android platform:

int error_ZipOpen = 0;
struct zip* apkArchive=zip_open("/storage/emulated/0/Test.apk",ZIP_RDONLY, &error_ZipOpen);
const char *fname = "META-INF/CERT.RSA";
struct zip_file* file = zip_fopen(apkArchive, fname, ZIP_FL_UNCHANGED  );
struct zip_stat fstat;
	zip_stat_init(&fstat);
	zip_stat(apkArchive,fname,0,&fstat);
	char *buffer=(char *)malloc(sizeof(char)*(fstat.size+1));  //sizeof(char)*(fstat.size+1)
	memset(buffer,0,fstat.size+1);
int numBytesRead =  zip_fread(file, buffer,fstat.size);
	buffer[fstat.size+1]='\0';

buffer :
Finally only part of the CERT.RSA file was read, but reading the txt file which in apk  is complete.

**Comment by 0-wiz-0** [comment]
We can't debug this without an example file.
Please make sure to handle error cases (there is no error checking anywhere in the example code).
You can also test by running `ziptool Test.apk cat 0` (where you replace "0" with the index of `META-INF/CERT.RSA` in the zip archive.
Does `CERT.RSA` perhaps contain zero bytes (which terminate C strings) and you didn't handle that?

**Comment by LivedForward** [comment]
[Test.zip](https://github.com/nih-at/libzip/files/3723972/Test.zip)

This is a test file, because uploading .apk files is not supported, so I modified the suffix to .zip
It is almost incomplete to read the char array of META-INF/CERT.RSA(XXX.RSA/XXX.DSA) in all apk files.

I am sure there are no errors in the code and no errors have occurred.
I tried to use an index to replace the file name, but still the same result.

**Comment by 0-wiz-0** [comment]
I tried your testfile, and it worked fine for me.
The size is 1066, and I get all bytes with ziptool:
````
# ziptool Test.zip cat 232 | wc -c
    1066
````
I guess that do not handle the result correctly (there are embedded zero bytes in the file).
