### ISSUE TITLE
Documentation is unclear on functions available in 0.1x versions

### ISSUE THREAD

**Issue by SlySven** [nih-at/libzip#13]
At present I am trying to update some legacy code in a project that uses `libzip` as it was around 0.10 to 0.13 (I think) - whilst nearly everywhere that our project is used now has a 1.x version available there are a couple of corner cases (including one part of the C.I. systems - based on Ubuntu _Trusty Tahr_) that only has the [older version](https://packages.ubuntu.com/trusty/libzip2) by default.  Whilst I can accommodate such _mature_ systems with `#if defined(LIBZIP_VERSION_MAJOR) && (LIBZIP_VERSION_MAJOR >= 1)` to use the appropriate function depending on what is available it is hard to determine exactly what functions I do have available in the older version cases.

Could the `man` pages be updated to indicate (perhaps within a `HISTORY` section) which version of the `libzip` library gained a (working form) of each function; perhaps also this should include the addition/modification/removal of flag options where appropriate?

**Comment by SlySven** [comment]
Ah, I see `API-CHANGES` goes some way towards addressing this - but as I was ___RTFM___-ing to investigate this, I didn't see that file 🙂 

\<aside>In `zip_error_get(zip_t* za, int* ze, int* se)` what relation does `se` have to `errno` defined in `errno.h` on Linux systems?\</aside> 😕

**Comment by 0-wiz-0** [comment]
That HISTORY-section project is too big for my current time commitments. I'm willing to accept patches though! Also if you find a good place for mentioning `API-CHANGES`.
As for your other question, see the `zip_error_code_system()` and `zip_error_system_type()` man pages.

**Comment by 0-wiz-0** [comment]
This has been fixed with the latest commits, finishing with https://github.com/nih-at/libzip/commit/7da0227aea74483184d17ac8fe868bf7c71b4e4c. Enjoy!
