### ISSUE TITLE
Use of deprecated form of CMake functions prevents use in modern CMake

### ISSUE THREAD

**Issue by leecbaker** [nih-at/libzip#131]
```
The plain signature for target_link_libraries has already been used with
  the target "zip".  All uses of target_link_libraries with a target must be
  either all-keyword or all-plain.

  The uses of the plain signature are here:

   * lib/libzip/lib/CMakeLists.txt:223 (TARGET_LINK_LIBRARIES)
```

Libzip uses the old form of the `target_link_libraries()` command which does not have the `PUBLIC`/`PRIVATE`/`INTERFACE` keywords used to specify how this link dependency should be used.

When used as part of CMake code using current versions of the `target_link_library()` and other functions, `PUBLIC`/`PRIVATE`/`INTERFACE` keywords must be specified. This is encountered e.g. when libzip is used as a library in a bigger project.

Instructions on how to appropriately use these keywords is here: https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#build-specification-and-usage-requirements

**libzip Version**
master

**Operating System and Compiler**
Any version of CMake from at least 3.0 and newer; perhaps back as old as CMake 2.8. I observed this with CMake 3.12.

**Solution**
Add the `PUBLIC`/`PRIVATE`/`INTERFACE` keywords to each use of `target_link_libraries()` `target_include_directories()` and other functions, such as [here](https://github.com/nih-at/libzip/blob/master/lib/CMakeLists.txt#L228).

**Comment by 0-wiz-0** [comment]
I'm actually not quite clear on the difference between the three types. Could you open a pull request with a suggested fix, please?

**Comment by leecbaker** [comment]
Yes, no problem.

**Comment by 0-wiz-0** [comment]
We marked libzip's use of libraries as `PRIVATE` in 38b2ceea.
I don't see the point in doing the same for executables, if you need that as well in your environment, please explain in more detail.
Thanks!
