### ISSUE TITLE
v. 1.5.2 - Compilation error in Visual Studio 2017

### ISSUE THREAD

**Issue by danilom67** [nih-at/libzip#137]
**Compiler Error**
1>------ Build started: Project: zip, Configuration: Release x64 ------
1>zip_source_winzip_aes_encode.c
1>C:\Temp\libzip-1.5.2\libzip-1.5.2\lib\zip_source_winzip_aes_encode.c(166): error C2036: 'void *': unknown size
1>Done building project "zip.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**libzip Version**
1.5.2

**Operating System and Compiler**
Windows - Visual Studio 2017 Version 15.9.5

Also, any flags passed to `cmake`.
 -G"Visual Studio 15 2017 Win64" -DENABLE_COMMONCRYPTO=OFF -DENABLE_GNUTLS=OFF -DENABLE_MBEDTLS=OFF -DENABLE_OPENSSL=OFF -DZLIB_INCLUDE_DIR=C:\Temp\zlib1211\zlib-1.2.11 -DZLIB_LIBRARY=C:\Temp\zlib1211\zlib-1.2.11\contrib\vstudio\vc14\x64\ZlibStatRelease\zlibstat.lib ..

**Autodetected Configuration**
Attach `CmakeCache.txt` from your build directory. This list everything `cmake` detected on your system.
[CMakeCache.txt](https://github.com/nih-at/libzip/files/3809351/CMakeCache.txt)

**Additional context**
Previous versions compiled without raising this error.

**Comment by 0-wiz-0** [comment]
That was fixed in 1e6b758ad1284736c681e55a9d5315c0e79dd92f.
