### ISSUE TITLE
Documentation: normal font in function arguments is hard to read

### ISSUE THREAD

**Issue by lordadamson** [nih-at/libzip#139]
**Description**
In the documentation the font used for the arguments passed and return values is not a mono-space font that is easy to read for code.

Example:
![Screenshot from 2019-11-19 19-25-49](https://user-images.githubusercontent.com/43860544/69170239-6cb71780-0b02-11ea-8527-da45818f6469.png)

It's a little weird because the function name is written in a nice font that is suitable for code :smile: 

**Solution**
Please have the function arguments and return values documented in a font that is mono-space.

**Comment by 0-wiz-0** [comment]
That's a question of style, and we like the look we have now. Copy'n'paste should still work either way :)
