### ISSUE TITLE
Cocoapod support or documentation for how to import the library into xcode.

### ISSUE THREAD

**Issue by Artaches** [nih-at/libzip#140]
**Description**
It would be great if this library was packaged in a Cocoapod for easy importing in XCode. Or step-by-step documentation for importing the library into XCode would be great too. I didn't find the "libzip/developer-xcode" project to be sufficient in demonstrating how to do this.

I've got the library working on Android but I'm struggling with getting it to work in XCode for iOS development.

Thank you for this great library!

**Comment by dillof** [comment]
The included Xcode project is for development only, and not suitable for building a production version. cmake supports creating an Xcode project, but it would need some extra work to get it to build a framework. I plan on doing that at some point, but haven’t gotten to it yet.

As for Cocoapod, I do not use it and have no interest in adding support for it. If you can provide the necessary files and they don’t require much maintenance, we could include them.
