### ISSUE TITLE
MSVC(C2036) "void*" unkown size

### ISSUE THREAD

**Issue by Demonese** [nih-at/libzip#147]
**Compiler Error**
lib\zip_source_winzip_aes_encode.c [166, 1]
MSVC(C2036) "void*" unkown size

**libzip Version**
libzip-1.5.2

**Operating System and Compiler**
Windows 10 Home x64 1919 18363.535
MSVC 16.4.2 x64

**Autodetected Configuration**
[CMakeCache.txt](https://github.com/nih-at/libzip/files/4018902/CMakeCache.txt)

**Additional context**
I'm trying to change it to `buffer_n += _zip_buffer_read(ctx->buffer, (zip_uint8_t*)data + ret, length - (zip_uint64_t)ret);` and it compiler pass.

**Comment by 0-wiz-0** [comment]
Fixed in https://github.com/nih-at/libzip/commit/1e6b758ad1284736c681e55a9d5315c0e79dd92f#diff-9e1a446dcf69a141d0ca22e5eec5185b
