### ISSUE TITLE
 C++ style comments are not allowed in ISO C90

### ISSUE THREAD

**Issue by yzcj105** [nih-at/libzip#151]
**Describe the Bug**
When make,  the "//" comment is not supported with -ansi compile, which is ISO C90. 

**Expected Behavior**
Instead,  "/* */" is suggested.

I've used gcc compile on centos 7.   So when compile some packages like "tldr c client", it depends on libzip, and show the error information

make PREFIX=/mnt/home/jchen/.linuxbrew/Cellar/tldr/1.3.0_2 install
Last 15 lines from /mnt/home/jchen/.cache/Homebrew/Logs/tldr/01.make:
PREFIX=/mnt/home/jchen/.linuxbrew/Cellar/tldr/1.3.0_2
install

CC src/local.c
CC src/net.c
CC src/parser.c
CC src/tldr.c
CC src/utils.c
In file included from src/utils.c:12:0:
/mnt/home/jchen/.linuxbrew/Cellar/libzip/1.5.2_1/include/zip.h:261:1: error: C++ style comments are not allowed in ISO C90
 // clang-format on
 ^
/mnt/home/jchen/.linuxbrew/Cellar/libzip/1.5.2_1/include/zip.h:261:1: error: (this will be reported only once per input file)
make: *** [obj/utils.o] Error 1
make: *** Waiting for unfinished jobs....

READ THIS: https://docs.brew.sh/Troubleshooting

Just change two lines in zip.h, from `//clang-format on` and also `//clang-format off` to `/* clang-format on */` and `/* clang-format off*/

**Comment by yzcj105** [comment]
I think instead of a bug label, I should use complie label instead. But I don't know how to change that.

**Comment by 0-wiz-0** [comment]
Fixed, thanks.

**Comment by buddhi944** [comment]
**Thank you** very much for the help ......................
