### ISSUE TITLE
Centos 7 compile error during make install

### ISSUE THREAD

**Issue by Synida** [nih-at/libzip#154]
**Compiler Error**
```
$ sudo make
[ 46%] Built target zip
[ 85%] Built target man
[ 87%] Built target zipcmp
[ 87%] Built target zipmerge
[ 89%] Built target ziptool
[ 89%] Built target fuzz_main
/bin/sh: cmake: command not found
make[2]: *** [regress/CMakeFiles/testinput] Error 127
make[1]: *** [regress/CMakeFiles/testinput.dir/all] Error 2
make: *** [all] Error 2
```

**libzip Version**
1.6.1

**Operating System and Compiler**
Centos 7
cmake version 3.16.0

No flags were passed to `cmake`.

**Autodetected Configuration**
[CMakeCache.txt](https://github.com/nih-at/libzip/files/4293195/CMakeCache.txt)

**Additional context**
I'm not sure what am I doing wrong, but I need this library to be able to compile the zip extension with php(ZTS).

**Comment by 0-wiz-0** [comment]
Please debug this yourself:
````
/bin/sh: cmake: command not found
````
perhaps your root user's path does not contain cmake?

**Comment by Synida** [comment]
Solved, thank ya'!
