### ISSUE TITLE
ZLIB advertises ZLIB_INCLUDE_DIRS not ZLIB_INCLUDE_DIR

### ISSUE THREAD

**Issue by volo-zyko** [nih-at/libzip#162]
This is so since at least cmake 3.0. See, [here](https://cmake.org/cmake/help/v3.0/module/FindZLIB.html).

https://github.com/nih-at/libzip/blob/d9bffef2218cd442d24e29d2ed233822c9938091/CMakeLists.txt#L226

**Comment by 0-wiz-0** [comment]
Yes. Have you tried changing it? When I run cmake, only `ZLIB_INCLUDE_DIR` is defined.

**Comment by volo-zyko** [comment]
No, :) I trusted the docs. However, looking at the source code of [FindZLIB.cmake](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindZLIB.cmake#L115) there is indeed `ZLIB_INCLUDE_DIR` but it's internal ZLIB's variable. Few lines below `ZLIB_INCLUDE_DIRS` is defined. Maybe `ZLIB_FOUND` is not defined in your setup?

**Comment by 0-wiz-0** [comment]
No one has reported an actual problem with it, so I'll leave it as-is for now.
