### ISSUE TITLE
Zipmerge failing to preserve symlinks inside zip files

### ISSUE THREAD

**Issue by navsaini** [nih-at/libzip#165]
**Describe the Bug**
When using zipmerge to merge zip files, symbolic links present inside zip files is converted to a regular file with the symlink target as text in the file. 

**Expected Behavior**
Zipmerge should preserve symbolic links when merging zip files.

**Observed Behavior**
I know that the symlink attribute is stored in the external attributes of the directory entry. I looked into the code a little bit and saw that in `_zip_dirent_read`, we read the external attribute of the original file and store it in the zip directory entry. 

```
zde->ext_attrib = _zip_buffer_get_32(buffer); 
```

When logging these values, I noticed that it is indeed the same for regular files and symlinks, while different for other types of files such as directories and named pipes. I'm not sure why this value would be read as the same value for both regular files and symbolic links.

**To Reproduce**
```
$ echo "hello" > hello.txt
$ ln -s hello.txt hello_link
$ ls -al | grep hello_link
lrwxr-xr-x   1 user  staff     9 Apr 12 16:11 hello_link -> hello.txt
$ echo "hi" > hi.txt
$ zip a.zip hello.txt hello_link
$ zip b.zip hi.txt
$ ./zipmerge target.zip a.zip b.zip
$ mkdir target
$ mv target.zip target 
$ cd target
$ unzip target.zip
$ ls -al
total 32
drwxr-xr-x  6 user  staff  192 Apr 12 16:12 .
drwxr-xr-x  8 user  staff  256 Apr 12 16:12 ..
-rw-rw-rw-  1 user  staff    6 Apr 12 16:11 hello.txt
-rw-rw-rw-  1 user  staff    6 Apr 12 16:11 hello_link
-rw-rw-rw-  1 user  staff    3 Apr 12 16:11 hi.txt
-rw-r--r--  1 user  staff  315 Apr 12 16:12 target.zip
```

**libzip Version**
Latest version of repo as of 4/12/2020

**Operating System**
MacOS Mojave Version 10.14.5, also observed on some versions of Ubuntu

```
$ gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Test Files**
Described in "To Reproduce" section 

**Additional context**

**Comment by 0-wiz-0** [comment]
That's not a bug in `zipmerge`, it's in `unzip`. When I try your recipe, the symlink is already a plain file when I `unzip a.zip`.

**Comment by navsaini** [comment]
@0-wiz-0 My mistake, I forgot to include the symlinks flag in the example. However, when using that flag, `unzip` preserves the symbolic link.
```
$ echo "hello" > hello.txt
$ ln -s hello.txt hello_link
$ zip --symlinks a.zip hello.txt hello_link
$ echo "hi" > hi.txt
$ zip --symlinks b.zip hi.txt
$ rm hello.txt
$ rm hello_link
$ unzip a.zip
$ ls -al | grep hello_link
lrwxr-xr-x   1 user  staff       9 Apr 13 09:50 hello_link -> hello.txt
```
But when I combine it using `zipmerge`, the symbolic link is not preserved.
```
$ echo "hi" > hi.txt
$ zip --symlinks b.zip hi.txt
$ ./zipmerge target.zip a.zip b.zip
$ mkdir target
$ mv target.zip target/
$ unzip target.zip
$ ls -al
total 32
drwxr-xr-x   6 user  staff  192 Apr 13 09:53 .
drwxr-xr-x  12 user  staff  384 Apr 13 09:53 ..
-rw-rw-rw-   1 user  staff    6 Apr 13 09:32 hello.txt
-rw-rw-rw-   1 user  staff    9 Apr 13 09:49 hello_link
-rw-rw-rw-   1 user  staff    3 Apr 13 09:52 hi.txt
-rw-r--r--   1 user  staff  318 Apr 13 09:53 target.zip
```

**Comment by 0-wiz-0** [comment]
Ok, thanks for the new test case.
`zipmerge` seems to throw away the extra fields (not sure why) and change some of the extended attributes.

I'm not aware of a specification of how symlinks are supposed to be added to zip files, so this might take some time to fix.

**Comment by 0-wiz-0** [comment]
Please try the latest git version. https://github.com/nih-at/libzip/commit/c364f791ee7a0af87957c723f43950289724e70f contains the fix.

**Comment by navsaini** [comment]
@0-wiz-0 It works great! Thank you so much! How much testing were you able to do to ensure that no previous functionality was affected?

**Comment by 0-wiz-0** [comment]
Thanks for the feedback.

libzip has quite a nice regression test suite in the `regress` directory. These still run fine.
