### ISSUE TITLE
[Windows] missing compat.h

### ISSUE THREAD

**Issue by OgreTransporter** [nih-at/libzip#167]
**Compiler Error**
```
zipcmp.c(595): error C2065: "strcasecmp": nichtdeklarierter Bezeichner
```
and
```
ziptool.obj : error LNK2019: Verweis auf nicht aufgelöstes externes Symbol "strcasecmp" in Funktion "get_compression_method".
```

**libzip Version**
commit e0568ba8f9e3db1a9bb7e0fa9ee291092bdcf7b9

**Operating System and Compiler**
Windows 10, Visual Studio 2017

**Additional context**

Please add `#include "compat.h"` back in zipcmp.c and ziptool.c

See commit 00b3e34216ad25277a87285f66b5e8b4187bb4ca

**Comment by 0-wiz-0** [comment]
Thanks, re-added. I was watching the Appveyor build, but it hadn't progressed that far yet :)

**Comment by OgreTransporter** [comment]
I tried to run the test, but suddenly I could not build the project anymore ;-)
