### ISSUE TITLE
Windows build failing

### ISSUE THREAD

**Issue by gfgit** [nih-at/libzip#168]
Hi,
I'm building libzip from QtCreator 4.10.2
The compiler is MingW 5.3.0 32bit
The OS is Windows 8.1 64bit

I manually added the ZLIB_INCLUDE_DIR variable pointing to the zlib folder
CMake runs succesfully but then compiling fails due to
`zip_source_filep.c:247: error: undefined reference to `_zip_mkstempm'`
But _zip_mkstempm is present

I don't understand what I'm doing wrong!

**Comment by 0-wiz-0** [comment]
I don't know what you mean when you say you build libzip from QtCreator.
We support building with cmake. Something is strange in your infrastructure.

`_zip_mkstempm()` is only used if WIN32 is not defined, see
https://github.com/nih-at/libzip/blob/master/lib/zip_source_filep.c#L239
but in that case, the file `zip_mkstempm.c` is included in the build:
https://github.com/nih-at/libzip/blob/master/lib/CMakeLists.txt#L183

So your build infrastructure inconsistently defines the WIN32 symbol. You'll have to debug this yourself, sorry.

**Comment by gfgit** [comment]
Hi,
QtCreator is an IDE that integrates cmake.
I solved the issue by downloading the lates sources.
Previously I was using the source from the link in the libzip website that are not updated and do not include the compiler switch for WIN32
