### ISSUE TITLE
"zip_add_dir" cannot compress all files in a folder or sub-folder

### ISSUE THREAD

**Issue by xiaofeiyun123** [nih-at/libzip#169]
**Describe the Bug**
"zip_add_dir" cannot compress all files in a folder or sub-folder

**Expected Behavior**
 compress all files in a folder or sub-folder

**Observed Behavior**
Only folder is compressed

**To Reproduce**
Short program or code snippet that reproduces the problem.

**libzip Version**
Version of libzip or revision repository used.

**Operating System**
Operating system and version, used compiler.

**Test Files**
If applicable, attach and describe zip archives that trigger the problem.

**Additional context**

**Comment by xiaofeiyun123** [comment]
How to implement compress all files in a folder or sub-folder in Windows and Linux?

**Comment by dillof** [comment]
That is outside the scope of libzip. You will have to write code to traverse the file system and add all directories and files yourself.

**Comment by dillof** [comment]
I've just improved the man page to make this more obvious.
