### ISSUE TITLE
Large files with a ZIP64 field containing zeros cannot be unzipped

### ISSUE THREAD

**Issue by lukas9393** [nih-at/libzip#171]
Hi I use this library inside php (php-zip). Our service has received a large file (probably compressed with zip (Info-ZIP macos catalina))
The size of the packed file is 393.8 MB, unpacked this file has a size of 5.56 GB. 
The intention is to unpack this file using libzip, but unfortunately we get the following error message:

`can't open zip from source: Zip archive inconsistent`

The central directory file header of the file looks like this:

```
504b 0102	0	4	Central directory file header signature = 0x02014b50
2d03		4	2	Version made by
2d00		6	2	Version needed to extract (minimum)
0800		8	2	General purpose bit flag
0800		10	2	Compression method
ca40		12	2	File last modification time
9c50		14	2	File last modification date
9991 f98b	16	4	CRC-32 of uncompressed data
ffff ffff	20	4	Compressed size
ffff ffff	24	4	Uncompressed size
2800		28	2	File name length (n)
1c00		30	2	Extra field length (m)
0000		32	2	File comment length (k)
0000		34	2	Disk number where file starts
0000		36	2	Internal file attributes
2000 a481	38	4	External file attributes
0000 0000	42	4	Relative offset of local file header.

6465 5f44 455f 7072 6f64 7563 742d 6161 6161 6161 6161 6161 2d76 322d 6161 6161 6161 6161 2e63 7376     46  n   File name
0100 1800 3f57 994b 0100 0000 8c8d 7817 0000 0000 0000 0000 0000 0000  46+n m  Extra field
```

Since the file is larger than 4 GiB it results that the uncompressed size (and compressed size) is set to `FFFF FFFF` and an extra field is defined.

The extra field is of type ZIP64:

```
0100				0   2  Tag for this "extra" block type
1800				2   2  Size of this "extra" block
3f57 994b 0100 0000		4   8  Original uncompressed file size
8c8d 7817 0000 0000		12  8  Size of compressed data
0000 0000 0000 0000		20  8  Offset of local header record
<non-existent>			28  4  Number of the disk on which this file starts
``` 

I have looked at the current master branch and think I have found where the error has its origin.
The file zip_dirent.c has a section that takes care of this ZIP64 field [L504](https://github.com/nih-at/libzip/blob/aa0414fc6bb569305daf0204f7a8ae41c77e1ff9/lib/zip_dirent.c#L504):
 ```c
    if ((ef_buffer = _zip_buffer_new((zip_uint8_t *) ef, got_len)) == NULL) {
        zip_error_set(error, ZIP_ER_MEMORY, 0);
        if (!from_buffer) {
            _zip_buffer_free(buffer);
        }
        return -1;
    }

    if (zde->uncomp_size == ZIP_UINT32_MAX)
        zde->uncomp_size = _zip_buffer_get_64(ef_buffer);
    else if (local) {
        /* From appnote.txt: This entry in the Local header MUST
           include BOTH original and compressed file size fields. */
        (void) _zip_buffer_skip(ef_buffer, 8); /* error is caught by _zip_buffer_eof() call */
    }
    if (zde->comp_size == ZIP_UINT32_MAX)
        zde->comp_size = _zip_buffer_get_64(ef_buffer);
    if (!local) {
        if (zde->offset == ZIP_UINT32_MAX)
            zde->offset = _zip_buffer_get_64(ef_buffer);
        if (zde->disk_number == ZIP_UINT16_MAX)
            zde->disk_number = _zip_buffer_get_32(ef_buffer);
    }

    if (!_zip_buffer_eof(ef_buffer)) {
        zip_error_set(error, ZIP_ER_INCONS, 0);
        _zip_buffer_free(ef_buffer);
        if (!from_buffer) {
            _zip_buffer_free(buffer);
        }
        return -1;
    }
```

The variable got_len contains the value of 24 (0x18). The buffer loads the extra field with an offset of 2, since the tag and size are not required. Only the entries that are `FFFF` or `FFFF FFFF` are read from the field. This means that the "offset of local header record" is left out and thus, not read.
At the end the buffer checks if the offset and the size are identical, a difference is detected and therefore the error is thrown.

The check is found in `zi_buffer.c` [L60](https://github.com/nih-at/libzip/blob/aa0414fc6bb569305daf0204f7a8ae41c77e1ff9/lib/zip_buffer.c#L60):

```c
_zip_buffer_eof(zip_buffer_t *buffer) {
    return buffer->ok && buffer->offset == buffer->size;
}
```

I can't gain a deep understanding for this behavior, why the zeros are written for "Offset of local header record" and not for "Number of the disk". I assume that this is  allowed or probably not defined exactly. 

Nevertheless, I would suggest that the zeros should be tollerated in both above mentioned fields and the buffer should not throw any error messages.

**Comment by dillof** [comment]
I've done some digging, and this archive is not strictly conforming to the spec (see below). info-Zip zip does not write such archives (at least the latest version), but Info-Zip unzip accepts them.

We will relax our checks to accept such archives.

This is clearly specified in the appnote (docs/appnote.txt): Fields in the Zip64 extra field are only present if the corresponding entry in the central directory is all FFs:

   4.4.16 relative offset of local header: (4 bytes)

       This is the offset from the start of the first disk on
       which this file appears, to where the local header should
       be found.  If an archive is in ZIP64 format and the value
       in this field is 0xFFFFFFFF, the size will be in the 
       corresponding 8 byte zip64 extended information extra field.

   4.5.3 -Zip64 Extended Information Extra Field (0x0001):

      The following is the layout of the zip64 extended 
      information "extra" block. If one of the size or
      offset fields in the Local or Central directory
      record is too small to hold the required data,
      a Zip64 extended information record is created.
      The order of the fields in the zip64 extended 
      information record is fixed, but the fields MUST
      only appear if the corresponding Local or Central
      directory record field is set to 0xFFFF or 0xFFFFFFFF.

**Comment by dillof** [comment]
I've just committed the change, please let me know if it works for your archive.

**Comment by lukas9393** [comment]
Perfect, this solution works now for my archive. Thanks a lot for that. It's exactly what I've tried to point out with my issue. In my opinion that ticket can be closed. Thanks again!
