### ISSUE TITLE
Implement zip_commit()

### ISSUE THREAD

**Issue by lszolnoki** [nih-at/libzip#174]
**Description**
I know that zip_commit() is already on the roadmap (TODO.md), but I woud like to add a use case.

**Use case**
Consider a web scraper that downloads HTML and image files straight into a zip file while it recursively downloads dependencies (like wget). Once an initial HTML document is downloaded and scanned for dependencies it could be committed to the zip archive before its dependencies.

**Describe alternatives you've considered**
1. One can zip_close() and zip_open() to flush zip_sources kept in memory.
* This breaks the atomic nature of a "transaction" that zip_archive represents.
* This probably creates more directory records in the zip archive, creating overhead.
  * I am not sure about this one, libzip could potentially strip a directory record from the very end of an existing archive before adding new files to it.
2. One can implement a temporary file backed zip_source for external sources.
* Writing the file to disk then reading back to zip it sort of defeats the purpose of this exercise.

**Comment by dillof** [comment]
zip_commit() would be basically equivalent to zip_close() / zip_open(). It would create exactly the same archive on disk.

**Comment by lszolnoki** [comment]
Oh, ok. Does a zip_close() / zip_open() between adding files add extra directory records to the zip file?

**Comment by dillof** [comment]
No, every file added to the zip archvie gets exactly one directory entry, no matter how often you close/open the archive.

However, unless you are on a file system that supports cloning (BTFS on Linux, APFS under macOS), a zip_close() has to write the whole archive to disk each time. (This would be the same for zip_commit()).

**Comment by lszolnoki** [comment]
> No, every file added to the zip archvie gets exactly one directory entry, no matter how often you close/open the archive.

That's good to know.

> However, unless you are on a file system that supports cloning (BTFS on Linux, APFS under macOS), a zip_close() has to write the whole archive to disk each time. (This would be the same for zip_commit()).

Hmm, I guess I wouldn't need a zip_commit() then but a zip_flush()? Something that appends new files to the temporary file backing the zip_archive so I could discard zip sources I don't need anymore. Writing the whole archive each time I want to discard zip sources that I can't keep in memory anymore seems unnecessarily expensive.

**Comment by dillof** [comment]
That adds a lot of complexity and does not work well for many use cases. What if you delete a file between two flushes? Then we have to rewrite again, in order to close the hole.

Besides, if the user interrupts the download or your program crashes, with periodic zip_close() calls, all files downloaded up to that point are retained. WIth flush, they would all be lost (since they are stored in a temporary file that is not even a valid zip archive).

I’m afraid that is more complexity than we are willing to add for the limited utility it provides.

**Comment by lszolnoki** [comment]
Understandable, zip_flush() indeed looks too complex for this use case.

An other approach would be to not only allow a single file as source, but an abstract collection of files with file names. Then this collection could retrieve and discard external files as necessary while zip_close() walks over it.
