### ISSUE TITLE
Version number blank, unable to compile with libzip as a dependency

### ISSUE THREAD

**Issue by cglmrfreeman** [nih-at/libzip#177]
**Describe the Bug**
A compilation of libzip from a git repo omits the version number. When compiling an application that looks for a version number of libzip to see if you have a version greater than some previous version of libzip, the compile will fail. Specifically, I am trying to use cmake to create a makefile, and I recieve the following error:
```
configure: error: Package requirements (libzip >= 0.10) were not met:
Package dependency requirement 'libzip >= 0.10' could not be satisfied.
Package 'libzip' has version '', required version is '>= 0.10'

```
**Expected Behavior**
I expected the cmake configuration to pass the libzip check of a version greater than 0.10.

**Observed Behavior**
A clear and concise description of what actually happened.
The cmake configuration failed to see a libzip greater than version 0.10 because the version was ' '.

**To Reproduce**
Short program or code snippet that reproduces the problem.
None available to provide, but the program I was attempting to build was [ideviceinstaller](https://github.com/libimobiledevice/ideviceinstaller).

**libzip Version**
Version of libzip or revision repository used.
https://github.com/nih-at/libzip.git
**Operating System**
Operating system and version, used compiler.
OpenSUSE Tumbleweed 20200519 x86_64 Linux 5.6.12-1-default
cmake version 3.17.2
**Test Files**
If applicable, attach and describe zip archives that trigger the problem.

**Additional context**

**Comment by 0-wiz-0** [comment]
Fixed, thanks for the report!
