### ISSUE TITLE
cmake target dist

### ISSUE THREAD

**Issue by malytomas** [nih-at/libzip#179]
**Compiler Error**
CMake Error at externals/cage/externals/libzip/libzip/CMakeLists.txt:81 (ADD_CUSTOM_TARGET):
  ADD_CUSTOM_TARGET cannot create target "dist" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "E:/personal/flittermouse/externals/cage/externals/jpeg/jpeg".  See
  documentation for policy CMP0002 for more details.

**libzip Version**
Commit 34d80f56c003ae88753ef998607d97e3158eb222

**Operating System and Compiler**
Windows, cmake 3.17.0, (msvc)

**Additional context**

Commit 2bc0d5a6bec74031ed12ff7727d857a5c8361d02 has removed the check whether target _dist_ already exists. Please restore that check so that the libzip can be used with add_subdirectory in a larger project.

The target _distcheck_ should be under the same condition.

**Comment by malytomas** [comment]
Thanks for such a quick reaction.

However, the current fix looks a bit dangerous. The target `distcheck` depends on target `dist` and should be enabled only if neither existed. Currently, it may depend on foreign target dist.

It should be something like:
```cmake
if(NOT TARGET dist)
  add_custom_target(dist)
  if(NOT TARGET distcheck)
    add_custom_target(distcheck)
    add_dependencies(distcheck dist)
  endif()
endif()
```

I apologize for not being clear enough in the beginning.
I hope this makes sense.
Thanks again.

**Comment by 0-wiz-0** [comment]
Thanks, that makes sense. I've combined both of them under one `if()`.
