### ISSUE TITLE
make cmake install optional

### ISSUE THREAD

**Issue by malytomas** [nih-at/libzip#180]
Please add an option into cmake to disable install.

I am using libzip via add_subdirectory and I do not want libzip to be installed alongside my superproject files. I build libzip as a static library and do not need it in the installation.

Thanks.

**Comment by 0-wiz-0** [comment]
Sure.
Is there some CMake support for this (some standard macros or common patterns) or do I just add a `LIBZIP_DO_INSTALL` variable that defaults to `ON` and make installation dependent on that?

**Comment by malytomas** [comment]
I am not aware of any common way to do this (unfortunately).
`LIBZIP_DO_INSTALL` sounds good.

**Comment by 0-wiz-0** [comment]
Implemented, thanks for the suggestion.
