### ISSUE TITLE
Make zip_ftell() work for compressed files too

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#184]
At the moment, `zip_ftell()` only works on uncompressed (stored) files. When called on compressed files, it returns an error.
See [doc](https://libzip.org/documentation/zip_ftell.html).

Supporting `zip_ftell()` for compressed files should be fairly simple. It is just a matter of counting how many bytes have been read from this file so far.

**Comment by dillof** [comment]
This is now implemented in git HEAD.

Could you please give it a try?

**Comment by fdegros** [comment]
Thanks.

I reviewed the change and tested it. I confirm that `zip_ftell()` can now return the current position in compressed files.
