### ISSUE TITLE
Add function to duplicate file handle zip_file_t

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#185]
I would be interested in a function duplicating an open file handle `zip_file_t`. Something like:

```
zip_file_t* zip_fdup(zip_file_t* file);
```

The returned _duplicated_ file handle should initially be at the same file position and in the same state as the given _original_ file handle. Afterwards, both handles can be read independently at their own pace with [`zip_fread()`](https://libzip.org/documentation/zip_fread.html), and eventually independently closed with [`zip_fclose()`](https://libzip.org/documentation/zip_fclose.html).

This is particularly interesting for compressed files since [`zip_fseek()`](https://libzip.org/documentation/zip_fseek.html) doesn't work with them. This would allow to create _backup points_ at specific positions while decoding a compressed file, and later start decoding from these backed-up positions again without having to start from the beginning of the file.

**Comment by dillof** [comment]
The compression libraries used in libzip do not support cloning their internal state, so resuming compression from an earlier point is not supported.

So, unfortunately, we cannot implement this feature.

**Comment by fdegros** [comment]
I was more thinking about resuming decompression than resuming compression.

FYI, the [`zlib`](https://zlib.net/manual.html) library has a `deflateCopy` function that does exactly that, if I understand the documentation correctly.

**Comment by dillof** [comment]
Could you please check in which version of zlib this was added, and thus by how much it would raise our requirement?

Could you also check which of the other compression libraries we use support such a feature, and which support it for compression as well?

If the majority support this, we could add a new method to zip_source for it.

**Comment by fdegros** [comment]
The function `deflateCopy` exists at least since `zlib` 1.0.6 (19 Jan 1998).

https://github.com/madler/zlib/commit/7850e4e406dce1f7a819297eeb151d1ca18e7cd9

As for the other decompression libraries, I don't know. My use case only relies on `libzip` + `zlib`.

My concern was more about the decryption engine used for encrypted files in a ZIP. If a file is both compressed and encrypted, I guess that the states of both the decompression and the decryption engines must then be correctly duplicated and kept in sync.

**Comment by dillof** [comment]
If it’s only supported for decompressing with libzip, that’s too narrow a use case for us to add the extra complexity.

And you are right, it would be good if it were also supported by the various encryption backends.

**Comment by fdegros** [comment]
This feature would be useful even if it worked only with `zlib`, ie `deflate`-compressed files. I guess it is probably possible for it to return a _not implemented_ or _not supported_ error with other compression libraries.

This feature would allow us to create _restart points_ at regular intervals when decompressing a big file. These _restart points_ could then be used to efficiently "jump back" into the file without having to cache the whole decompressed data. This would allow us to do for compressed files what `zip_fseek` already does for uncompressed files. This would provide an important optimisation opportunity, especially on 32-bit devices with limited memory and disk space.

**Comment by dillof** [comment]
I understand the usefulness, but it is probably not worth adding the extra complexity if it is only supported in one specific configuration, even if it is the most common one.

You are asking us to implement and maintain this complexity. I was asking you to investigate which other configurations could support this, which you have so far declined to do. If this feature is this important to you, please put in the effort.

**Comment by fdegros** [comment]
I could test and use this feature if it existed. I see an optimisation opportunity here. But I cannot justify investing much more time on adding this feature at the moment, since I can get things working without it (albeit less efficiently).

**Comment by dillof** [comment]
So it seems like no one is willing to invest the effort to make this feature happen.

**Comment by fdegros** [comment]
Understood. If one day you decide to implement this feature, let me know. I might still be able to test and use it, then.
