### ISSUE TITLE
zip archive inconsistent

### ISSUE THREAD

**Issue by jccardot** [nih-at/libzip#186]
**Describe the Bug**
When trying to open the attached archive [v-pulsar.zip](https://github.com/nih-at/libzip/files/4872834/v-pulsar.zip), I get: "Zip archive inconsistent"
Note: first I spotted this in ark.

**Expected Behavior**
The zip is ok with other archivers, it should not be considered inconsistent.

**Observed Behavior**
I observed the behaviour in ark, with the version installed by my distribution (lib64zip5-1.5.2-1.mga7).
To be sure the bug was still present upstream, I git cloned the last version (master) and compiled it.
Here is the result:

[fred@localhost libzip]$ LD_LIBRARY_PATH=/home/fred/compil/libzip/build/lib/ /home/fred/compil/libzip/build/src/ziptool -c  /tmp/v-pulsar.zip get_archive_comment
can't open zip archive '/tmp/v-pulsar.zip': Zip archive inconsistent

**Operating System**
GNU Linux, Mageia 7, gcc (Mageia 8.4.0-1.mga7) 8.4.0

**Test Files**
attached

**Comment by 0-wiz-0** [comment]
There are multiple problems with this file. Basically, it contains two unrelated zip archives. First there is one of ~120kB that contains `PULSAR.MDL`, `FILE_ID.DIZ`, `VSL.APP`, and `VSL.NFO`; then follows a second one that contains `LOVER-LO.XM`, `FILE_ID.DIZ`, `VSL.APP`, and `VSL.NFO`.
Both files have truncated zip archive comments (which I think is the main reason libzip rejects it).

Depending on how you parse the file (front first or from the back) you'll get different files.

InfoZIP unzip reports:
````
caution:  zipfile comment truncated
warning [v-pulsar.zip]:  121185 extra bytes at beginning or within zipfile
````
i.e. it ignores the first zip archive.

I think it's correct for libzip to reject this.

**Comment by jccardot** [comment]
Thanks for the analysis of the zip file, I was not aware. This is a zip date 1996 I have on my disc, and I found this problem. Obviously the problem is the zip, not libzip :D
Note: Ark without libzip (I don't know which lib it uses in this case) sees the other zip file.
