### ISSUE TITLE
not successfully linking with lzma

### ISSUE THREAD

**Issue by paradoxon82** [nih-at/libzip#187]
**Compiler Error**
LINK: command "C:\PROGRA~2\MICROS~1\2019\BUILDT~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\zip.dir\objects1.rsp /out:zip.dll /implib:zip.lib /pdb:C:\Users\danie\git\libzip-1.7.1\build\lib\zip.pdb /dll /version:5.3 /machine:x64 /INCREMENTAL:NO C:\OSGeo4W64\lib\zlib.lib C:\Users\danie\git\bzip2-1.0.8\libbz2.lib C:\Users\danie\git\xz-5.2.5\windows\vs2019\Release\x64\liblzma\liblzma.lib bcrypt.lib advapi32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:zip.dll.manifest" failed (exit code 1120) with the following output:
   Creating library zip.lib and object zip.exp
zip_algorithm_xz.c.obj : error LNK2019: unresolved external symbol __imp_lzma_code referenced in function process
zip_algorithm_xz.c.obj : error LNK2019: unresolved external symbol __imp_lzma_end referenced in function end
zip_algorithm_xz.c.obj : error LNK2019: unresolved external symbol __imp_lzma_lzma_preset referenced in function start
zip_algorithm_xz.c.obj : error LNK2019: unresolved external symbol __imp_lzma_stream_encoder referenced in function start
zip_algorithm_xz.c.obj : error LNK2019: unresolved external symbol __imp_lzma_alone_encoder referenced in function start
zip_algorithm_xz.c.obj : error LNK2019: unresolved external symbol __imp_lzma_stream_decoder referenced in function start
zip_algorithm_xz.c.obj : error LNK2019: unresolved external symbol __imp_lzma_alone_decoder referenced in function start

**libzip Version**
1.7.1

**Operating System and Compiler**
Windows 10, nmake, visual c++ 2019 complier 

Also, any flags passed to `cmake`.

**Autodetected Configuration**
[CMakeCache.txt](https://github.com/nih-at/libzip/files/4873176/CMakeCache.txt)

**Additional context**
Trying to use the libzlib with the xz package version 5.2.5

**Comment by 0-wiz-0** [comment]
Sorry, we do not actively support Windows. It works in the appveyor build, see e.g. https://ci.appveyor.com/project/nih-at/libzip/build/job/p0ix5vnpks25gjbc
Please let us know if you find something that needs changing on the libzip side.
