### ISSUE TITLE
Linking error while using -DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld

### ISSUE THREAD

**Issue by bapi23** [nih-at/libzip#188]
**Compiler Error**
/usr/local/bin/cmake -S/home/bpiekny/development/projects/libzip -B/home/bpiekny/development/projects/libzip/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/bin/cmake -E cmake_progress_start /home/bpiekny/development/projects/libzip/build/CMakeFiles /home/bpiekny/development/projects/libzip/build//CMakeFiles/progress.marks
make -s -f CMakeFiles/Makefile2 all
[  1%] Built target nonrandomopen
Scanning dependencies of target zip
[ 41%] Built target man
[ 41%] Building C object lib/CMakeFiles/zip.dir/__/zip_err_str.c.o
[ 41%] Linking C shared library libzip.so
/usr/bin/ld.lld: error: unknown argument: --push-state
/usr/bin/ld.lld: error: unknown argument: --pop-state
/usr/bin/ld.lld: error: unknown argument: --push-state
/usr/bin/ld.lld: error: unknown argument: --pop-state
collect2: error: ld returned 1 exit status
lib/CMakeFiles/zip.dir/build.make:1862: recipe for target 'lib/libzip.so.5.3' failed
make[2]: *** [lib/libzip.so.5.3] Error 1
CMakeFiles/Makefile2:284: recipe for target 'lib/CMakeFiles/zip.dir/all' failed
make[1]: *** [lib/CMakeFiles/zip.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 41%] Built target testinput
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**libzip Version**
Master,
hash: 5ce73a9ae91b3549d1e17a1ca05719dbed98bb2e

**Operating System and Compiler**
Ubuntu 18.04,
gcc (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
and
default gcc 7.3

Also, any flags passed to `cmake`.
-DCMAKE_SHARED_LINKER_FLAGS=-fuse-ld=lld

**Autodetected Configuration**
[CMakeCache.txt](https://github.com/nih-at/libzip/files/4904445/CMakeCache.txt)

**Additional context**

**Comment by 0-wiz-0** [comment]
You didn't fill in all the information, and I don't even know what you want to achieve with that flag. Please debug it yourself some more.
