### ISSUE TITLE
add ways to get file attributes likes general purpose flags

### ISSUE THREAD

**Issue by glanium** [nih-at/libzip#189]
There is struct called zip_file_attributes in zip.h
But how to acess this struct??

I need to access general purpose flags in central file headers

**Comment by 0-wiz-0** [comment]
You probably already found https://libzip.org/documentation/zip_file_get_external_attributes.html

Can you please be more specific what you want to access?

AFAIK, of the values that an application might want to access/modify, only the ASCII-bit is not available.
Otherwise (IMO) of the general purpose bit flags are not intended to be set by applications and are handled by libzip automatically.

**Comment by glanium** [comment]
I need to decode file name using custom encoding
If Bit11 in general purpose bit flags is set, I decode file name with UTF8
But If it is not set, I decode file name with encodings(user specify or locale default) other than UTF8.

So I need to access bit11 in general purpose bit flags to decide which encoding to use.

**Comment by 0-wiz-0** [comment]
You're in luck - you don't have to do anything. libzip does it automatically for you. See https://libzip.org/documentation/zip_get_name.html

**Comment by glanium** [comment]
I know these flags like ZIP_FL_ENC_GUESS
But these flags suppors all encoding like here https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers

It seems these flags support very limited subset...

I need to support encoding(code page) like here https://docs.microsoft.com/en-us/windows/win32/intl/code-page-identifiers

**Comment by glanium** [comment]
Some C#/Java zip library have ways to specify the encoding for file name(comment)  with bit11 flag in general purpose bit flags cleared for this purpose

for example, .NET standard ZipArchive class has contructor that accept encoding parameter for this purpose.

https://docs.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchive.-ctor?view=netcore-3.1#System_IO_Compression_ZipArchive__ctor_System_IO_Stream_System_IO_Compression_ZipArchiveMode_System_Boolean_System_Text_Encoding_

**Comment by 0-wiz-0** [comment]
I don't see the relevance of the links you posted. File names in ZIP archives are either CP-437 or UTF-8 (if bit 11 is set).
When reading names with libzip you'll by default always get UTF-8 and will have to convert to the encoding you want yourself.
When writing, you'll have to convert from your encoding to UTF-8 yourself and pass that value to libzip.

If you know that a zip archive was _not_ written by a standard-compliant tool, you can get the file name directly using `ZIP_FL_ENC_RAW` and convert it yourself to whatever you need.

**Comment by glanium** [comment]
Before UTF-8 flag(Bit11) introduced, many archivers used encodings other than CP-437 in practise
Even Windows Explorer built-in comppressed zipped folder used the encoding other than CP-437.

anyway, i give up. thx

**Comment by 0-wiz-0** [comment]
I'm sorry, the code page information is not included in the zip archive (except for the UTF-8 bit). So if you suspect the data is not in CP-437, you'll have to guess the encoding.

**Comment by glanium** [comment]
>If you know that a zip archive was not written by a standard-compliant tool, you can get the file name directly using ZIP_FL_ENC_RAW and convert it yourself to whatever you need.

Yes, it's what i want to do. 
But it is impossible to do it without accessing general purpose bit flags.

My program is like the following

zip_stat_t stat;
zip_stat_index(zip, index, ZIP_FL_ENC_RAW, &stat);
auto flags = get_general_purpose_bit_flags(index) <----------- this is required
if (bit 11 is set in flags)
{
  // if bit 11 is set, follow zip standard spec
  convert stat.name using utf8
}
else
{
  // convert name myself to whatever i need
  convert stat.name using custom encoding
}

**Comment by dillof** [comment]
You could check if the name returned with ZIP_FL_ENC_RAW is valid UTF-8. If it is, it was most likely encoded as UTF-8 in the zip archive. If not, use your own conversion, as if bit 11 was not set.

This is an edge case for not strictly complying zip archives, and I don't want to complicate the API further for it.
