### ISSUE TITLE
libzip 1.7.2: few cmake tweaks needed

### ISSUE THREAD

**Issue by pgajdos** [nih-at/libzip#192]
Hello,

I needed several cmake tweaks. In te contrast of 1.7.1, I am missing a posibility (where applicable):
(1) install libraries, pkconfig/libzip.pc and cmake/libzip under `/usr/lib64` instead of `/usr/lib` prefix,
(2) install man pages under `/usr/share/man` instead of `/usr/man`.
(3) Reflect *.pc file the change of library location.

See for details:
https://build.opensuse.org/package/view_file/devel:libraries:c_c++/libzip/libzip-cmake-rules.patch

**Comment by 0-wiz-0** [comment]
These problem should all be fixed by the commits up to 
https://github.com/nih-at/libzip/commit/60a6bf356bf05492ac1c94c55b5e07c330bfc4a1

**Comment by pgajdos** [comment]
True. Thanks!
