### ISSUE TITLE
Provide a public api for obtaining an error string from an error code

### ISSUE THREAD

**Issue by UnknownEclipse** [nih-at/libzip#193]
Description
Provide a public function for turning a zip error code into a human readable string, as in strerror or zError. This would be useful in the case of calling zip_open and getting an error message without first creating a zip_error_t, and in the case of c++ interaction, where a custom error_category to adapt the error codes would be helpful.

Solution
From what I can see, a function that performs a bound-checked index operation on the internal array _zip_err_str should be sufficient.

**Comment by dillof** [comment]
Sorry, if you want a human readable representation of an error code that is not already stored in a zip_error_t (which only happens with zip_open), you will have to fill in a zip_error_t.

It's just four lines of code:
```C
zip_error_t error;
zip_error_init_with_code(&error, err);
const char *error_string = zip_error_strerror(&error));
/* use error_string */
zip_error_fini(&error);
```
