### ISSUE TITLE
Document libzip's thread safety

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#196]
What are libzip's guarantees in the face of multiple threads?

Libzip's documentation doesn't mention multithreading. However, it would be useful to know and document the thread safety of its various functions.

For example:

- Can separate ZIP archives be concurrently opened and closed via `zip_open` and `zip_close`? (Or is there some shared state between archives that is accessed in an unsynchronized way?)
- Can separate `zip_t` archives be concurrently operated on?
- Can separate `zip_file_t` objects be concurrently opened and closed via `zip_fopen` and `zip_fclose`? Even if they come from the same `zip_t` archive? 
- Can separate `zip_file_t` objects be concurrently operated on? Even if they come from the same `zip_t` archive? Even if they are linked to the same file inside an archive?

**Comment by dillof** [comment]
Excellent questions, we'll update the documentation.

Short answer: zip archives are independent of each other, everything you do with one archive is not thread save (including files opened from them).

What follows from this but may not be immediately obvious: if you add a file from one archive to another,  accessing that added file or closing the archive it was added to accesses the first archive and therefore must synchronise both archives.
