### ISSUE TITLE
Get the error code of a file-related operation

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#197]
How can I get the *error code* of a failed operation on a `zip_file_t`?

I can get the *error message* using `zip_file_strerror`. But I'm not sure how to get the matching error code.

**Comment by dillof** [comment]
Use `zip_file_get_error()`.

**Comment by fdegros** [comment]
Thanks.

I was looking at https://libzip.org/documentation/libzip.html and `man libzip`, and `zip_file_strerror` is not mentioned there. It might be worth adding it.

**Comment by dillof** [comment]
Thanks, Thomas fixed it.

The main documentation page is at https://libzip.org/documentation/ which is auto-generated from all man pages.

**Comment by fdegros** [comment]
Understood.

I still like https://libzip.org/documentation/libzip.html. I find the grouping of functions by category very useful.
