### ISSUE TITLE
Build failure with gnutls and cmake < 3.16

### ISSUE THREAD

**Issue by ffontaine** [nih-at/libzip#199]
**Compiler Error**
```
CMake Error at lib/CMakeLists.txt:5 (add_library):
  Target "zip" links to target "GnuTLS::GnuTLS" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

Full build log: http://autobuild.buildroot.org/results/55f/55f23beb55126204f71f3b195879318630c2d600//build-end.log

**libzip Version**
1.7.3

**Operating System and Compiler**
Buildroot with cmake 3.15.5

Also, any flags passed to `cmake`.
`
-DCMAKE_INSTALL_PREFIX="/usr" -DCMAKE_COLOR_MAKEFILE=OFF -DBUILD_DOC=OFF -DBUILD_DOCS=OFF -DBUILD_EXAMPLE=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TEST=OFF -DBUILD_TESTS=OFF -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON  -DENABLE_BZIP2=ON -DENABLE_GNUTLS=ON -DENABLE_MBEDTLS=OFF -DENABLE_OPENSSL=ON -DCMAKE_EXE_LINKER_FLAGS=-lfts -DENABLE_LZMA=OFF`

**Autodetected Configuration**
http://autobuild.buildroot.org/results/55f/55f23beb55126204f71f3b195879318630c2d600//libzip-1.7.3/CMakeCache.txt

**Additional context**
The build failure is due to commit d5859063d5daea357f5b7c29efad8156bfd5856 which added a call to GnuTLS::GnuTLS however this target is only available since cmake 3.16.0 and https://github.com/Kitware/CMake/commit/44e8b8f1f222c0227ed72d09310e30524bda9935. I would advise to add the FindGnuTLS.cmake from cmake into cmake-compat.

**Comment by 0-wiz-0** [comment]
Please try https://github.com/nih-at/libzip/commit/73f6f8ebff678a0847e6b197b574082cc285b528.

**Comment by ffontaine** [comment]
Thanks, this patch was applied to buildroot and it fixes the build failure on the autobuilders

**Comment by goehte** [comment]
Hello,
I'm also getting the same"GnuTLS" cmake error from first post.

May sysadmin has only installed `cmake version 3.10.2` and I cannot update it.
It there any further workaround?

**Comment by 0-wiz-0** [comment]
There was a commit that is referenced in this issue. Just use libzip from git and it should work fine.
If not, we need more details.
