### ISSUE TITLE
Mercurial down at hg.nih.at possible to create pointer to this repo ?

### ISSUE THREAD

**Issue by xoryouyou** [nih-at/libzip#2]
Hi Not Invented Here,

seems like your mercurial is down at `hg.nih.at` the apache returns a 502 since yesterday.

I needed a special version of your libzip to build a project and was searching for an alternative source and found this repo by luck.

I don't know if you mainly develop on mercurial or git but it would be nice to have a pointer up at `hg.nih.at` to this repo  so no time is wasted googling around :)

**Comment by 0-wiz-0** [comment]
I've just fixed `hg.nih.at`. `README.md` now contains links to both the official hg repository as well as the github mirror. Thanks!

**Comment by xoryouyou** [comment]
@0-wiz-0 perfect! Thanks alot.
