### ISSUE TITLE
XZ (Method 95): WinZip expects Version Required = 20, otherwise refuses to extract the archive

### ISSUE THREAD

**Issue by jloqfjgk** [nih-at/libzip#200]
**Test files**
[WinZip-xz.zip](https://github.com/nih-at/libzip/files/4988431/WinZip-xz.zip)
[libzip-xz.zip](https://github.com/nih-at/libzip/files/4988432/libzip-xz.zip)

**Bug description**
Zip file using XZ (Method 95) created by libzip cannot be extracted in WinZip.
However, bsdtar (libarchive), 7-Zip 19.00 and p7zip 16.02 can extract the Zip file successfully.

**Steps to reproduce**
1. Open [libzip-xz.zip](https://github.com/nih-at/libzip/files/4988432/libzip-xz.zip) in WinZip.
2. WinZip throws an error.
3. Rename `.zip` to `.zipx`.
4. WinZip still throws the same error.

Error message:
```
Extracting to "Z:\test\"
Use Path: yes   Overlay Files: no
Skipping abac-repeat.txt: this file is not in the standard Zip 2.0 format.
   Please see www.winzip.com/zip2.htm for more information.
   Version needed value for this file is 63.
   Compression method value is 95.
There are no matching files in the archive. Nothing to extract.
Warning: No files found to extract.
```

**libzip version**
3b65662

**Additional information**
libzip (as well as 7-Zip and p7zip) can open the [file created by WinZip](https://github.com/nih-at/libzip/files/4988431/WinZip-xz.zip).

The Unarchiver (unar) fails to open both files so I suppose unar does not really support XZ.

Producer | File | Extracts in WinZip? | Extracts in libzip, 7-Zip, p7zip and bsdtar? | Extracts in unar?
------------ | ------------- | ------------- | ------------- | -------------
libzip | [libzip-xz.zip](https://github.com/nih-at/libzip/files/4988432/libzip-xz.zip) | **No** | Yes | No (Failed! (File is not fully supported))
WinZip | [WinZip-xz.zip](https://github.com/nih-at/libzip/files/4988431/WinZip-xz.zip) | Yes | Yes | No (Failed! (File is not fully supported))

**Comment by 0-wiz-0** [comment]
I think that's a bug in Winzip, like for zstd. XZ compression was added to appnote.txt in 6.3.8, so version-required should be set to 6.3, but Winzip does not accept it if it's not 2.0.
Worked around in 9f8a3eb29e3446f4aafe9675e5bcbcbfe054990b but if you know someone at Winzip, they should fix it...
