### ISSUE TITLE
Make zip_fseek() work for compressed files too

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#201]
At the moment, `zip_fseek()` only works on uncompressed (stored) files. When called on compressed files, it returns an error.
See [doc](https://libzip.org/documentation/zip_fseek.html).

Now that `zip_ftell()` works for compressed files, would it make sense to make `zip_fseek()` work for compressed files too? As a first approximation, I would be happy with a naive and inefficient implementation such as:

```
  if (file is stored) {
    // Use existing and fast zip_fseek() implementation
    ...
    return 0;
  }

  // File is compressed
  if (current_position > new_position) {
    // Reset position to the beginning of the file, similar to closing and reopening the file,
    // but keeping the same zip_file_t object
    ...
    current_position = 0;
  }

  // Skip (new_position - current_position) bytes
  while (current_position < new_position) {
    // Read or decode up to (new_position - current_position) bytes
    ...
    current_position += ...;
  }   
```

Of course, if libzip can provide a more efficient implementation, that would be even better.

**Comment by 0-wiz-0** [comment]
There is no efficient way to do this, and we do not want to encourage this. If you need this, you'll have to write it yourself.
