### ISSUE TITLE
zip_fopen_index() fails with ZIP_ER_INVAL "Invalid argument" instead of ZIP_ER_WRONGPASSWD "Wrong password"

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#204]
**Describe the Bug**

1. Open a ZIP with `archive = zip_open(...)`
2. Set an empty password with `zip_set_default_password(archive, "")`. 
Note that the password is an empty string, not a `NULL` pointer.
3. Try to open an AES-encrypted file with `zip_fopen_index(archive, index, 0)`.

**Expected Behavior**

`zip_fopen_index` should fail with error `ZIP_ER_WRONGPASSWD` (Wrong password).

**Observed Behavior**

`zip_fopen_index` fails with error `ZIP_ER_INVAL` (Invalid argument).

This *Invalid argument* error is misleading and hard to diagnose. The arguments passed to `zip_fopen_index` seem all valid. There is no indication in [`zip_set_default_password`](https://libzip.org/documentation/zip_set_default_password.html) documentation that an empty string constitutes an invalid password argument, and the call to `zip_set_default_password(archive, "")` succeeds.

If you change the password to a `NULL` pointer, then `zip_fopen_index` fails with error `ZIP_ER_NOPASSWD` (No password provided), which is the expected behaviour.
If you change the password to a non-empty string, then `zip_fopen_index` fails with error `ZIP_ER_WRONGPASSWD` (Wrong password provided), which is the expected behaviour.
If you try to open a ZipCrypto-encrypted file, then `zip_fopen_index` fails with error `ZIP_ER_WRONGPASSWD` (Wrong password provided), which is the expected behaviour. 

I would like the empty but non-`NULL` password to be treated the same way with AES-encrypted files as a non-empty password.

**libzip Version**

1.7.3

**Test Files**

- [Encrypted AES-128.zip](https://source.corp.google.com/chromeos_public/src/third_party/autotest/files/client/site_tests/platform_CrosDisksArchive/data/Encrypted%20AES-128.zip)
- [Encrypted AES-192.zip](https://source.corp.google.com/chromeos_public/src/third_party/autotest/files/client/site_tests/platform_CrosDisksArchive/data/Encrypted%20AES-192.zip)
- [Encrypted AES-256.zip](https://source.corp.google.com/chromeos_public/src/third_party/autotest/files/client/site_tests/platform_CrosDisksArchive/data/Encrypted%20AES-256.zip)

**Additional context**

The ZIP archive is open in read-only mode. I don't know if this is relevant or not.

I don't know if `zip_fopen`, `zip_fopen_encrypted` and `zip_fopen_index_encrypted` exhibit the same problem. I only tried with `zip_fopen_index`.

**Comment by fdegros** [comment]
Ping! Any news on this bug?

**Comment by fdegros** [comment]
Ping?

**Comment by 0-wiz-0** [comment]
Fixed in https://github.com/nih-at/libzip/commit/043ceac7ac5dc67eb8f257195cd9adf8f0cedb19

Please do not send pings. Thanks.
