### ISSUE TITLE
zip_close is slow

### ISSUE THREAD

**Issue by lcxywfe** [nih-at/libzip#208]
**Describe the Bug**
I'm using libzip to compress some files, the zip package is about 5.5MB after compression, but the ```zip_close``` costs about 3000ms, is it normal? And is there any way to speed it up?

**Comment by dillof** [comment]
zip_close() is where all the compression and writing to disk happens, so it's expected to take some time.

**Comment by lcxywfe** [comment]
@dillof Thanks! I thought the compression is happened in ```zip_source_file```. By the way, Is it possible to speed up with multi-threading?

**Comment by lcxywfe** [comment]
I mean, compress parallelly and write sequentially?

**Comment by dillof** [comment]
And where should we put the potentially gigabytes of compressed data in the meantime?

**Comment by lcxywfe** [comment]
I set the compression level to 5, and the performance has improved at least 500% with a volume increase of less than 5%.
