### ISSUE TITLE
Disable tests when cross compiling

### ISSUE THREAD

**Issue by baruchsiach** [nih-at/libzip#21]
The unconditional run of tests breaks cross compilation:

```
/bin/sh: 1: ziptool: not found
regress/CMakeFiles/testinput.dir/build.make:59: recipe for target 'regress/CMakeFiles/testinput' failed
```

This is because the target binary can't run on the host. In this particular case, running ziptool manually produces:

```
/lib/ld-musl-armhf.so.1: No such file or directory
```

It would be best to disable the tests automatically when cross comping. If not, an option to disable test with `-DBUILD_TESTING=OFF` would help.

**Comment by 0-wiz-0** [comment]
Fixed in https://github.com/nih-at/libzip/commit/e9244b207c0fc883ff84c1fc46602feb1e2b0347. Thanks for the report!
