### ISSUE TITLE
avoid CMAKE_BINARY_DIR

### ISSUE THREAD

**Issue by malytomas** [nih-at/libzip#211]
These two lines:
https://github.com/nih-at/libzip/blob/e049c609ee4bc3def382cdfc701e0309292d1357/lib/CMakeLists.txt#L114
and
https://github.com/nih-at/libzip/blob/e049c609ee4bc3def382cdfc701e0309292d1357/lib/CMakeLists.txt#L228
are using CMAKE_BINARY_DIR, which pollutes super-project directory (a project that includes libzip via add_subdirectory).
Please use CMAKE_CURRENT_BINARY_DIR instead.

**Comment by 0-wiz-0** [comment]
Thanks, fixed.
