### ISSUE TITLE
Mangled file names (Mojibake) despite ZIP_FL_ENC_GUESS

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#212]
**Describe the Bug**

With some ZIP archives, the file name encoding is not detected and translated correctly, despite the use of `ZIP_FL_ENC_GUESS` with `zip_get_name` or `zip_stat_index`. This leads to "mangled" file names.

**Expected Behavior**

File names are correctly reported when using `ZIP_FL_ENC_GUESS`. 

With the [attached ZIP](https://github.com/nih-at/libzip/files/5258901/Archive.SJIS.zip), it should be:

```
新しいフォルダ
+-  SJIS_835C_ソ.txt
+-  新しいテキスト ドキュメント.txt
```

**Observed Behavior**

The file names are mangled and reported as:

```
ÉVé╡éóâtâHâïâ_
+-  SJIS_835C_â\.txt
+-  ÉVé╡éóâeâLâXâg âhâLâàâüâôâg.txt
```

**libzip Version**

4d7582db

**Operating System**

Linux version 5.7.10 (gcc version 9.3.0 (Debian 9.3.0-12), GNU ld (GNU Binutils for Debian) 2.34)

**Test Files**

[Archive SJIS.zip](https://github.com/nih-at/libzip/files/5258901/Archive.SJIS.zip)

**Comment by 0-wiz-0** [comment]
Yes, this is expected. Sorry if the documentation was not clear enough.

Only CP-437 and UTF-8 are specified by the zip specification. If you know that you are using a different encoding, you'll have to get the names with `ZIP_FL_ENC_RAW` and transcode them yourself.

The file names in your archive are in SJIS.

I added a sentence to the man pages to make that clearer.
