### ISSUE TITLE
Compression levels for zstd

### ISSUE THREAD

**Issue by krab** [nih-at/libzip#214]
zstd support compression up to 22 without using --ultra option https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L47

but currently libzip limited by 9? deflate limitations? https://github.com/nih-at/libzip/blob/master/lib/zip_set_file_compression.c#L43

**Comment by dillof** [comment]
Yes, this limit comes from deflate. We haven't gotten around to implementing method-specific flags/levels.

**Comment by DanielG1010** [comment]
Hi, have you been able to implement further compression levels for zstd? I was doing some tests selecting zstd as compression method with `ZIP_CM_ZST` as mentioned [here](https://libzip.org/documentation/zip_set_file_compression.html#ZIP_CM_ZSTD), but there is no difference in the compressed ratio obtained compare to default or deflate methods.

**Comment by DanielG1010** [comment]
Thank you for your response @dillof I was able to replicate your results with ziptool, I went again to test my C++ code, and I was able to see some difference now I think it might have been a problem in the compilation, not really sure. Thanks!
