### ISSUE TITLE
Cannot open CRX file

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#215]
**Describe the Bug**

`libzip` does not accept CRX files.

**Expected Behavior**

`libzip` opens a CRX file as a valid ZIP file.

A CRX file is a ZIP file with a custom prefixed header, and the ZIP format is robust against noise prefix.

Note that the command-line program `unzip` handles CRX files correctly (with a warning).

```
$ unzip -l elckoikggmpkacmbmpbgdepginigahjalive_main.crx
Archive:  elckoikggmpkacmbmpbgdepginigahjalive_main.crx
warning [elckoikggmpkacmbmpbgdepginigahjalive_main.crx]:  566 extra bytes at beginning or within zipfile
  (attempting to process anyway)
  Length      Date    Time    Name
---------  ---------- -----   ----
      625  2014-01-21 13:34   analytics.js
     ...
     2880  2014-01-21 13:34   Storage.js
---------                     -------
   723535                     27 files
```

**Observed Behavior**

When trying to open a CRX file, [`zip_open`](https://libzip.org/documentation/zip_open.html) fails with error `ZIP_ER_NOZIP` (Not a zip archive).

**libzip Version**

4d7582db

**Operating System**

Linux version 5.7.17

**Test Files**

https://clients2.googleusercontent.com/crx/blobs/QgAAAC6zw0qH2DJtnXe8Z7rUJP1TKQxtsDMfW2kdoGLbNHz7ckn8HvAlDj7felWRqNXJCbNdtxNNXTHZnowLQ3TM_C8nI9lXmXxvJhMhmHIlE8SnAMZSmuXL3u-_339TTOQYIDOfcI8itb-N3A/elckoikggmpkacmbmpbgdepginigahjalive_main.crx

**Comment by 0-wiz-0** [comment]
I don't know what tool created this, but the bug report belongs there.

A zip archive can have random data at the start, but the internal data structures contain data fields that specify *absolute* offsets. This CRX file has incorrect data there.

You can check this easily by just removing the first 566 bytes. After that, the ZIP archive is correct.

One particular example: The central directory entry for the first file, `analytics.js`, specifies that the local data starts at offset 0. That is not correct, it starts at byte 566 (after the extra data).

This kind of problem affects all entries.

**Comment by fdegros** [comment]
I'm coming back to it, since being able to handle CRX files might turn out to be an important use case in our application.

A CRX file is essentially a ZIP archive with some extra data prepended to it. How could we get `libzip` to "ignore" this prepended data and process a CRX file as an ordinary ZIP archive? My guess is that it requires two separate phases:

1. Determine the length of the prepended data to ignore
2. Apply this length as an offset when reading bytes from the archive

With your knowledge of the ZIP format, how difficult do you think each phase would be?

**Comment by dillof** [comment]
What are these CRX files and where are they used? Since they are not valid zip archives, I don’t see libzip supporting them.

However, you can do both of these tasks yourself: Open the file with `zip_source_file_create()`, read data until you find the local directory signature `"PK\3\4` that starts the actual zip archive, use `zip_source_window_create()` to create a source that only contains the zip archive, and use `zip_open_from_source()` to open the archive. You won't be able to modify the archive, though.

**Comment by fdegros** [comment]
> What are these CRX files and where are they used?

A CRX file is a Chrome Extension bundle.

**Comment by fdegros** [comment]
This is worth reconsidering. The underlying feature request is broader than that one `CRX` and is a legitimate, well-established use case.

The ZIP format's End-Of-Central-Directory is located by scanning backward from the end of the file, which is precisely what makes prepending arbitrary data possible in the first place. Self-extracting archives are literally built this way (a stub program + an unmodified ZIP appended verbatim), and Chrome's CRX3 format does the same thing (a signed header + a normal ZIP). Both are common, valid files people reasonably expect to open, not corrupted archives.

`unzip` and `libarchive` already handle this transparently today (the former with a warning, the latter silently). They compute where the central directory actually is from the EOCD position and size, and treat any discrepancy with the declared offset as a constant shift from prepended data.

I opened #582 implementing the same approach for `libzip`. It's a fallback only: every EOCD candidate is tried strictly first, so this can't cause a valid archive containing a decoy central directory (e.g. in its comment) to be misread. It's been tested against a real Chrome Web Store CRX (all 73 files extract with matching CRC) and a real self-extracting archive, including round-tripping through [`mount-zip`](https://github.com/fdegros/zipmount) built unmodified against it.
