### ISSUE TITLE
Making zlib optional

### ISSUE THREAD

**Issue by leezu** [nih-at/libzip#217]
zlib is required for DEFLATE compression. However, libzip can also be useful to read / write uncompressed zip files.
For these use-cases, it would be helpful to make zlib an optional dependency.

**Comment by 0-wiz-0** [comment]
That's a very limited use-case...

Do you actually use this? For what?

Do you have a patch?

**Comment by leezu** [comment]
https://numpy.org/doc/stable/reference/generated/numpy.savez.html uses this format. I wrote some numpy.savez compatible C++ code based on libzip. Having the (unused) zlib dependency adds some trouble for Windows users as zlib isn't available there by default.

**Comment by 0-wiz-0** [comment]
Interesting.
zlib is not only used for deflate support but also for CRCs (which are also needed for uncompressed files), so I don't think we'll make it optional.
libzip is part of vcpkg (a packaging system for Windows) - I hope this helps you.
https://github.com/microsoft/vcpkg/tree/d961529d7ffd822390b229dbd8ad29a94630dda0/ports/libzip
