### ISSUE TITLE
SONAME/ABI and library versioning policy

### ISSUE THREAD

**Issue by traversaro** [nih-at/libzip#218]
**Description**
Hi @0-wiz-0 and all libzip authors, thanks a lot for the amazing library. I was wondering if do you have any policy on versiong w.r.t. to  bumping the `SONAME`, i.e. breaking the ABI. In the sense, do you expect to bump the major version of the library the next time you will bump the  `SONAME`, or the `SONAME` and the library version are indipendent? 

**Solution**
Reply to this issue explaining if there is a relation between the `SONAME` and the library version, of if there is no such relation. Adding this info in the README could also help other packagers. 

**Describe alternatives you've considered**
The alternative is not to clarify this aspect. 

**Additional context**
The question came out in https://github.com/conda-forge/libzip-feedstock/pull/21 .

**Comment by 0-wiz-0** [comment]
We try to follow best practices: when adding symbols, we bump the shared library minor version, and when removing symbols (or changing the API for a function, which we haven't done yet) we bump the major version.
There is no promise on the version number of the distfile (which I think is what you are asking) but I expect at least the "Y", perhaps the "X", in X.Y.Z to change whenever we change the shared library major version number.

**Comment by traversaro** [comment]
Perfect, thanks!
