### ISSUE TITLE
invalid compile mark variable used

### ISSUE THREAD

**Issue by irov** [nih-at/libzip#22]
commit 39fa68134c52f1f12041f24b92af8b1df74a23df

static int dummy __attribute__((used)); 
invalid compile (MSVC15)
libzip\lib\zip_algorithm_bzip2.c(273): error C2061: syntax error: identifier '__attribute__'

**Comment by 0-wiz-0** [comment]
Fixed in https://github.com/nih-at/libzip/commit/84072ae6cc50aa36c00ebb9493e4bb9a45a8bf63, thanks!
