### ISSUE TITLE
Support for string/in-memory data

### ISSUE THREAD

**Issue by mvorisek** [nih-at/libzip#220]
**Description**
Currently, it seems string/ (in-memory data in general) is no supported.

Usecase https://bugs.php.net/bug.php?id=80372

**Solution**
Provide at some solution for RO operations.

**Describe alternatives you've considered**
Create virtual file handle https://stackoverflow.com/questions/11381694/using-a-c-string-like-a-file but it is not cross platform.

**Comment by dillof** [comment]
This is supported by using `zip_source_buffer_create` to create a source from the string, and then use `zip_open_from_source` to open the zip archive contained in that buffer.

**Comment by mvorisek** [comment]
@dillof Thanks for quick reaction!
