### ISSUE TITLE
Xcode project for building libzip using custom libzip flags

### ISSUE THREAD

**Issue by JanX2** [nih-at/libzip#224]
I have written a script that will generate a reasonably clean custom Xcode project via the CMake build system. The script heavily patches the Xcode project file generated by CMake as it uses absolute paths and contains a lot oft cruft:

https://github.com/JanX2/libzip-xcode-custom

You may or may not want to link to this from "libzip/developer-xcode/README Xcode Project.md".

**Comment by dillof** [comment]
What are you trying to achieve with this script and the resulting Xcode project?

**Comment by JanX2** [comment]
It sets up a lipzip build with custom features/dependencies in an Xcode project. This way, you can use it as a dylib dependency in other code. For example, I use it in my [Objective-C wrapper for libzip](https://github.com/JanX2/JXZip).

**Comment by dillof** [comment]
Do you keep the created Xcode project around, or do you just use it to build the dylib? 

In the first case, this sounds like a maintenance nightmare.

In the second case, is there something functionally wrong with the Xcode project created by cmake? If not, and it's only used for building the dylib, why do you care what it looks like? If yes, a fix would be better suited in cmake, so we won't have to maintain it and other projects benefit as well.

**Comment by JanX2** [comment]
I keep the created Xcode project around in a separate git repository and I use it to build the dylib with custom features. 

If there are changes to libzip, the script regenerates the Xcode project. Should there be any breaking changes somewhere (cmake, lipzip), the script should be relatively easy to adapt.
