### ISSUE TITLE
zip_{fseek, ftell} error on uncompressed data

### ISSUE THREAD

**Issue by JustBeYou** [nih-at/libzip#228]
**Describe the Bug**
I'm trying to use `zip_ftell` to get the current position in a file I'm reading (opened with `zip_fopen`). It works fine if the file is under 4 KiB in size, but if it is above it fails with `Operation not supported`. 
It does not work even if I read the entire file.

**Expected Behavior**
Return the current offset in the file. 

**Observed Behavior**
Throws `Operation not supported`.

**To Reproduce**
Create an archive containing a large file (more than 4KiB) and run the following:

```c
#include <stdio.h>
#include <zip.h>

int main() {
    int err = 0;
    zip_t* zip = zip_open("archive.zip", 0, &err);
    zip_file_t* f = zip_fopen(zip, "test.txt", 0);

    // Calling ftell() will make fread() to fail
    // Comment the following line to make fread work, but ftell will still be broken
    printf("offset: %zd\n", zip_ftell(f));
    printf("error: %s | %s\n", zip_strerror(zip), zip_file_strerror(f));

    char buf[512] = {0};
    zip_int64_t bytes;
    while ((bytes = zip_fread(f, buf, 511) > 0)) {
        //printf("Read %zd %s\n", bytes, buf);
    }

    printf("offset: %zd\n", zip_ftell(f));
    printf("error: %s | %s\n", zip_strerror(zip), zip_file_strerror(f));

    zip_fclose(f);
    zip_close(zip);

    return 0;
}
```
Output
```
offset: -1
error: No error | Operation not supported
offset: -1
error: No error | Operation not supported
```

**libzip Version**
Latest, built from source. (from master)

**Operating System**
Fedora
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
```

**Test Files**
Test archive attached.
[archive.zip](https://github.com/nih-at/libzip/files/5750613/archive.zip)

**Comment by 0-wiz-0** [comment]
The testfile has compressed data.

**Comment by JustBeYou** [comment]
@0-wiz-0 ok, so how should `ftell` be used? As I said earlier, it does not work even after reading the entire file (I assume that reading it should also decompress it as I get the uncompressed data)

The documentation is not very clear about how it should be used.

**Comment by 0-wiz-0** [comment]
The documentation tries to explicit, but perhaps it can be improved. It currently says:
````
zip_ftell only works on uncompressed (stored) data. When called on compressed data it will return an error.
````
I.e. the data must be uncompressed in the zip archive. It can not be compressed data.
It doesn't matter what you do with the data with other `zip_*` functions.

**Comment by JustBeYou** [comment]
Oh, it makes sense now. I was thinking that it says `the data must be uncompressed first`. Thank you.

**Comment by 0-wiz-0** [comment]
Oh, I nearly forgot - in the next release, `zip_ftell` _will_ work on all kinds of sources.
However, `zip_fseek` still only works on uncompressed data.
