### ISSUE TITLE
regress/nonrandomopentest.c:44: undefined reference to `zip_random'

### ISSUE THREAD

**Issue by jschueller** [nih-at/libzip#23]
I think zip_random should be exported (marked with ZIP_EXTERN) to be used outside from the lib, ie in this test for example.

**Comment by 0-wiz-0** [comment]
The problem is: in general, we do not want to export the symbol. For testing, it seems it is needed (on Windows, I assume). But we do not have a separate library used for testing (which would somehow defeat the purpose of testing what we deliver anyway).
Do you have a suggestion?

**Comment by jschueller** [comment]
Maybe a solution is to export it, but without exposing it publicly in the zip.h header.

**Comment by 0-wiz-0** [comment]
I've marked the symbol with ZIP_EXTERN.

**Comment by lvivtotoro** [comment]
This issue doesn't seem to be fixed for me, I get `undefined reference to 'zip_random'` if I built it myself (which I have to, as Arch doesn't have lib32-libzip.

**Comment by 0-wiz-0** [comment]
You are affected by issue #106. Please try the last release, or a git snapshot from two weeks ago.
