### ISSUE TITLE
How to read binary data from a zip

### ISSUE THREAD

**Issue by bw98** [nih-at/libzip#233]
**Description**
I want to get an image data from a zip file, and I have tried to use `zip_fread` to read the data, but The data obtained is incomplete. What I get is only few bytes in the begin of image file.

Hence I was wondering which function in libzip should I call in order to get the image data? I looked through the documentation, but unfortunately I didn’t find the function I wanted.

My code is as follows:
```
    zip_file* file = zip_fopen(m_zip, cur_filename.c_str(), ZIP_RDONLY);
    char* content = new char[filesize + 1000];
    const zip_int64_t did_read = zip_fread(file, content, filesize);  // strlen(content) here is much smaller than the actual bytes of the image file
```

**Solution**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by 0-wiz-0** [comment]
Please provide more information about the problem.

**Comment by bw98** [comment]
My question is basically the same as this question ["Get files (other than text) from .zip with libzip"](https://stackoverflow.com/questions/9140194/libzip-read-file-contents-from-zip?rq=1) from StackOverflow.

**Comment by 0-wiz-0** [comment]
The question is answered in the stackoverflow post.
The interface is modelled after the standard C fopen/fread/fclose interface.
An example implementation of reading a file is in the `ziptool` code:
https://github.com/nih-at/libzip/blob/master/src/ziptool.c#L170
