### ISSUE TITLE
Fail to read image data with .jb2 file extension

### ISSUE THREAD

**Issue by bw98** [nih-at/libzip#236]
I want to use libzip to get the image data with the file extension `.jb2` in the zip compressed package.
If the parameter `flags` of `zip_fopen()` is not set to `ZIP_FL_COMPRESSED`, the data of the image file cannot be obtained through `fread()` (the error message is: `Zlib error: data error`).
However, the data read after using `ZIP_FL_COMPRESSED` is compressed, not the original data. How can I read the original data about this kind of file?

**Comment by bw98** [comment]
I can read this xxx.jb2 image file through ifstream and stringstream in c++, The image data Base64 format is such that (do not know what the upload file, sorry):`l0pCMg0KGgoBAAAAAQAAAAAwAAEAAAATAAAAZAAAAGQAAAAAAAAAAAEAAAAAAAEmAAEAAAE2AAAAZAAAAGQAAAAAAAAAAAAIA//9/wL+/v4EKO5Q8aznG7tfle0QBLV3axn5X6BjJPKMlJRMgk7UM0XVbCFph0pA3OkWEZDucACoRkLgRz0wOZBWynQuw8t6fD1mDlQWhwq40+kpSVNas4FI0l00AaNaL
fELTQVZDxXrdIAHNbg2EEV6lu1V87qK/1sULkm1n2of6nBEnfekpb3z8AmOI3i9/yBL/bF/h7mubWhs28mlJuPFZc/PIzVGul29iiIqq0I6s1FV5bkL7LE3z+R/fTz8deVW+rYBTlCMko490Cn6ofKET1xnmjL49WvqeGk+iwfWoCE4fl7a7EzJ1hy7gE3yi5Ftjp8wQwaIQNJcx8Ad2hcGLlafr1ONM6
4mohh439HJPUEDbvliU0qsRpzhcZZbJn//rAAAAAIxAAEAAAAAAAAAAzMAAQAAAAA=
`

**Comment by dillof** [comment]
My first guess would be that the zip archive is defective. Can you try reading it with another zip program?

**Comment by bw98** [comment]
> My first guess would be that the zip archive is defective. Can you try reading it with another zip program?

The zip archive may not be defective as your guess, because I try to dozens of zip files which have images such as `.jb2`, `.jpg`(except from `.png`, which can be read successfully), the `zip_fread()` return -1 with error message 'zlib error: data error' for `.jb2`, `Invalid argument` for `.jpg`.
My pseudocode is as follows:

**Comment by dillof** [comment]
libzip doesn't care what file type it is, so if it succeeds for png but not for jpeg, then the error is either in the zip archives or your program. Without further information, it's hard to be more specific.

Things to try:

- run `unzip -t` on the zip files to see if they are in fact correct. (If the program that produced these archives has a bug, then all dozens of zip files would likely be defective).
- check the error code of zip_fopen(). If that fails, it returns NULL, and then zip_fread will return `Infalid argument`.
- include the filename in the error message and check that it is correct and does exist in the archive.
- post a small zip archive and a reduced but working version of your program so we can take a look at it.

**Comment by bw98** [comment]
I made a demo  to test whether libzip is enable to read picutre binary data and it works well, probably it can't work somewhere except from libzip, I'm still tracking it. Thus, this issue is good to be closed and I really thank you for answering my question.
