### ISSUE TITLE
How to cancel archiving in progress?

### ISSUE THREAD

**Issue by vadi2** [nih-at/libzip#237]
I'd like to run my zipping in a separate thread to provide a good user experience for large zips. However, `zip_close` doesn't offer much by the way of being able to cancel it while it is in progress. What is a good way to go about it?

**Comment by dillof** [comment]
You can use `zip_register_cancel_callback_with_state(callback, userdata)`. `callback` will be called with two arguments: The zip archive and `userdata`. If it returns 1, `zip_close()` will be cancelled.

I just noticed that there is no documentation for this function, but it's been in libzip since 1.7.0.

**Comment by vadi2** [comment]
It looks like the function takes 4 arguments, so I'm struggling a bit here. What're the other two arguments?

This is what I've got:

```cpp
        auto cancel_callback = [](void*) -> int { return !mExportingPackage; };
        zip_register_cancel_callback_with_state(archive, cancel_callback, nullptr);
        ze = zip_close(archive);
```

**Comment by dillof** [comment]
In your case, just use `nullptr` as the third and fourth arguments.

From zip_progress.c:

    void zip_register_cancel_callback_with_state(zip_t *za, zip_cancel_callback callback, void (*ud_free)(void *), void *ud);


`za` is the zip archive, `callback` is your callback function, `ud_free` is the function called to free `ud` once it's no longer needed, or `NULL` if you don't need to free `ud`. `ud` is the user data passed to your callback, or `NULL` if you don't need user data.

**Comment by vadi2** [comment]
Thanks, got it sorted. For anyone else reading this in the future, this is the code that works:

```cpp
        auto cancel_callback = [](zip*, void*) -> int { return !mExportingPackage; };
        zip_register_cancel_callback_with_state(archive, cancel_callback, nullptr, nullptr);
        ze = zip_close(archive);
```

`mExportingPackage` is a `inline static bool`.
