### ISSUE TITLE
Cannot open big ZIP (4+GB) on 32-bit device

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#239]
**Describe the Bug**

Libzip doesn't open big ZIPs (4+GB) on 32-bit devices.

**Expected Behavior**

Libzip should be able to handle big ZIPs, even on 32-bit devices.

**Observed Behavior**

`zip_open(fileName, ZIP_RDONLY, &err)` fails to open a big ZIP (4+GB) on an ARM-32 device.
The returned error is `ZIP_ER_READ` and the error message is:
*Read error: Value too large for defined data type*

Note that the same code (same libzip version, same ZIP file) works correctly on 64-bit devices. I checked on both AMD-64 and ARM-64.

Note that libzip can correctly handle big files (4+GB) compressed in a ZIP, even on 32-bit devices, as long as the compression is effective enough to keep the ZIP file itself under 4GB.

So, the issue seems to be about the ZIP file itself being over 4GB on a 32-bit device.

**libzip Version**

1.7.3

**Operating System**

Linux 4.4

**Comment by 0-wiz-0** [comment]
Have you read `INSTALL.md`?

````
If you are building on a 32-bit Linux system it might be necessary to define _FILE_OFFSET_BITS to 64. Your distro will need to provide a fts.h file that is new enough to support this, or the build will break in zipcmp.
````

**Comment by fdegros** [comment]
Thanks. No I didn't read `INSTALL.md`. (Well, now I have read it.)
I'm using the [Gentoo package](https://packages.gentoo.org/packages/dev-libs/libzip), and I can't see any reference to _FILE_OFFSET_BITS in it.

**Comment by fdegros** [comment]
I tried and found out that adding the line

```
  append-flags -D_FILE_OFFSET_BITS=64
```

at the beginning of `src_configure()` in Gentoo's file `libzip-1.7.3.ebuild` solves the issue.

So, I guess, it's more a Gentoo issue than a libzip issue.
