### ISSUE TITLE
Please provide a maintainance WORKING 1.3.3 release

### ISSUE THREAD

**Issue by SlySven** [nih-at/libzip#24]
I understand the desired to only have to maintain one build system for libzip but unfortunately this means that the last two releases in the 1.3 series (1.3.1 & 1.3.2) do not compile on mingw(64).

As a maintainer of a Qt project that provides support for building with the native qmake and a CMake alternative it is a non-starter to require the latter on Windows where the user, building from sources, wants to use the former.  Given that the patch in https://libzip.org/libzip-discuss/msg00790.html does fix the issue would it be possible to backport it to finish the 1.3 series with an official released version that will compile from sources for those cases where 1.4, and the CMake dependency, is not an option?

**Comment by 0-wiz-0** [comment]
Sorry, we're not going to maintain older release branches.
