### ISSUE TITLE
zstd support

### ISSUE THREAD

**Issue by timofey-retailnext** [nih-at/libzip#246]
**Compiler Error**
Linker error: ZSTD_minCLevel() and ZSTD_maxCLevel() not found

**libzip Version**
1.8.0

**Operating System and Compiler**
Ubuntu 18.04, platform provided zstd lib 1.3.3

Also, any flags passed to `cmake`.
		-DBUILD_SHARED_LIBS:BOOL=ON \
		-DBUILD_TOOLS=ON \
		-DBUILD_REGRESS=OFF \
		-DBUILD_EXAMPLES=OFF \
		-DBUILD_DOC=OFF \

**Additional context**
Missing zstd functions appeared in zstd 1.5.x while ubunutu 18.04 has 1.3.3 -> link errors
need to add zstd version requirement to CMakeLists.txt:
from: "find_package(Zstd)"
to:  "find_package(Zstd 1.5)"
this will automatically disable older and incompatible zstd lib versions

**Comment by remicollet** [comment]
> Missing zstd functions appeared in zstd 1.5.x

They are in 1.3.6

In ChangeLog

```
v1.3.6  (Oct 6, 2018)
...
api : minimum negative compression level is defined, and can be queried using ZSTD_minCLevel().
``` 

And ZSTD_maxCLevel was already there
