### ISSUE TITLE
WinZip encryption is not FIPS compliant

### ISSUE THREAD

**Issue by vmurashev** [nih-at/libzip#250]
If to link ```libzip``` with FIPS compliant OpenSSL,
it is not possible to use WinZip encryption method
There is a crash with the following report in STDERR:
```
.\crypto\aes\aes_misc.c(74): OpenSSL internal error, assertion failed: Low level API call to cipher AES forbidden in FIPS mode!
```
Root cause is that the function ```_zip_crypto_aes_encrypt_block``` defined as macros to recall ```AES_encrypt``` from OpenSSL
But ```AES_encrypt``` API is not FIPS compliant and should be avoided to be compatible with OpenSSL FIPS mode

**Comment by 0-wiz-0** [comment]
I don't know anything about OpenSSL's FIPS mode.
The code is in [lib/zip_crypto_openssl.c](https://github.com/nih-at/libzip/blob/master/lib/zip_crypto_openssl.c), but I think you found that already.

Feel free to come up with a patch, if it is even possible with openssl in FIPS mode; or use a different backend (like GnuTLS or mbed TLS or libreSSL or an OpenSSL installation without FIPS).

**Comment by vmurashev** [comment]
@0-wiz-0 patch #255 suggested, please take a look

**Comment by 0-wiz-0** [comment]
Thank you very much! I've just merged it.
