### ISSUE TITLE
Build shared and static library at the same time.

### ISSUE THREAD

**Issue by FH0** [nih-at/libzip#254]
To build static library `cmake -DBUILD_SHARED_LIBS=OFF .`
To build shared library `cmake -DBUILD_SHARED_LIBS=ON .`

Maybe building at the same time is a good way.

**Comment by 0-wiz-0** [comment]
Please make a case for it.
And please provide the patches for CMake build infrastructure.

**Comment by FH0** [comment]
I encountered this problem when compiling PHP.

I did not use this library directly. But PHP uses this library. I am not familiar with cmake. If the developers don't have time, forget it.
