### ISSUE TITLE
Linking to visual studio 2019. Unresolved external symbol

### ISSUE THREAD

**Issue by mihdim777** [nih-at/libzip#256]
Hello!

I don't understand what am I doing wrong with linking Libzip v1.8.0 to Visual Studio 2019.

I pulled from github libzip, zlib and openssl. I installed openssl and created env variable with `OPENSSL_ROOT_DIR`.

I installed libzip using vsbuild.cmd ( `libzip/vstudio/vsbuild.cmd` ) :

`cmake -DBUILD_SHARED_LIBS=OFF -DLIBZIP_DO_INSTALL=OFF ..`

I created a new folder in vs project and placed headers from `libzip/lib` and a folder for lib resulted from building libzip. `libzip/build/lib/release/zip.lib`

Now in VS I went to `Project Properties->C/C++ ->Additional Include Directories` and added the path to previously folder for headers. Also in `Linker->Additional Library Directories` and added the folder for .lib file.

And now I don't understand why I still get `unresolved external symbol zip_open referenced in function` . `LNK2019` and `LNK1120`.

Do you have any idea how I can resolve this?

Thank you!

**Comment by 0-wiz-0** [comment]
`zip_oepn` looks like a typo for `zip_open`.

**Comment by mihdim777** [comment]
No, I just typed wrong manually. There is no typo in code. Those are the 2 error that I get. I use crow server and on one route I want to unzip a file that I receive.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol zip_open referenced in function "public: __cdecl <lambda_8ae99868ea3d9c398af21634afc272bd>::operator()(struct crow::request const &,struct crow::response &)const " (??R<lambda_8ae99868ea3d9c398af21634afc272bd>@@QEBA@AEBUrequest@crow@@AEAUresponse@2@@Z)	Test	C:\Users\mih\source\repos\Test\Test\Test.obj	1	`

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	1 unresolved externals	Test  C:\Users\mih\source\repos\Test\Test\Test.obj	1	`

**Comment by 0-wiz-0** [comment]
Sorry, I can't help you with VSCode problems. This does not look specific to libzip.

**Comment by mihdim777** [comment]
It's visual studio 2019, not VSCode. It's linking problem, I don't understand what I am doing wrong.

**Comment by 0-wiz-0** [comment]
Sorry, I meant to say Visual Studio. I don't use Windows, so I can't help you here. I don't think this is a problem related to libzip, but how to use/setup Visual Studio, and you should look for help somewhere else.

**Comment by dillof** [comment]
Sorry, like Thomas said, we don't use Windows and can't help you debug compile/link problems on Windows. Also, we can't provide pre-built Windows binaries (since we don't use Windows).

**Comment by mihdim777** [comment]
Ok! Thank you ! If I will find the solution I will come back and maybe include Windows building and linking in repo.
