### ISSUE TITLE
VS 2015 compiler doesn't support __attribute__((used)) in zip_algorithm_bzip2.c

### ISSUE THREAD

**Issue by s850042002** [nih-at/libzip#26]
Haven't test in VS 2017

temporary workaround:
1. just remove __attribute__((userd))
2. jump back to 1.3.2

**Comment by 0-wiz-0** [comment]
Already fixed in https://github.com/nih-at/libzip/commit/84072ae6cc50aa36c00ebb9493e4bb9a45a8bf63
