### ISSUE TITLE
Make zip_fread documentation more explicit

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#260]
The documentation of [`zip_fread()`](https://libzip.org/documentation/zip_fread.html) could be more explicit.

The documentation stipulates that `zip_fread()` function reads at most `nbytes` bytes. But it doesn't explain which circumstances would result in a _short read_ where the function reads fewer than the requested number of bytes.

Obviously, there is a _short read_ when the end of the file is reached. But is it the only possible cause?

What happens when `zip_fread()` attempts to read some bytes after having reached the end of the file? My experiments show that it returns `0`, but this behaviour is not explicitly documented. Can we rely on it?

What happens when `zip_fread()` is called several times after having reached the end of the file? Does it consistently return `0`?

**Comment by dillof** [comment]
Assume any call to `zip_fread()` can result in a short read, even though most won't. It uses a variety of zip sources under the hood, some of which could be user supplied, so we can't be more specific than that.

After encountering end of file, any further call to `zip_fread()` will return 0. I'll make that more explicit in the documentation.

**Comment by fdegros** [comment]
Thanks.
