### ISSUE TITLE
zip_fread reports a CRC error at the end of an AES-encrypted file

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#261]
[Different Encryptions.zip](https://github.com/nih-at/libzip/files/7166836/Different.Encryptions.zip)
**Describe the Bug**

After reaching the end of an AES-encrypted file, `zip_fread()` returns `-1` and signals a _CRC error_.

Example:
```
Open 'Encrypted AES-256.txt'
zip_fread(file, buf, 4096) returned 32
zip_fread(file, buf, 4064) returned -1 (CRC error)
```

No such error occurs if the file is encrypted with ZipCrypto, or not encrypted at all:

```
Open 'Encrypted ZipCrypto.txt'
zip_fread(file, buf, 4096) returned 34
zip_fread(file, buf, 4062) returned 0
```

```
Open 'ClearText.txt'
zip_fread(file, buf, 4096) returned 23
zip_fread(file, buf, 4073) returned 0
```

Note that, in the ZIP archive, the AES-encrypted files seem to have a CRC-32 set to zero, which is not the case of ZipCrypto-encrypted or unencrypted files.

```
$ unzip -v 'Different Encryptions.zip' 
Archive:  Different Encryptions.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
      23  Stored       23   0% 2020-08-28 15:22 89dbe5e0  ClearText.txt
      32  Unk:099      40 -25% 2020-08-28 15:23 00000000  Encrypted AES-128.txt
      32  Unk:099      44 -38% 2020-08-28 15:23 00000000  Encrypted AES-192.txt
      32  Unk:099      48 -50% 2020-08-28 15:23 00000000  Encrypted AES-256.txt
      34  Stored       34   0% 2020-08-28 15:23 1e97241a  Encrypted ZipCrypto.txt
--------          -------  ---                            -------
     153              189 -24%                            5 files
```

**Expected Behavior**

No such _CRC error_ should occur.

**libzip Version**

1.7.3.1

**Operating System**

Linux version 5.10.46

**Comment by dillof** [comment]
How did you create this zip archive? 

Are you sure you used the correct password for decryption? A wrong password can often lead to CRC errors.

Can you unpack the archive with other zip utilities?

Can you provide the password used to encrypt the files so we can test it?

**Comment by fdegros** [comment]
I believe this archive is valid, as it can be unpacked by other ZIP utilities supporting AES encryption.

The password is `password`.

IIRC, this archive was created using `7z`.

**Comment by 0-wiz-0** [comment]
Winzip 9 and 10 did set the CRC to zero for AES encryption. Winzip 11+ does it for files that are "smaller than 20 bytes compressed" per its documentation.
This case is currently not supported. If you make bigger test files, you should get a CRC field that is non-zero and it will work with libzip.

**Comment by fdegros** [comment]
I created a bigger AES-encrypted ZIP, and its CRC is still zero.

```
$ 7z a -tzip -ppassword -mem=AES256 G\'Day.zip G\'day.png
  
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.utf8,Utf16=on,HugeFiles=on,64 bits,8 CPUs Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (806EA),AS
M,AES-NI)

Scanning the drive:
1 file, 56672 bytes (56 KiB)

Creating archive: G'Day.zip

Items to compress: 1


Files read from disk: 1
Archive size: 37479 bytes (37 KiB)
Everything is Ok

$ unzip -v G\'Day.zip
Archive:  G'Day.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
   56672  Unk:099   37293  34% 2021-09-01 17:59 00000000  G'day.png
--------          -------  ---                            -------
   56672            37293  34%                            1 file
```

So, I'm not sure I understand correctly. Is this archive valid or not? 

In any case, I would like to be able to process it without encountering a CRC error. At the moment, I have to explicitly ignore and discard this error. Or I have to be extra careful not to try reading any byte past the end of the file. But, IIUC, this also prevents me from detecting actually corrupted files, right?

**Comment by dillof** [comment]
"Valid" is a relative term when it comes to zip archives, but we agree that libzip should support this without error. We'll fix this, but I can't promise when.

**Comment by fdegros** [comment]
Understood. Let me know when you have a fix for it, even if it is not in an official release yet. If this fix is simple enough, I should be able to backport it to libzip 1.7.3.

**Comment by fdegros** [comment]
Thanks.

I confirm that the change 6cb3653 fixes the issue.
