### ISSUE TITLE
Retrieve offsets for entries

### ISSUE THREAD

**Issue by mikeucfl** [nih-at/libzip#262]
I have the need to retrieve the starting offsets for each entry in a zip, and saw the _zip_file_get_offset method. The values from za->entry[index].orig seem to be what I'm after (https://github.com/nih-at/libzip/blob/master/lib/zip_file_get_offset.c#L57). The only issue I'm having is if I delete and add the same file, the offsets don't seem to be correct unless I call zip_close and zip_open before reading them again. Is there another method I could take to sync this, or another route I could take to retrieve updated versions of the offsets? Thanks

**Comment by dillof** [comment]
If you modify the archive, the new offsets depend on the size of the compressed file data and metadata of the files up to this file, and therefore cannot be known before writing the archive back to disk.

These offsets are not reliable when you change the archive. Why do you need to know them, and what are you using them for?

Also, you should be aware that `_zip_file_get_offset()` is not part of the official API and might change or be removed without warning.

**Comment by mikeucfl** [comment]
Makes sense now why the values are not what I expect, do you happen to know of a way to get them there but not actually write to disk? I haven't dug down into the zip_close method to see what it does, so that may be my next path for me. Having to write to disk and load right now takes too much overhead. I have a requirement to provide these offsets for a customer's system. Thanks again for the answers.

**Comment by dillof** [comment]
Not easily, no. You could add a flag to zip_close to have it skip copying/writing data and just remember how much data would have been written. However, zip_close is one of the biggest and most complex parts of libzip, and we will not include this change in the official build, so you would have to maintain it yourself.

**Comment by mikeucfl** [comment]
got it, thanks for the information
