### ISSUE TITLE
Add new function to rewind or reset a zip_file_t

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#264]
It could be useful to have a function acting on a `zip_file_t*` that rewinds or resets the open file and puts it back into the same state as if it had been freshly opened by `zip_fopen_index`, but without changing the pointer to the underlying `zip_file_t`.

Something like:
```c++
// Rewinds the file.
//
// Precondition: file has been returned by zip_fopen() or zip_fopen_index().
// Precondition: file has not been closed by zip_fclose() yet.
//
// Postcondition: zip_ftell(file) returns 0
// Postcondition: the file error status is cleared
void zip_freset(zip_file_t *file);
```

At the moment, the workaround consists in closing (`zip_fclose`) and reopening (`zip_fopen_index`) the file. It has the inconvenience of potentially changing the `zip_file_t*`. It also means that we need to keep around the `zip_t* archive` and the `zip_uint64_t index` that we pass to `zip_fopen_index`. There is a simplification opportunity in having a function doing the same thing directly on a `zip_file_t*`.

**Comment by 0-wiz-0** [comment]
What's your use case?

**Comment by fdegros** [comment]
The use case is about "jumping backwards" when reading a compressed file and the jump target is out of the buffer keeping the latest uncompressed data. We have to rewind the file, restart from the top and move forwards to the new position.
