### ISSUE TITLE
zip_source_zip_create and kin force re-encryption of encrypted but not compressed entries

### ISSUE THREAD

**Issue by drussel** [nih-at/libzip#265]
**Describe the Bug**
When trying to copy data between zip files that is encrypted by not compressed, the function ends up decompressing and recompressing the data even when we want the same output.

**Expected Behavior**
It is faster than re-encrypting the file.

**Observed Behavior**
It is slower.

**To Reproduce**
Create an archive with entries that are encrypted, but not compressed. Create a new file and a zip_source from the original file with encryption-only. I can provide code if that is useful, just don't have stand alone at the moment.

**libzip Version**
1.8.0

**Operating System**
Multiple.

**Test Files**

**Additional context**
There is a line (in zip_source_zip_new.c:64) adding compression to the source flags if encryption is turned on. Then the flags don't match on the target.

**Comment by 0-wiz-0** [comment]
If the encryption flags change, the data needs to be re-encrypted.
Make them match and the data will be copied.
I'm not sure what you'd like from libzip here.

**Comment by dillof** [comment]
Closing due to lack of feedback.
