### ISSUE TITLE
Removed conan option libzip:with_openssl

### ISSUE THREAD

**Issue by bjoernbahn** [nih-at/libzip#267]
**Describe the Bug**
I use Conan to get the libzip dependency. I updated my dependency from 1.5.2 to 1.7.0 and got the error message:

ERROR: libzip/1.8.0: option 'with_openssl' doesn't exist
Possible options are ['shared', 'fPIC', 'with_bzip2', 'with_lzma', 'with_zstd', 'crypto', 'tools']

**Expected Behavior**
The libzip:with_openssl option would still be usable, since the cmake option ENABLE_OPENSSL is still in the CMakeLists.txt.

**To Reproduce**
conanfile.txt
[requires]
libzip/1.8.0

[options]
libzip:with_openssl=False

**libzip Version**
1.8.0

**Operating System**
Windows 10 and Ubuntu 20.04

**Comment by 0-wiz-0** [comment]
We're an upstream for conan. For conan bug reports, please use conan's tracker.
https://github.com/conan-io/conan/issues
