### ISSUE TITLE
Api description in document needs to be updated. 

### ISSUE THREAD

**Issue by PeiweiHu** [nih-at/libzip#269]
+ zip_source_rollback_write returns void. But its RETURN VALUE section in the document states it returns 0 or -1. 
+ zip_unchange_archive always returns 0. But its RETURN VALUE section in the document states it returns 0 or -1.

**Comment by dillof** [comment]
I've fixed the man page for `zip_source_rollback_write`. 

While `zip_unchange_archive` currently always returns 0, we reserve the right to change that later, if the need arises. The man page not only documents the current behaviour, it is also a promise for future changes.
