### ISSUE TITLE
zip_fseek and zip_ftell not working with encrypted (uncompressed) data

### ISSUE THREAD

**Issue by volanin** [nih-at/libzip#271]
I am using libzip 1.8.0 on linux.
I am creating the archive with the following code (error checking removed for simplicity).
This zips a single file, with uncompressed data and using AES256 encryption:

```
    zip_t* zip = zip_open( zipname, ZIP_CREATE | ZIP_TRUNCATE, NULL );

    zip_source_t* source = zip_source_file( zip, filename, 0, 0 );
    zip_int64_t index = zip_file_add( zip, basename( filename ), source, ZIP_FL_ENC_UTF_8 );

    zip_set_default_password( zip, password );
    zip_file_set_encryption( zip, index, ZIP_EM_AES_256, NULL );

    zip_set_file_compression( zip, index, ZIP_CM_STORE, 0 );  //  No compression.
    zip_close( zip );
```

After that, I am opening the archive and trying to **zip_fseek( )** and **zip_ftell( )**, but both return error.

```
    zip_t* zip = zip_open( zipname, ZIP_RDONLY, NULL );
    zip_set_default_password( zip, password );

    zip_fseek( zip, 10, SEEK_SET );  //  Returns -1
    zip_ftell( zip );  //  Returns -1
```

Without encryption, these functions work as described. Is this the expected behavior?
Nothing in the documentation talks about limitations with encrypted files.

EDIT:

I just tested zip_file_set_encryption( ) with ZIP_EM_TRAD_PKWARE and the functions started working as intended.
So I assume **zip_fseek( )** and **zip_ftell( )** will fail when using AES encryption.

**Comment by dillof** [comment]
Like compression, encryption only allows processing the data sequentially, so seeking is not supported.

**Comment by fdegros** [comment]
See also the similar feature request https://github.com/nih-at/libzip/issues/336.
