### ISSUE TITLE
Can't install with Luarocks, again

### ISSUE THREAD

**Issue by ogomez92** [nih-at/libzip#274]
**Expected Behavior**
Instal correctly... UIt's not  working on M1 macs  and luarocks.

**Observed Behavior**
A clear and concise description of what actually happened.

I tried to install libzip using homebrew, then install lua-zip using luarocks. It failed with an error.

**To Reproduce**
Short program or code snippet that reproduces the problem.
**Describe the Bug**
(base) uri@Mac-mini-de-oriol ~ % brew install libzip
Warning: libzip 1.8.0_1 is already installed and up-to-date.
To reinstall 1.8.0_1, run:
  brew reinstall libzip
(base) uri@Mac-mini-de-oriol ~ % luarocks install lua-zip
Installing https://luarocks.org/lua-zip-0.2-0.src.rock

Error: Could not find header file for ZIP
  No file zip.h in /usr/local/include
  No file zip.h in /usr/include
  No file zip.h in /include
You may have to install ZIP in your system and/or pass ZIP_DIR or ZIP_INCDIR to the luarocks command.
Example: luarocks install lua-zip ZIP_DIR=/usr/local

**libzip Version**
Version of libzip or revision repository used.
latest brew formula
**Operating System**
Operating system and version, used compiler.
Mac 12.1 Monterey beta on M1 mac Mini
**Test Files**
If applicable, attach and describe zip archives that trigger the problem.

**Additional context**

**Comment by 0-wiz-0** [comment]
Please report this bug to brew and/or luarocks. We do not maintain either of their formulas/recipes.

Some googling showed me that you can get the installation path of libzip in brew like this:
```
brew --prefix libzip
```
and then you can use that to set `ZIP_DIR`, as the lua-rocks error message tells you.
