### ISSUE TITLE
close zip is crash

### ISSUE THREAD

**Issue by wangsm123** [nih-at/libzip#276]
test: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)

**Comment by 0-wiz-0** [comment]
This is not enough information by a mile. The error message is not even from code in libzip.
Please provide more information if you want us to take a look at this.

**Comment by 0-wiz-0** [comment]
Feedback timeout.
