### ISSUE TITLE
zip_close failed, return "Renaming temporary file failed: Permission denied" on Windows 

### ISSUE THREAD

**Issue by dengchj** [nih-at/libzip#278]
**Describe the Bug**
I want to add a file to an exist zip file(a docx, it's actually a ZIP file). It works fine on Linux,  add files ok. But it gets an error on Windows when zip_close return `Renaming temporary file failed: Permission denied`
I have tried compiling libzip many times and in many ways, a nd tried VCPKG, but got the same wrong results.

**Expected Behavior**
Files can be closed normally and files can be added to the ZIP file normally.

**To Reproduce**
```C++
bool ZipAddFile(const std::string& zip_path, const char* buffer, const int size_buffer, const std::string& adding_file)
{
    int error = 0;
    zip_t *za = zip_open(zip_path.c_str(), ZIP_CHECKCONS, &error);
    if(za == nullptr)
    {
        zip_error_t ziperror;
        zip_error_init_with_code(&ziperror, error);
        LOG.Error("[{}] Open zip file: {} failed, {} ! [{}({})]", __FUNCTION__, zip_path.c_str(), zip_error_strerror(&ziperror), __FILE__, __LINE__);
    }
    LOG.Debug("[{}][{}], there is {} files in zip archive {}!", __FILE__, __LINE__, zip_get_num_files(za), zip_path.c_str());

    // load buff
    zip_source_t *zs = zip_source_buffer(za, buffer, size_buffer, 0);
    if(zip_file_add(za, adding_file.c_str(), zs, ZIP_FL_OVERWRITE|ZIP_FL_ENC_UTF_8) < 0)
    {
        LOG.Error("[{}] Add file {} to zip archive failed, {} ! [{}({})]", __FUNCTION__, adding_file.c_str(), zip_strerror(za), __FILE__, __LINE__);
        zip_source_free(zs);
        return false;
    }
    
    if(zip_close(za) != 0)
    {
      LOG.Error("[{}] Failed to close zip file {} [{}] ! [{}({})]", __FUNCTION__, zip_path.c_str(), zip_strerror(za), __FILE__,  __LINE__);
      return false;
    }

    return true;
}
```

**libzip Version**
libzip: v1.8.0
zlib: v1.2.11

**Operating System**
Windows 10，Visual Studio 2017

**Test Files**
a .docx file

**Comment by 0-wiz-0** [comment]
We're relying on users to work on the Windows support, since we're not using libzip on Windows ourselves.
Since noone else replied, you'll probably have to debug this yourself.
I suspect that some of your names are not valid with the file backend you're using. You could look at that first.

**Comment by dengchj** [comment]
@0-wiz-0 Thank you for your reply. I'm sorry , it's my mistake. The reason is that there are two open files on the same ZIP file at the same time, which is fine on Linux but blocked on Windows. Close the issue.
