### ISSUE TITLE
make test does not work with -DENABLE_ZSTD=OFF

### ISSUE THREAD

**Issue by cPanelBenjamin** [nih-at/libzip#283]
**Compiler Error**
The following tests FAILED:
         24 - clone-fs-add.test (Not Run)
         25 - clone-fs-delete.test (Not Run)
         26 - clone-fs-replace.test (Not Run)
        117 - set_compression_lzma_no_eos_to_store.test (Not Run)
        118 - set_compression_lzma_to_store.test (Not Run)
        121 - set_compression_store_to_lzma.test (Not Run)
        123 - set_compression_store_to_xz.test (Not Run)
        124 - set_compression_store_to_zstd.test (Not Run)
        126 - set_compression_xz_to_store.test (Not Run)
        127 - set_compression_zstd_to_store.test (Not Run)
Errors while running CTest
make: *** [test] Error 8

**libzip Version**
1.8.0

**Operating System and Compiler**
CloudLinux Server release 6.10 (Vladimir Lyakhov)
-- The C compiler identification is GNU 4.4.7
cmake3 version 3.6.1

Flags passed to `cmake`: -DENABLE_ZSTD=OFF

**Autodetected Configuration**
[CMakeCache.txt](https://github.com/nih-at/libzip/files/8042741/CMakeCache.txt)

**Additional context**
Expected behaviour: 
tests which are skipped should not be treated as failed

**Comment by 0-wiz-0** [comment]
libzip uses `SKIP_RETURN_CODE` for this, which is supported already in your old cmake version.
You'll have to debug yourself what goes wrong there.

**Comment by 0-wiz-0** [comment]
Just to be clear - check the tests if they really return exit code 77 or if there's a different problem there.
If they return 77 and it's just an issue with cmake/ctest, libzip is fine.

**Comment by cPanelBenjamin** [comment]
My mistake :) The tests do return exit code 77. Upgrading to CMake v3.9 fixed this for me.
