### ISSUE TITLE
Is there a way to check if there is corrupt file in zip package?

### ISSUE THREAD

**Issue by shawneeshaw** [nih-at/libzip#288]
Hi there,

I got a corrupt zip file created by libzip. There is one file in zip package was damaged or corrupt. It's hard to repeat how it could be happen.
Now, I have a request, Can I use a function to check all of files in zip are not corrupt before I open a zip file to avoid fatal error.
I used ZIP_CHECKCONS flag with zip_open, it can be open successfully.
Anybody can help? Thanks!

**Comment by shawneeshaw** [comment]
I'm using libzip 1.7.3 on Windows.

**Comment by dillof** [comment]
That is outside the scope of libzip. You can use libzip to check for corrupted files (open each, read it until the end and check for errors), but we won't provide a function that does all that, as it is very expensive and therefore of limited use.

Also, your program should probably handle a corrupted file more gracefully than treating it as a fatal error.

**Comment by shawneeshaw** [comment]
> That is outside the scope of libzip. You can use libzip to check for corrupted files (open each, read it until the end and check for errors), but we won't provide a function that does all that, as it is very expensive and therefore of limited use.
> 
> Also, your program should probably handle a corrupted file more gracefully than treating it as a fatal error.

Thanks for your answer.
I've used libzip function to write a checking function(go through all of file entries in zip). Thanks to libzip nice performance, it seems not to consume much time.
