### ISSUE TITLE
Race condition in zip_open_from_source

### ISSUE THREAD

**Issue by fniksic** [nih-at/libzip#289]
In case of concurrent executions of `zip_open_from_source` (and consequently `zip_open`), there are race conditions on the local static variables `needed_support_read` and `needed_support_write`, e.g. [here](https://github.com/nih-at/libzip/blob/1f8de598838a0688004f16f06aafceec53e7573a/lib/zip_open.c#L94-L95). Is it intended that opening zip archives is not thread-safe?

The documentation currently states:
> In general, different zip archives opened by libzip are independent of each other and can be used by parallel-running threads without locking.

It a bit unclear if this is supposed to cover _opening_ zip archives using `zip_open`/`zip_open_from_source`, or it only talks about archives _after_ they've been opened. So it seems to me that either `zip_open_from_source` should be made thread-safe, or the documentation should more explicitly state that opening the archives itself is not thread-safe.

**Comment by dillof** [comment]
This was not intended. I removed the static variables.
