### ISSUE TITLE
Include appveyor.yml in repository

### ISSUE THREAD

**Issue by janisozaur** [nih-at/libzip#29]
It looks like libzip has appveyor enabled, however appveyor.yaml file is nowhere to be found. I assume you have AppVeyor configured via WebUI, which prevents external contributors from setting their own instances to replicate your setup and prevents from improving this setup.

Please include appveyor.yaml as part of the repository.

**Comment by 0-wiz-0** [comment]
I never got appveyor to work. My work in progress file is in git. See https://github.com/nih-at/libzip/issues/27#issuecomment-365901664 for details. I'll be happy to accept a working appveyor file!

**Comment by 0-wiz-0** [comment]
Fixed by the latest pull request #32 . Thank you!
