### ISSUE TITLE
How to add new files to an existing ZIP file

### ISSUE THREAD

**Issue by vikirj** [nih-at/libzip#290]
Hi

I have using libzip v1.8.0 version .
I have a list of files and zip (i.e test.zip) that all files . and then add a new file to an existing zip file (i.e test.zip ) 
how to add new files to an existing ZIP file.

	`void ZIP_Files(std::vector<std::string> & file_list)
	{
		int error;
		std::string zipFileName = "/home/centos/zipfiles/test.zip";
		zip_t *zipper = zip_open(zipFileName.c_str(), ZIP_CREATE | ZIP_EXCL, &error);
		for (auto itr : file_list)
		{
			std::string file_path = itr.c_str();
			if (fs::exists(file_path))
			{
				boost::filesystem::path path(file_path);
				std::string file_name = path.filename().string();
					zip_source_t *source = zip_source_file(zipper, file_path.c_str(), 0, 0);
				bool status = source != nullptr && zip_file_add(zipper, file_name.c_str(), source, ZIP_FL_ENC_UTF_8) < 0; // also tried ZIP_FL_OVERWRITE instead of ZIP_FL_ENC_UTF_8 and ZIP_FL_ENC_UTF_8 | ZIP_FL_OVERWRITE
				if (status)
					zip_source_free(source);
				// i have tried this too
				zip_source_t *source;
				if ((source = zip_source_buffer(zipper, file_list.data(), file_list.size(), 0)) == nullptr ||
					zip_file_add(zipper, file_name.c_str(), source, ZIP_FL_ENC_UTF_8 | ZIP_FL_OVERWRITE) < 0)
				{
					zip_source_free(source);
				}
			}
		}
                zip_close(zipper);
	}`
	
	in this `ZIP_Files` function 1st we get 5 files 
	and second time we get more than 5 files

**Comment by narandiran** [comment]
use ZIP_TURNCATE flag 
        zip_open(zipfilename.c_str(),ZIP_TRUNCATE,&error);
