### ISSUE TITLE
Support pre compressed files

### ISSUE THREAD

**Issue by arsnyder16** [nih-at/libzip#292]
**Description**

In some cases it would be useful to support pre compressed files being added to zip without compressing again, but at the same time allow the decompression to still work on open. The reverse already is possible in libzip, if i want to extract the compressed data directly i can use something like `zip_fopen_index(zip_, index_, ZIP_FL_COMPRESSED)`

**Solution**
One option would be to leverage the compression flags of on zip_set_file_compression.  
`zip_set_file_compression(zip_, index,  ZIP_CM_STORE, ZIP_CM_DEFLATE);`
For example i have a pre deflated file that i want to just store, but i want to make sure the index reports that the content is deflated when opening. 

**Describe alternatives you've considered**
I looked through the code to see if there were any existing hooks and found nothing that stood out.

**Additional context**

**Comment by arsnyder16** [comment]
Found a way to make this work but requires creating a custom `zip_source_callback` which 

For example

**Comment by arcanis** [comment]
I'm looking at implementing Zip support in Node.js via the libzip, and I think this capability would be a requirement (Node.js already has APIs for compressing files, so the idea would be to let the user provide pre-compressed buffers rather than duplicate this logic).

**Comment by dillof** [comment]
We have made the API for layered sources public, which allows to add precompressed data, see [examples/add-compressed-data.c](../blob/main/examples/add-compressed-data.c)

If you have questions or suggestions regarding the API, please contact us. If any issues with the API are found, we can still fix them before the next release, after which the API is official.

**Comment by arcanis** [comment]
Works perfectly, thanks!
