### ISSUE TITLE
Invalid ZIP file with zip_file_set_dostime() and PKWARE zip_file_set_encryption()

### ISSUE THREAD

**Issue by ralfjunker** [nih-at/libzip#293]
A combination of `zip_file_set_dostime()` and PKWARE ``zip_file_set_encryption()`` result in an invalid ZIP file.

Example code below is in PHP 8 or newer, the outcome in C is just the same.

```php
<?php

$zip = new ZipArchive();

if ($zip->open('test.zip', ZipArchive::CREATE) === TRUE) {
    $zip->addFromString('test.txt', 'file content goes here');
    /* setMtimeIndex() interferes with encryption and renders the file invalid. */
    $zip->setMtimeIndex(0, mktime(0,0,0,12,25,2019));
    $zip->setEncryptionIndex(0, ZipArchive::EM_TRAD_PKWARE, '1');
    $zip->close();
    echo "Ok\n";
} else {
    echo "KO\n";
}

/* Open & Extract. */
var_dump( $zip->open('test.zip') );
var_dump( $zip->setPassword('1') );
var_dump( $zip->getFromIndex(0)  );
var_dump( $zip->close()          );

?>
```

As shown, libzip fails to extract the encrypted file. 7-Zip reports a wrong password.

Reason is that the file's file time and the `zip_file_set_dostime()` time are mixed up during PKWARE encryption.

**Comment by dillof** [comment]
This is fixed now. We also catch the case where you change the mtime but don't re-encrypt the file.

Next time, please use C example code, so we don't have to back-translate the PHP function names.
