### ISSUE TITLE
zip_fdopen should not close fd_orig provided by the caller

### ISSUE THREAD

**Issue by hfuttyh** [nih-at/libzip#294]
**Describe the Bug**
zip_fdopen closed the fd_orig provided by the caller

**Expected Behavior**

**Observed Behavior**
fd_orig should be obtain by the caller，and should not being closed in zip_fdopen，it will caused fd bing double free

**To Reproduce**
Short program or code snippet that reproduces the problem.

**libzip Version**
1.8

**Operating System**
Operating system and version, used compiler.

**Test Files**
If applicable, attach and describe zip archives that trigger the problem.

**Additional context**

**Comment by 0-wiz-0** [comment]
This is documented this way:
```The fd argument may not be used any longer after calling zip_fdopen.``` -- see https://libzip.org/documentation/zip_fdopen.html -- not even `close()`d.
