### ISSUE TITLE
Unexpected CMake warnings

### ISSUE THREAD

**Issue by KivApple** [nih-at/libzip#295]
I got these warnings while I have disabled encryption and tests via BUILD_REGRESS=OFF, ENABLE_COMMONCRYPTO=OFF, ENABLE_GNUTLS=OFF, ENABLE_MBEDTLS=OFF, ENABLE_OPENSSL=OFF and ENABLE_WINDOWS_CRYPTO=OFF.
```
CMake Warning at lib/libzip/CMakeLists.txt:226 (message):
  -- neither Common Crypto, GnuTLS, mbed TLS, OpenSSL, nor Windows
  Cryptography found; AES support disabled
-- Could NOT find Perl (missing: PERL_EXECUTABLE) 
CMake Warning at lib/libzip/CMakeLists.txt:271 (message):
  -- perl not found, regression testing disabled
```
I think CMakeLists.txt should not attempt to search these libraries (and Perl) and produce any warning if these features were explicitly disabled.

**Comment by 0-wiz-0** [comment]
Do you have a patch?

**Comment by KivApple** [comment]
https://github.com/nih-at/libzip/pull/296

**Comment by dillof** [comment]
Thanks, merged.
