### ISSUE TITLE
is zip_file_is_seekable reliable ?

### ISSUE THREAD

**Issue by remicollet** [nih-at/libzip#297]
**Describe the Bug**
`zip_file_is_seekable` seems unreliable

**Expected Behavior**
`zip_file_is_seekable` return 0 when seek not doable

**Observed Behavior**
`zip_file_is_seekable` return 1 but `zip_fseek` fails

**To Reproduce**
Using https://github.com/pierrejoye/php_zip/blob/master/tests/test.zip

Using "bar" entry,  `zip_file_is_seekable` returns 1 and `zip_fseek` works
Using "entry1.txt" entry (compressed),  `zip_file_is_seekable` returns 1 but `zip_fseek` fails

**libzip Version**
1.9.0

**Operating System**
Fedora 35

**Additional information**
`zip_file_is_seekable` is missing in documentation and test coverage

**Comment by remicollet** [comment]
FYI WIP in the PHP extension where I discover this problem
https://github.com/pierrejoye/php_zip/commits/feature_stream_seek

**Comment by remicollet** [comment]
Minimal test:

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <zip.h>

#define ARCHIVE "test.zip"

int main(int argc, char *argv[]) {
	zip_t *z;
	zip_file_t *f;
	int i, err = 0;
	struct zip_stat s;

	z = zip_open(ARCHIVE, ZIP_RDONLY, &err);
	if (err || !z) exit(1);
	printf("Open Archive %s\n", ARCHIVE);
	for(i=0 ; f = zip_fopen_index(z, i, 0) ; i++) {
		zip_stat_index(z, i, 0, &s);
		printf(" Open File %d: %s (compress=%d)\n", i, s.name, s.comp_method);
		
		printf("  is_seekable: %d\n", zip_file_is_seekable(f));
		if (s.name[strlen(s.name)-1] == '/')  // directory
			printf("  directory\n");
		else
			printf("  fseek:       %d\n", zip_fseek(f, SEEK_SET, 0));
		zip_fclose(f);
	}
	zip_close(z);
	return 0;
}
```

Using https://github.com/pierrejoye/php_zip/raw/master/tests/test.zip

Output:
```
Open Archive phptest.zip
 Open File 0: bar (compress=0)
  is_seekable: 1
  fseek:       0
 Open File 1: foobar/ (compress=0)
  is_seekable: 1
  directory
 Open File 2: foobar/baz (compress=8)
  is_seekable: 1
  fseek:       -1
 Open File 3: entry1.txt (compress=8)
  is_seekable: 1
  fseek:       -1

```

We can expect `zip_file_is_seekable` to return 0 for directory (#301) and compressed files.

**Comment by remicollet** [comment]
Thanks, I confirm the fix is OK

Do you plan a 1.9.1 bug release soon?

**Comment by dillof** [comment]
Just did 😉.

**Comment by remicollet** [comment]
> Just did wink.

Thanks!

**Comment by remicollet** [comment]
@dillof btw, 1.9.1 still have 1.9.0 :(
```
#define LIBZIP_VERSION "1.9.0"
#define LIBZIP_VERSION_MAJOR 1
#define LIBZIP_VERSION_MINOR 9
#define LIBZIP_VERSION_MICRO 0

```
