### ISSUE TITLE
Implement a getter for DOS time (`zip_file_get_dostime`)

### ISSUE THREAD

**Issue by KOLANICH** [nih-at/libzip#298]
**Description**
We have `zip_file_set_dostime`. But we don't have `zip_file_get_dostime`. I know it is kinda useless now, but theoretically it may be useful. 

**Solution**
Implement `zip_file_get_dostime`.

**Describe alternatives you've considered**
n/a.

**Comment by dillof** [comment]
`zip_file_set_dostime` will be deprecated in an upcoming release. To get the last modification time, use `zip_stat`.

**Comment by KOLANICH** [comment]
Do I get right, that to read/manipulate that old dos times (including intentionally creating inconsistent and malformed ones) we would have to use an another library?

**Comment by KOLANICH** [comment]
Thanks for the info. I guess this position should be explicitly documented that possibility of creating/analysing twisted archives is explicitly out of scope.

**Comment by dillof** [comment]
I would have thought the first design goal in https://libzip.org/documentation/libzip.html was quite clear:

The main design criteria for libzip were:
- Do not create corrupt files, even in case of errors.
