### ISSUE TITLE
How to create empty archive

### ISSUE THREAD

**Issue by remicollet** [nih-at/libzip#299]
From discussion on https://github.com/php/php-src/issues/8781

Simple code

```
#include <stdio.h>
#include <stdlib.h>
#include <zip.h>

int main(int argc, char *argv[]) {
	zip_t *z;
	int err = 0;
	z = zip_open("empty.zip", ZIP_CREATE, &err);
	if (z && !err) printf("OK\n");
	zip_close(z);
	return 0;
}
```

runs OK but no file created.

And if a file exists, and ZIP_TRUNCATE is used, the file is deleted, which seems unexpected.

**Comment by 0-wiz-0** [comment]
Yes, libzip does not create empty archives.

What do you think is expected behaviour for `ZIP_TRUNCATE`?

**Comment by remicollet** [comment]
@0-wiz-0 to be honest, I don't really care, just about a user report (see link in 1st comment)

At least documention (for close method) may help.

**Comment by 0-wiz-0** [comment]
You mean, like this?
https://github.com/nih-at/libzip/blob/48695e84d566d87f36fb1328bb1880a4e9d8c1df/man/zip_close.mdoc#L50

(already there...)

Ok, I think we'll leave this behaviour as-is, until someone can explain why it would be better to keep them.  :)

**Comment by cmb69** [comment]
If I have a directory containing some files, and I delete these files, the directory is not deleted. If I have a ZIP archive containing some entries, and I delete these entries, the archive is deleted. I find that very much confusing.

**Comment by arcanis** [comment]
> Ok, I think we'll leave this behaviour as-is, until someone can explain why it would be better to keep them. :)

Imo, while I can understand part of the reasoning, I think this behaviour is quite unintuitive - I wouldn't expect it as the default one (I don't have another example in mind where an API that save a file may also delete it 🤔).
