### ISSUE TITLE
Deprecate `zip_f{read,write,seek,tell}`, expose the `zip_file.src` via a getter function and use `zip_source_*` API for it

### ISSUE THREAD

**Issue by KOLANICH** [nih-at/libzip#302]
**Description**
I'm writing bindings to this lib and having to implement 2 sets of APIs for the same thing feels unappealing.

**Solution**
* implement a getter for `zip_source` (src field) for a zippped file
* deprecate `zip_f*` API.

**Comment by dillof** [comment]
Please stop redesigning your API. We are quite happy with it the way it is.

Yes, there is some historical baggage we would do differently if we started from scratch, but maintaining compatibility with older versions of libzip is important to us, so we only replace APIs if they have serious shortcomings.

Also, we're careful with which information we expose in the public API, since once it's public, it is hard to change without breaking compatibility.

**Comment by KOLANICH** [comment]
>Yes, there is some historical baggage we would do differently if we started from scratch, but maintaining compatibility with older versions of libzip is important to us, so we only replace APIs if they have serious shortcomings.
>is not appealing to most of our users, as is having t o rewrite their programs using libzip.

Deprecating doesn't mean dropping.

>Also, we're careful with which information we expose in the public API, since once it's public, it is hard to change without breaking compatibility.

It is C. It can be possible to just document which functions can be used in which cases. So for the common subset it can be possible to create a generic wrapper and use it.

BTW, what is the difference between `zip_source_<something>_create` and `zip_source_<something>`? Should I use only `..._create` API?

**Comment by dillof** [comment]
> > Yes, there is some historical baggage we would do differently if we started from scratch, but maintaining compatibility with older versions of libzip is important to us, so we only replace APIs if they have serious shortcomings.
> > is not appealing to most of our users, as is having t o rewrite their programs using libzip.
> 
> Deprecating doesn't mean dropping.

Deprecating means it might be dropped in the future; therefore, it should not be used in new code, and old code should be migrated away from it when time allows.

> 
> > Also, we're careful with which information we expose in the public API, since once it's public, it is hard to change without breaking compatibility.
> 
> It is C. It can be possible to just document which functions can be used in which cases. So for the common subset it can be possible to create a generic wrapper and use it.

Again, we are happy with the API we have.

You do not have to expose every function from libzip in your bindings, and you also don't have to map functions one to one. You can create the API you want and use our API to implement it.

If there is functionality that is missing from our API and there are legitimate, non-esoteric use cases for it, we will consider adding it.

But we will not fundamentally change our API for you.

> 
> BTW, what is the difference between `zip_source_<something>_create` and `zip_source_<something>`? Should I use only `..._create` API?

`zip_source_*` takes a `zip_t` as first argument, and uses that to report errors. So in the simple case where you create a source to add files to an archive, it is the easier method.

`zip_source_*_create` does not require a `zip_t`, instead it is passed a `zip_error_t` to report errors in. It is meant to be used in cases where you don't have a `zip_t`, like if you want to open a zip archive from a source, or if you use a source for other means.

**Comment by KOLANICH** [comment]
>Deprecating means it might be dropped in the future; therefore, it should not be used in new code, and old code should be migrated away from it when time allows.

Exactly.

>zip_source_* takes a zip_t as first argument, and uses that to report errors.
>zip_source_*_create does not require a zip_t, instead it is passed a zip_error_t to report errors in.

Yeah, I see it from the signature. So, no other state is mutated? I guess it should be safe to ignore the variant taking `zip_t`.
