### ISSUE TITLE
The example in `zip_file_add` man page advertises calling `zip_source_free`, while its man page says not to do it.

### ISSUE THREAD

**Issue by KOLANICH** [nih-at/libzip#303]
**Describe the Bug**
https://github.com/nih-at/libzip/blob/9c5347e130320547ab972cd7184097e3c80d44f4/man/zip_file_add.mdoc#L117-L121
https://github.com/nih-at/libzip/blob/9c5347e130320547ab972cd7184097e3c80d44f4/man/zip_source_free.mdoc#L57-L64

**Expected Behavior**
Consistent docs.

**Observed Behavior**
Inconsistent docs

**Comment by dillof** [comment]
Please read more carefully: `zip_source_free` should not be called after a **successful** call to `zip_file_add`. In the example code, it is called after an **unsuccessful** call.

**Comment by KOLANICH** [comment]
Oops, my bad. Should the indentation be changed to something like the following in order to highlight this?

```c
if (
    (s=zip_source_buffer(archive, buf, sizeof(buf), 0)) == NULL
||
    zip_file_add(archive, name, s, ZIP_FL_ENC_UTF_8) < 0
) { 
    ...
}
```
