### ISSUE TITLE
does libzip support Multi-disk ZIP?

### ISSUE THREAD

**Issue by Firestar-Reimu** [nih-at/libzip#307]
https://bugs.kde.org/show_bug.cgi?id=399949

for example, `sample.zip` and `sample.z01`.

**Comment by 0-wiz-0** [comment]
No, currently not.
I've never met multi-disk zips in the wild.

**Comment by Firestar-Reimu** [comment]
for example: https://github.com/manjaro-plasma/download/releases

the zip downloaded here has a z01 file

**Comment by fabiang** [comment]
Can't you simply do `cat manjaro-kde-22.12-development-unstable-221230-linux61.iso.zip manjaro-kde-22.12-development-unstable-221230-linux61.iso.z01 > manjaro-kde-22.12-development-unstable-221230-linux61-complete.iso.zip`?

**Comment by 0-wiz-0** [comment]
No, that's not possible - all the file offsets inside the zip structure (e.g. where to find the local headers and thus file data) are of the form <disk, offset> and if you cat them into one file, all will be wrong (except for the one for the first entry).

**Comment by fdegros** [comment]
> I've never met multi-disk zips in the wild.

To support this point, only 0.02% of all the ZIP archives opened by the ChromeOS Files App fail with `ZIP_ER_MULTIDISK` "Multi-disk zip archives not supported". So, multi-disk archives seem indeed quite rare.

**Comment by dillof** [comment]
The provided example files don't seem to be valid (the first file starts with a data descriptor, not with a local header). Since we won't implement multi-disk support and no one else seems to be willing to either, I'll close this issue.
