### ISSUE TITLE
The ZIP_TRUNCATE flag leads to memory leak

### ISSUE THREAD

**Issue by oleksii-kogutenko** [nih-at/libzip#31]
The simple test:

    const char* path = "some/path";
    int errorp = 0;
    zip_t *zip = zip_open(path, ZIP_CREATE | ZIP_TRUNCATE, &errorp);
    zip_close(zip);

leads to memory leak:
==12432== HEAP SUMMARY:
==12432==     in use at exit: 73,139 bytes in 6 blocks
==12432==   total heap usage: 826 allocs, 820 frees, 3,828,722 bytes allocated
==12432== 
==12432== 435 (128 direct, 307 indirect) bytes in 1 blocks are definitely lost in loss record 5 of 6
==12432==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12432==    by 0x43A871: _zip_new (zip_new.c:49)
==12432==    by 0x42E5EB: _zip_allocate_new (zip_open.c:526)
==12432==    by 0x42D632: zip_open_from_source (zip_open.c:130)
==12432==    by 0x42D41B: zip_open (zip_open.c:74)
==12432==    by 0x41CEC7: Zip_MemoryLeak::test_method() (zip_tests.cpp:122)
==12432==    by 0x41CE99: Zip_MemoryLeak_invoker() (zip_tests.cpp:118)

if the function **zip_open** are using without flag **ZIP_TRUNCATE**, there no memory leak ...

**Comment by 0-wiz-0** [comment]
Which version are you using, exactly?
We are currently unable to reproduce the issue.
Is this really everything your instrumented code does?

**Comment by oleksii-kogutenko** [comment]
I used sources [libzip-1.4.0](https://libzip.org/download/libzip-1.4.0.tar.gz) , downloaded from
