### ISSUE TITLE
libzip.pc incorrectly has `-lz` regardless of zlib filename

### ISSUE THREAD

**Issue by marktsuchida** [nih-at/libzip#311]
On Windows, zlib is usually named `zlib.lib` or `zlibd.lib` (for linking with the MSVC debug runtime). However, `libzip.pc` always lists `-lz` and therefore doesn't work for static linking.

**Expected Behavior**
`libzip.pc` should have the following lines:
```txt
Libs:  -L${libdir} -lzip
Libs.private:  -ladvapi32 -lbz2 -llzma -lzstd -lbcrypt -lzlib
```

**Observed Behavior**
`libzip.pc` has the following lines:
```txt
Libs:  -L${libdir} -lzip
Libs.private:  -ladvapi32 -lbz2 -llzma -lzstd -lbcrypt -lz
```

**To Reproduce**
With vcpkg having `zlib`, `bzip2`, `liblzma`, `zstd` (triplet: `x64-windows-static`) installed,
```cmd
mkdir build
cd build
cmake .. -DCMAKE_TOOLCHAIN_FILE=C:/path/to/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DBUILD_SHARED_LIBS=NO
```

The behavior is the same even if `VCPKG_TARGET_TRIPLET` and `BUILD_SHARED_LIBS` are not set.

Also, I observed the same problem when using a manually built zlib via `-DZLIB_LIBRARY=path/to/lib/zlib.lib -DZLIB_INCLUDE_DIR=path/to/include`.

**libzip Version**
`main` (`9dec8f0c7001cf0c4d4d5b4342b299a84580760f`)

**Operating System**
Windows 10, Visual Studio 2019, CMake 3.24.0-rc4

**Attempt at a Fix**
I tried to make a patch for this, and got it to work when the CMake generator is Ninja. I did this by parsing `${ZLIB_LIBRARIES}` with `get_filename_component()` and using the result instead of the hard-coded `-lz`.

However, this strategy doesn't work when the generator is Visual Studio, because in that case `ZLIB_LIBRARIES` contains the libraries for both debug and release (something like `optimized;C:/path/to/vcpkg/installed/x64-windows-static/lib/zlib.lib;debug;C:/path/to/vcpkg/installed/x64-windows-static/debug/lib/zlibd.lib`). It would appear that generating libzip.pc at configuration time is impossible to do correctly for multiple-configuration build tools. Personally I'd be okay with something that is only approximately correct for Visual Studio as long as Ninja (or Make) can generate the correct `.pc` for a single configuration, but I'm not enough of a CMake expert to know how to implement such a fallback.

**Comment by marktsuchida** [comment]
If you are wondering why one would need `pkg-config` on Windows: in my case I want to consume libzip in a project built with Meson.

**Comment by 0-wiz-0** [comment]
I've added a variable, `ZLIB_LINK_LIBRARY_NAME`, that you can set if the default of 'z' is not good for you.
If you know of an easy, correct way to guess if this needs to be set, let me know, otherwise this'll be the solution :)

**Comment by marktsuchida** [comment]
Thanks, this helps.
It turns out that `ZLIB_LIBRARIES` contains a multi-config list even when the generator is Ninja, when using vcpkg's zlib.
So the fix turned out to be a little more complicated that I'd like -- but I have created a PR.

**Comment by dillof** [comment]
Thanks, we merged your pull request.
