### ISSUE TITLE
cmake something wrong 编译出错 

### ISSUE THREAD

**Issue by honghuzhi** [nih-at/libzip#312]
**Compiler Error**
[ 85%] Built target man
[ 87%] Building C object src/CMakeFiles/ziptool.dir/ziptool.c.o
[ 87%] Linking C executable ziptool
../lib/libzip.so.5.5: undefined reference to `HMAC_CTX_new'
../lib/libzip.so.5.5: undefined reference to `HMAC_CTX_free'
collect2: error: ld returned 1 exit status
make[2]: *** [src/ziptool] Error 1
make[1]: *** [src/CMakeFiles/ziptool.dir/all] Error 2
make: *** [all] Error 2

**libzip Version**
1.9.2 and 1.5.2

**Operating System and Compiler**
The operating system and compiler used, including version number.

Also, any flags passed to `cmake`.

**Autodetected Configuration**
Attach `CmakeCache.txt` from your build directory. This list everything `cmake` detected on your system.

**Additional context**

**Comment by dillof** [comment]
Please provide detailed information about your build environment.

**Comment by honghuzhi** [comment]
centos 7.9
man compile openssl update 1.1.1p verison
but when I update the cmake compile install  to 3.21.4 version , happen some worong  break ，
then I compile with  cmake ./bootstrap -with-system-curl  can compile complete
then I compile libzip 1.5.2 version happen those errors

**Comment by dillof** [comment]
This sounds like a problem with your OpenSSL. According to the [OpenSSL documentation](https://www.openssl.org/docs/man1.1.1/man3/HMAC_CTX_new.html), `HMAC_CTX_new` was added in OpenSSL 1.1.0, so it should be available in your version.
