### ISSUE TITLE
Zip a file with a path size superior to MAX_PATH

### ISSUE THREAD

**Issue by F4r3n** [nih-at/libzip#314]
**Describe the Bug**
I can't zip a file with a path superior to the Windows path limit (260 characters).

**Expected Behavior**
I should be able to zip the file

**Observed Behavior**
*zip_source_file* returns NULL because it uses *GetFileAttributesExW* this function has a path size limit.
>> In the ANSI version of this function, the name is limited to MAX_PATH characters. To extend this limit to 32,767 wide characters, call the Unicode version of the function (GetFileAttributesExW), and prepend "\\?\" to the path. For more information, see [Naming a File](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file).

**libzip Version**
1.8.2

**Operating System**
Windows only

**Comment by 0-wiz-0** [comment]
We have no expertise on Windows. Do you have a patch suggestion?

**Comment by 0-wiz-0** [comment]
The win32w backend already uses the recommended workaround (`GetFileAttributesExW`) so I suggest you use that - i.e. `zip_source_win32w()` or `zip_source_win32w_create()`.
