### ISSUE TITLE
Android NDK Compile Error

### ISSUE THREAD

**Issue by ag2s20150909** [nih-at/libzip#318]
**Compiler Error**
Output from the compiler, including exact and complete error message, file name and line number.
```shell
-- Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
CMake Warning at CMakeLists.txt:186 (message):
  -- bzip2 library not found; bzip2 support disabled


-- Could NOT find LibLZMA (missing: LIBLZMA_LIBRARY LIBLZMA_INCLUDE_DIR LIBLZMA_HAS_AUTO_DECODER LIBLZMA_HAS_EASY_ENCODER LIBLZMA_HAS_LZMA_PRESET) (Required is at least version "5.2")
CMake Warning at CMakeLists.txt:195 (message):
  -- lzma library not found; lzma/xz support disabled


-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Could NOT find Zstd (missing: Zstd_LIBRARY Zstd_INCLUDE_DIR) (Required is at least version "1.3.6")
CMake Warning at CMakeLists.txt:204 (message):
  -- zstd library not found; zstandard support disabled


-- Found Perl: /usr/bin/perl (found version "5.30.0")
CMake Error at CMakeLists.txt:285 (file):
  file RELATIVE_PATH must be passed a full path to the directory:
  ../../install/arm64-v8a

CMake Error at CMakeLists.txt:287 (file):
  file RELATIVE_PATH must be passed a full path to the directory:
  ../../install/arm64-v8a


CMake Error at CMakeLists.txt:289 (file):
  file RELATIVE_PATH must be passed a full path to the directory:
  ../../install/arm64-v8a


-- Configuring incomplete, errors occurred!
See also "/home/ag2s/build/libzip-1.9.2/android/build/arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "/home/ag2s/build/libzip-1.9.2/android/build/arm64-v8a/CMakeFiles/CMakeError.log".
make: *** No rule to make target 'install'.  Stop.
```

**libzip Version**
Version of libzip or revision repository used.

- 1.9.2

**Operating System and Compiler**
The operating system and compiler used, including version number.

- Ubuntu 20.04 WSL 
- Android NDk android-ndk-r21e or android-ndk-r23b
- cmake version 3.22.2

Also, any flags passed to `cmake`.

no just run ```android/do.sh```

**Autodetected Configuration**
Attach `CmakeCache.txt` from your build directory. This list everything `cmake` detected on your system.

**Additional context**

**Comment by dillof** [comment]
Which arguments did you pass to `cmake`?

**Comment by dillof** [comment]
I see the problem: That file passes `-DCMAKE_INSTALL_PREFIX:PATH=../../${INSTALL_DIR}/${ANDROID_TARGET_PLATFORM}` to `cmake`, but that must be an absolute path.

Try replacing that with `-DCMAKE_INSTALL_PREFIX:PATH=$(pwd)/../../${INSTALL_DIR}/${ANDROID_TARGET_PLATFORM}` 

We don't use Android, so we can't properly maintain this script, but we'll gladly incorporate fixes. We'll add a note to that effect to the README file.
