### ISSUE TITLE
Docs refer to non-existent function zip_file_extra_field_by_id

### ISSUE THREAD

**Issue by edolstra** [nih-at/libzip#323]
**Describe the Bug**

The docs have several references to a non-existent function `zip_file_extra_field_by_id`:

```
$ git grep zip_file_extra_field_by_id
man/libzip.html:  <li><a class="Xr" href="zip_file_extra_field_by_id.html">zip_file_extra_field_by_id(3)</a></li>
man/libzip.man:zip_file_extra_field_by_id(3)
man/libzip.mdoc:.Xr zip_file_extra_field_by_id 3
```

I think this should be `zip_file_extra_field_get_by_id`.

**libzip Version**

Revision 8a5fbde12e9defe58313ed7fd54cd1959f3823d0

**Operating System**

N/A

**Test Files**

N/A

**Comment by 0-wiz-0** [comment]
Fixed, thanks!
