### ISSUE TITLE
libzip fails to set the compression or close the archive, 'Unkown error'

### ISSUE THREAD

**Issue by famastefano** [nih-at/libzip#325]
**Describe the Bug**
libzip fails to set the compression and/or close the archive.

**Expected Behavior**
I expect to being able to zip a binary (Windows crash dump) + text files (logs) and compress them.

**Observed Behavior**
libzip completes these operations successfully:
- zip_open
- zip_source_file_create
- zip_file_add
But fails when I try to use `zip_set_file_compression` or `zip_close` the archive
The error is `Can't open file: Unkown error`

**To Reproduce**
Sadly I didn't have time to reproduce the bug. I can provide the source code I've used.
```cpp
void createCrashZip(std::string_view zipname, std::string_view logdir, std::string_view dumppath, std::vector<std::string> const& logFiles)
{
    int         err{};
    zip_error_t srcerr{};
    zip_t      *ar = zip_open(zipname.data(), ZIP_CREATE | ZIP_TRUNCATE, &err);

    if(ar)
    {
        std::vector<zip_int64_t> arfiles; // list of file indexes to compress them later

        // Adds the crashdump
        if(!dumppath.empty())
        {
            zip_source *minidumpsrc = zip_source_file_create(dumppath.data(), 0, 0, &srcerr);
            if(!minidumpsrc)
                goto zip_creation_failure;

            zip_int64_t minidumpid = zip_file_add(ar, "crashdump.dmp", minidumpsrc, ZIP_FL_ENC_UTF_8);
            if(minidumpid == -1)
                goto zip_creation_failure;
            arfiles.emplace_back(minidumpid);
        }

        // Adds each log file
        for(auto const &file : logFiles)
        {
            zip_source *filesrc = zip_source_file_create(file.data(), 0, 0, &srcerr);
            if(!filesrc)
                goto zip_creation_failure;

            // 'file' is an absolute path, here we extract only the filename+extension
            std::string name    = file.substr(file.find_last_of('/') + 1);
            zip_int64_t fileid = zip_file_add(ar, name.data(), filesrc, ZIP_FL_ENC_UTF_8);
            if(fileid == -1)
                goto zip_creation_failure;
            arfiles.emplace_back(fileid);
        }

        // Fails
        for(zip_int64_t arfile : arfiles)
            if(zip_set_file_compression(ar, arfile, ZIP_CM_DEFLATE, 5) == -1)
                goto zip_ar_creation_failure;

        // If we comment the code above, this also fails
        if(zip_close(ar) == -1)
            goto zip_ar_creation_failure;
        return;
    }

zip_ar_creation_failure:
    MessageBoxA(NULL, zip_strerror(ar), "Error", MB_OK);
    goto zip_ar_discard;
zip_creation_failure:
    MessageBoxA(NULL, zip_error_strerror(&srcerr), "Error", MB_OK);
zip_ar_discard:
    zip_discard(ar);
}
```

**libzip Version**
1.9.2 through vcpkg:
```json
{
  "name": "libzip",
  "version>=": "1.9.2"
}
```

**Operating System**
- Windows 10 Pro x64 19044.1889
- C++17
- VS 2022 Pro
- MSVC 19.32.31332

**Test Files**
No .zip generated.
I can provide the crashdump my application generates if necessary. It's a file ~95MB big.
The logs are tiny (few KB).

**Additional context**
This is a Qt application.
My crash handler spawns a separate thread that:
1. Flush the logs
2. Generate a minidump (Win32 API)
3. Zip the minidump + the log files

**Comment by dillof** [comment]
`std::string_view::data()` does not guarantee the string to be NUL-terminated, so it can't be passed to libzip functions directly.

The files are opened by libzip when you call `zip_close()`, so that `zip_source_file_create()` succeeded does not mean the file can be opened.

Using `zip_source_file()` instead of `zip_source_file_create()` would be easier, since the error will be stored in `ar` and you can always use `zip_strerror(ar)` to get the error string.

Setting the compression algorithm is not required, libzip by default uses deflate (unless the file is less than 8k and would increase in size when compressed).

**Comment by famastefano** [comment]
Thanks a lot for the quick answer!
I've resolved the error, and as you can imagine the problem was me using the API wrong.
**libzip** couldn't open the crashdump because I forgot to close the handle, as Windows blocked any reading of the file.
