### ISSUE TITLE
How Windows decide whether to use Deflate or Deflate64 for zipping files

### ISSUE THREAD

**Issue by surajg101** [nih-at/libzip#327]
Windows Explorer uses the Deflate64 compression method for its zip files, rather than Deflate. Is this behaviour consistent across "current" Windows versions?

I tried one way. I created one zip file whose size is 2.69 GB, and one folder whose size is more than 1.23.

After zipping both of them, the zip file was created using Deflate64 and its size was 3.19 GB.

I would like to know how Windows decides whether to zip the file using Deflate64 or Deflate? What are the conditions required to create Deflate64 zip files?

**Comment by 0-wiz-0** [comment]
That's a good question, but we don't know either - libzip is (AFAIK) not used in Windows Explorer's zip handling.

**Comment by surajg101** [comment]
ok ,Thank you for replying
