### ISSUE TITLE
Add link for `zip_file_is_seekable` to https://libzip.org/documentation

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#328]
The function `zip_file_is_seekable` is described on the [`zip_fseek` page](https://libzip.org/documentation/zip_fseek.html). However, it is not mentioned on the [libzip index page](https://libzip.org/documentation/).

**Comment by dillof** [comment]
Thanks. There was a bug in the web site updating script that didn't handle linked pages correctly. We fixed the script and added the new page.
