### ISSUE TITLE
Determine if a file is seekable just by looking at its zip_stat struct

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#329]
The function `zip_file_is_seekable()` tells whether an open `zip_file_t` is seekable. I would like to determine if a file is seekable without having to open it first. More specifically, I would like to determine if a file is seekable just by looking at its `zip_stat` structure as returned by the function `zip_stat_index()`.

At the moment, I am using the following workaround:

```c++
  zip_stat_t st;
  if (zip_stat_index(..., &st) < 0)
    throw ZipError("Cannot stat file", ...);

  const bool seekable = (st.valid & ZIP_STAT_COMP_METHOD) != 0 &&
                        st.comp_method == ZIP_CM_STORE &&
                        (st.valid & ZIP_STAT_ENCRYPTION_METHOD) != 0 &&
                        st.encryption_method == ZIP_EM_NONE;
```

But this code duplicates some of the logic provided by `zip_file_is_seekable()`, at the risk of being inconsistent with what libzip can really do.

**Comment by dillof** [comment]
`zip_fopen()` decides which source layers are needed to read the data in the requested format. These source layers themselves use various criteria to check if they support seeking. So this code is distributed over various parts of libzip, and we would have to duplicate much of it to check if a file is seekable before opening it, which also runs the risk of getting inconsistent.

As such, we don't think this feature is worth the cost.
