### ISSUE TITLE
Windows compile failed because of localtime define

### ISSUE THREAD

**Issue by mkaes** [nih-at/libzip#330]
**Compiler Error**
cl.exe  /nologo -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS ... /DWIN32 /D_WINDOWS /W3 /MDd /Zi /Ob0 /Od /RTC1 /showIncludes /Folib\CMakeFiles\zip.dir\zip_add.c.obj /Fdlib\CMakeFiles\zip.dir\zip.pdb /FS -c D:\_dev\int\libzip\msvc16-amd64-debug-static\libzip\lib\zip_add.c
     [exec] C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\time.h(558): error C2059: syntax error: '('

**libzip Version**
Latest version from github

**Operating System and Compiler**
Windows, Visual Studio 2019

**Additional context**
The issue comes from 1e859f915587bf415eb1f43fc3035b2880c7f711.
After the define for localtime_s the windows header time.h is included.

**Comment by mkaes** [comment]
The header is from the WindowsSDK10.

The error occurs here
```
534:         #if __STDC_WANT_SECURE_LIB__
535:             _Check_return_wat_
536:             static __inline errno_t __CRTDECL ctime_s(
537:                 _Out_writes_(_SizeInBytes) _Post_readable_size_(26) char*         const _Buffer,
538:                 _In_range_(>=,26)                                   size_t        const _SizeInBytes,
539:                 _In_                                                time_t const* const _Time
540:                 )
541:             {
542:                 return _ctime64_s(_Buffer, _SizeInBytes, _Time);
543:             }
544: 
545:             _Check_return_wat_
546:             static __inline errno_t __CRTDECL gmtime_s(
547:                 _Out_ struct tm*    const _Tm,
548:                 _In_  time_t const* const _Time
549:                 )
550:             {
551:                 return _gmtime64_s(_Tm, _Time);
552:             }
553: 
554:             _Check_return_wat_
555:             static __inline errno_t __CRTDECL localtime_s(
556:                 _Out_ struct tm*    const _Tm,
557:                 _In_  time_t const* const _Time
558:                 )
559:             {
560:                 return _localtime64_s(_Tm, _Time);
561:             }
562:         #endif

```

**Comment by 0-wiz-0** [comment]
Fixed in https://github.com/nih-at/libzip/commit/15e724cf011f8773d0fa6ec36df9610ccd305b0f, thanks!
