### ISSUE TITLE
Getting error strings after zip_open()

### ISSUE THREAD

**Issue by stuser81** [nih-at/libzip#331]
After calling many functions, we can use `strerror` functions to get a friendly error string.

However what to do after zip_open()? All we have is an error in the form of an integer - we don't have any structure yet for use with the `stderror` functions. Although the error strings are documented at https://libzip.org/documentation/zip_open.html - how to get at them programmatically?

**Comment by dillof** [comment]
Here's how you do it:

```
    zip_t *za;
    int err;

    if ((za = zip_open(name,  0, &err)) == NULL) {
        zip_error_t error;
        zip_error_init_with_code(&error, err);
        fprintf(stderr, "%s: cannot open zip archive '%s': %s\n", progname, name, zip_error_strerror(&error));
        zip_error_fini(&error);
        return -1;
    }
```

We should add this example to the `zip_open()` man page.
