### ISSUE TITLE
When decompressing the encrypted zip file, some wrong passwords are passed through zip_set_default_password(), zip_fopen_index() function returns correct without error, and reads out the garbled code. This error password prompts that the file is damaged when decompressing with winrar, but actually the file is not damaged, just the password is wrong

### ISSUE THREAD

**Issue by huangbobonb** [nih-at/libzip#332]
When decompressing the encrypted zip file, some wrong passwords are passed through zip_set_default_password(), zip_fopen_index() function returns correct without error, and reads out the garbled code. This error password prompts that the file is damaged when decompressing with winrar, but actually the file is not damaged, just the password is wrong

**Comment by dillof** [comment]
This is a known limitation of the password verification in the zip file format. It can catch some wrong passwords, but not all.

**Comment by huangbobonb** [comment]
请问我在爆破的时候能有什么办法知道输入的密码错误吗

**Comment by huangbobonb** [comment]
Is there any way for me to know the wrong password when blasting

**Comment by dillof** [comment]
I'm sorry, what do you mean by "blasting"?
