### ISSUE TITLE
[add zip from zip stored] keep the new entry with its original stored compress method

### ISSUE THREAD

**Issue by hongjunwang** [nih-at/libzip#338]
**Description**
A lot of media files use STORED compress method in Android APK file, especially some games. when I use zipmerge to merge some apk files, libzip changed the files of which use STORED compress method to DEFLATE compress method. This behavior  cause two negative effects:
1) media files are excpeted to use STORED method. this lets the files be accessed directly via [mmap(2)], removing the need to copy this data in RAM and reducing your app's memory usage.
2) compress method changed cause recompress process that significantly increased unnecessary time-consuming。

**Solution**
when add file from zip, keep the new entry with its original compress method, and avoild unnecessary recompress operations to reduce the cost of merge zip.

**Comment by dillof** [comment]
We think compressing files is the correct default behaviour, but we understand your use case, so we made it an option: `zipmerge -k` keeps stored files uncompressed in the target zip archive.

**Comment by hongjunwang** [comment]
> We think compressing files is the correct default behaviour, but we understand your use case, so we made it an option: `zipmerge -k` keeps stored files uncompressed in the target zip archive.

I have tested this feature. It works fine. great!
