### ISSUE TITLE
Opening large zip files

### ISSUE THREAD

**Issue by TheoMcIntosh** [nih-at/libzip#339]
Unfortunately I have run into an issue where I am unable to use your superb library to open any zip files around 8gb in size or more.

I would greatly appreciate it if anyone could lead me towards a solution or add support for larger files.

Kind regards

**Comment by dylan1951** [comment]
Yes support for larger files would be amazing!

**Comment by 0-wiz-0** [comment]
libzip has support for files over 8GB, there's nothing to enhance.
What is the actual problem you are seeing?
If you are on Linux - some of them need(ed?) a special define, from `INSTALL.md`:
```
If you are building on a 32-bit Linux system it might be necessary
to define `_FILE_OFFSET_BITS` to `64`.
```

**Comment by dylan1951** [comment]
Never mind, we are stupid.
