### ISSUE TITLE
Zips generated by macOS Archive Utility fails consistency check

### ISSUE THREAD

**Issue by Luc45** [nih-at/libzip#341]
**Describe the Bug**
libzip cannot validate the consistency of Zip files generated by the Archive Utility from macOS.

```
ziptool -c hello-dolly.zip get_archive_comment
can't open zip archive 'hello-dolly.zip': Zip archive inconsistent: entry 1: local and central headers do not match
```

libzip is used by the [zip](https://github.com/php/php-src/tree/master/ext/zip) extension of PHP, so this affects PHP as well:

```
$opened = ( new ZipArchive() )->open( 'foo.zip', ZipArchive::CHECKCONS );
// returns error code 21 (Zip archive inconsistent)
```

**Expected Behavior**
- The example above should be able to validate the consistency of a zip archive generated by macOS Archive Utility.
- Once PHP updates the libzip version, the PHP example above should be validated successfully as well.

**Observed Behavior**
libzip could not validate the consistency of the zip file.

**To Reproduce**
- Using libzip: `ziptool -c hello-dolly.zip get_archive_comment`
- Using PHP, where the `zip` extension uses `libzip`: `$opened = ( new ZipArchive() )->open( 'foo.zip', ZipArchive::CHECKCONS );`

**libzip Version**
1.9.2

**Operating System**
Zip file generated by macOS Archive Utility (GUI, right click -> Compress), on macOS Ventura (13.0.1).

**Test Files**
[hello-dolly.zip](https://github.com/nih-at/libzip/files/10247261/hello-dolly.zip)

**Additional context**
Apparently, the macOS Archive Utility is known to have a lot of issues. So I believe this bug report is more to workaround issues from Archive Utility, than a bug in libzip per-se.

**Comment by Luc45** [comment]
For additional context, this bug affected WordPress Core a couple of years ago: https://core.trac.wordpress.org/ticket/12637

They worked around it by using PclZip as a [fallback](https://github.com/WordPress/WordPress/blob/master/wp-admin/includes/file.php#L1599-L1600).

**Comment by 0-wiz-0** [comment]
I've just fixed this, thanks for the report!

**Comment by Luc45** [comment]
It seems macOS Archive Utility is to zip what Internet Explorer was to front-end devs in 2005 :smile: 

Thanks a lot for the quick response.
