### ISSUE TITLE
Improve API of zip_source_zip, fix documentation.

### ISSUE THREAD

**Issue by QrczakMK** [nih-at/libzip#347]
From my understanding `zip_source_t` can almost be used as a replacement for `zip_file_t` (reducing the number of concepts). One of exceptions is that `zip_source_zip()` provides compressed data if `start == 0` and (`length == -1` or `length == 0`). Is that supported?

https://github.com/nih-at/libzip/commit/0562f8fb17cc2b051f0436e2ed24045524d1e736 suggests to explicitly pass the whole uncompressed length, but I am worried that some weirdly crafted archive can have a zero uncompressed length but a non-zero compressed length, in which case I suppose this will not work correctly and will return the compressed data. Is this possible and how to work around that?

**Comment by QrczakMK** [comment]
Also, https://github.com/nih-at/libzip/commit/9d6e4aedcb7cb0183063867b1e9b917ff0ba92b4 does not seem correct: according to https://github.com/nih-at/libzip/blob/main/lib/zip_source_zip.c `ZIP_FL_COMPRESSED` has no effect for `zip_source_zip()`, it is completely determined by `start` and `len`.

I wish it just honored presence or absence of `ZIP_FL_COMPRESSED` from the caller.

**Comment by dillof** [comment]
I agree with you, the API is clunky. We will deprecate `zip_source_zip` and replace it with a new function that honours `start`, `length`, and the flags `ZIP_FL_COMPRESSED` and `ZIP_FL_ENCRYPTED` without any special cases.

**Comment by QrczakMK** [comment]
I see that `_zip_source_zip_new()` accepts a password parameter, which is another missing piece wrt. `zip_fopen_index_encrypted()` functionality. Maybe a default password per archive suffices in practice, I don’t know how common it is to need a separate password per file.

**Comment by dillof** [comment]
That's a good point, we will probably add this while we're refining the API.

**Comment by dillof** [comment]
We've now added the new functions `zip_source_zip_file` and `zip_source_zip_file_create` and deprecated the old ones.
