### ISSUE TITLE
Libzip trigger program crash(memory corruption) on closing archive after a adding a file on archive with a source buffer(with freep != 0)

### ISSUE THREAD

**Issue by AkelOlivier** [nih-at/libzip#351]
**Describe the Bug**
Libzip trigger program crash(memory corruption) on closing archive after a adding a file on archive with a source buffer(with freep != 0) ( only when we let libzip take ownship of buffer) .(buffer made on the heap (calloc))
also happen  when instead we only make source buffer  , then we don't add a file from source buffer (we do nothing) then we call zip_source_free ( happen immedialty in that case)

**Expected Behavior**
there should be no crash 

**Observed Behavior**
Exception non gérée à 0x00007FFCF7FAF6A9 (ntdll.dll) dans TestLibZip.exe : 0xC0000374: Un segment de mémoire a été endommagé (paramètres : 0x00007FFCF80197F0).

**To Reproduce**
``` C
struct ZipArchive
{
    zip_t* archive = nullptr;

    ZipArchive(const char* archive_name, int flag, int* error)
    {
        archive = zip_open(archive_name, flag, error);
    }
    ~ZipArchive()
    {
        if (zip_close(archive) == -1)
        {

            zip_discard(archive);
        }

        archive = nullptr;
    }
};

void WriteArchiveBufferOwnshipTransferedToLibZip(const char* archive_filename)//problem here -> crash on archive closed
{
	int  error = 0;
	{
		ZipArchive archive(archive_filename, ZIP_CREATE, &error);
		if (archive.archive)
		{

			//fail crash memory corruption
			auto txt = "crash";
			const auto buffer_lengt = strnlen_s(txt, 255) + 1;
			char* buffer = (char*)calloc(buffer_lengt, 1);
			if (buffer)
			{
				memcpy_s(buffer, buffer_lengt, txt, buffer_lengt);
				auto zip_source = zip_source_buffer(archive.archive, buffer, buffer_lengt, -1);//i give libzip the ownship of heap buffer what is wrong?(double free?)
				if (zip_source)
				{
					if (zip_file_add(archive.archive, "toto.txt", zip_source, ZIP_FL_OVERWRITE | ZIP_FL_ENC_GUESS) == -1)
					{
						//in case there is a problem we got an error when we try to add the file in queue, doesn't happen here
						
						zip_source_free(zip_source);

					}
				}
			}
		}

	}
}
```

**libzip Version**
 libzip 1.9.2(dynamic) debug , zlib-1.2.13(debug dynamic)

**Operating System**
 windows 10 22H2, visual studio 2022/2019, c++20.

**Test Files**
[TestLibZipcrash192.zip](https://github.com/nih-at/libzip/files/10527166/TestLibZipcrash192.zip)
(you will need to remap the include / lib directory in project i didnt provide internaly libzip

**Additional context**
i provide in the file 2 situation with crash ( there is 2 constexp ( constexpr bool IS_BUFFER_FREE_BY_LIBZIP = true; to get crash bug , 
constexpr int ALTERNATIVE_CRASH = 0;// 0 or 1 to trigger bug when close archive , source free .

also i provide a "workaround" with  a function by calling zip_source_keep before closing archive if file_add or source_free  if i do nothing seems to work ( so it is a ref counter bug, double free?)

**Comment by AkelOlivier** [comment]
i tested again with head and 1.9.2( with zlib in debug dll ) (with  proper dll  possible mismatch with libzip.dll from me )  in debug, i can confirm there is no bug in the configuration in both version , i need to test with zlib in static compilation, is libzip supported as if compile as static (with static zlib also?)

**Comment by AkelOlivier** [comment]
tested with static zlib in debug no problem : PASS
i can't compile libzip in static debug i get linker error , did i miss a macro?

**Comment by AkelOlivier** [comment]
the bug was a mismatch between .dll i think (my fault sorry )

**Comment by AkelOlivier** [comment]
i get multiple linker error with libzip (static compiled) and the test app , 

> 1>main.obj : error LNK2019: unresolved external symbol __imp_zip_close referenced in function "public: __cdecl ZipArchive::~ZipArchive(void)" (??1ZipArchive@@QEAA@XZ)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_discard referenced in function "public: __cdecl ZipArchive::~ZipArchive(void)" (??1ZipArchive@@QEAA@XZ)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_error_init referenced in function main
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_fclose referenced in function "public: __cdecl ZipEntry::~ZipEntry(void)" (??1ZipEntry@@QEAA@XZ)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_file_add referenced in function "void __cdecl WriteArchiveBufferOwnshipByUs(char const *)" (?WriteArchiveBufferOwnshipByUs@@YAXPEBD@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_fopen referenced in function "public: __cdecl ZipEntry::ZipEntry(struct zip *,char const *,int)" (??0ZipEntry@@QEAA@PEAUzip@@PEBDH@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_fread referenced in function "void __cdecl ReadArchive(char const *)" (?ReadArchive@@YAXPEBD@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_open referenced in function "public: __cdecl ZipArchive::ZipArchive(char const *,int,int *)" (??0ZipArchive@@QEAA@PEBDHPEAH@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_source_buffer referenced in function "void __cdecl WriteArchiveBufferOwnshipByUs(char const *)" (?WriteArchiveBufferOwnshipByUs@@YAXPEBD@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_source_free referenced in function "void __cdecl WriteArchiveBufferOwnshipByUs(char const *)" (?WriteArchiveBufferOwnshipByUs@@YAXPEBD@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_source_keep referenced in function "void __cdecl WriteArchiveBufferOwnshipTransferedToLibZipWorkaround(char const *)" (?WriteArchiveBufferOwnshipTransferedToLibZipWorkaround@@YAXPEBD@Z)
1>main.obj : error LNK2019: unresolved external symbol __imp_zip_stat referenced in function "public: __cdecl ZipEntry::ZipEntry(struct zip *,char const *,int)" (??0ZipEntry@@QEAA@PEAUzip@@PEBDH@Z)

**Comment by dillof** [comment]
I'm afraid I can't help you there, as I don't use Windows.
