### ISSUE TITLE
zip_source_zip_file() + zip_source_stat() fills stat.name inconsistently with valid & ZIP_STAT_NAME

### ISSUE THREAD

**Issue by QrczakMK** [nih-at/libzip#352]
**Describe the Bug**
For a source created with `_zip_source_zip_new()` (or `zip_source_zip_file()`), `zip_source_stat()` appears to always set `valid & ZIP_STAT_NAME`, but `name` is the name of the archive, not the name of the file inside.

In particular if the archive is unnamed (it comes from `zip_source_function_create()` which does not set `valid & ZIP_STAT_NAME` in its `ZIP_SOURCE_STAT`), then `zip_source_stat()` sets `valid & ZIP_STAT_NAME` but `name == NULL`.

**Expected Behavior**
I expected `zip_source_stat()` to give similar results to `zip_stat_index()`, although I understand that e.g. if data were decompressed then compression method is changed to `ZIP_CM_STORE`.

(If `name` is meant to reflect the archive, then `valid & ZIP_STAT_NAME` should reflect that too.)

I guess this might be caused by `_zip_stat_merge()` merging the whole `valid` but explicitly skipping `name`. Is the reason still valid after the change to layered source ownership rules BTW?

**libzip Version**
1.9.2

**Comment by dillof** [comment]
That shouldn't happen. (I assume the name of the source containing the archive leaks to the source returned by `zip_source_zip_file()`.)
