### ISSUE TITLE
Insufficient documentation regarding stat.size, stat.comp_size, and stat.comp_method

### ISSUE THREAD

**Issue by QrczakMK** [nih-at/libzip#353]
**Description**
It is unclear whether `stat.size` or `stat.comp_size` relates to data being returned by `zip_source_read()`.

It is also unclear how sizes should be filled in `ZIP_SOURCE_STAT`.

From experiments and reading the code it appears that:
* Sources which do not deal with compression, e.g. those created from stdio files, have `size` but not `comp_size` nor `comp_method`. In that case `size` should obviously be used (if present, otherwise size is unknown).
* Sources created by `zip_source_zip_file()` and read from the existing archive have all 3 fields set: `size`, `comp_size`, and `comp_method`. If the file was originally uncompressed, then `comp_method == ZIP_CM_STORE` and `size == comp_size`. But if the file was compressed and `ZIP_FL_COMPRESSED` was not used, then data are being decompressed on the fly, `comp_method == ZIP_CM_STORE`, yet `comp_size` corresponds to the original compressed size. This implies that if `comp_method == ZIP_CM_STORE`, then `zip_source_read()` reads `size` (never `comp_size`), otherwise it reads `comp_size` (never `size`). I guess that if the corresponding `size` or `comp_size` field is absent, then it is better to treat the size as unknown rather than look at the other field.

On the other side, for sources provided by the caller e.g. to `zip_file_add()`:
* If I provide uncompressed data, does it matter whether `comp_method` is set to `ZIP_CM_STORE` or unset? I guess this does not matter.
* If I provide uncompressed data, should I set `size`, `comp_size`, or both? I guess that `size` is important, and setting `comp_size` does not matter (whether `comp_method` is `ZIP_CM_STORE` or unset).
* If I provide compressed data, which fields should be set? This code: https://github.com/nih-at/libzip/blob/993b36cd92b8844dea34340401a59a988e17c739/lib/zip_close.c#L521 indicates that `size` and `crc` are required, besides `comp_method` which is obvious for this case. This makes sense (libzip has no way to find `size` and `crc` without decompressing the data) but is undocumented. I understand that this is niche usage (providing compressed data is normally done when the source comes from another archive, i.e. it is created by libzip itself), but I am going to use this (if I accumulate data for a file in memory before providing them to libzip, it is more memory efficient to compress them on the fly and provide already compressed data than to accumulate and provide uncompressed data).

It would be nice to be able to find this out in the documentation. It is not obvious that for finding out how much `zip_source_read()` will read, one needs to consult either `size` or `comp_size` depending on `comp_method`.

Also, I suppose that compressed sources are meaningful only for `zip_file_add()` and `zip_file_replace()`, but not e.g. to `zip_open_from_source()`.

Also, with the new `zip_source_zip_file()` being used to transfer a file from one archive to another, it is not obvious that doing that both with and without `ZIP_FL_COMPRESSED` works correctly, but with `ZIP_FL_COMPRESSED` it will be more efficient by avoiding to recompress the file.

**Comment by QrczakMK** [comment]
Thank you for quick response.

My code can make use of knowing the exact size which will be read by future calls to e.g. `zip_source_read()`.

(This is used e.g. to choose the strategy for reading the whole contents into `std::string` or a similar type — whether it can be preallocated to its final size and read in one step, or whether we must read in fragments. This is also used for tuning buffer sizes — they can be initially more generous if the whole contents are known to be long enough, and the last buffer can be smaller if it intersects with the end of data.)

It is generally fine if the size is not known, but it is important to have precise rules for finding out the optional size and whether it is known.

If an absent `comp_method` is always treated the same as `ZIP_CM_STORE`, then maybe `ZIP_STAT_COMP_METHOD` should not exist? Or it should exist merely for consistency with other fields?

BTW, it looks like `ZIP_FL_RECOMPRESS` is no longer used anywhere but it is still defined. Should it continue to be defined for compatibility, even though it does not do anything?

**Comment by dillof** [comment]
> It is generally fine if the size is not known, but it is important to have precise rules for finding out the optional size and whether it is known.

For uncompressed data, `zip_source_read()` **should** return `size` bytes of data, for compressed data, it **should** return `comp_size` bytes. However, sources can return different number of bytes (both more or less), so your program should be able to handle it (if only by reporting an error).

> 
> If an absent `comp_method` is always treated the same as `ZIP_CM_STORE`, then maybe `ZIP_STAT_COMP_METHOD` should not exist? Or it should exist merely for consistency with other fields?

There is a difference between knowing the data is uncompressed and simply assuming it. I think it's good to have a way to express this difference.

> 
> BTW, it looks like `ZIP_FL_RECOMPRESS` is no longer used anywhere but it is still defined. Should it continue to be defined for compatibility, even though it does not do anything?

It should be marked as deprecated.
