### ISSUE TITLE
Libzip doesn't notice a zip-bomb, unlike unzip

### ISSUE THREAD

**Issue by ImustBuySomeBreadToday** [nih-at/libzip#354]
OS: Debian 11
I have archive manager named "Ark", version 20.12.2. Said archive manager can use libzip (version 1.7.3-1) to unpack zip files. To be sure that it uses libzip, I disabled literally all plugins except libzip in Ark's configuration. I gave it non-recursive zip-bomb to unpack and it unpacked it without throwing any warnings or errors. Then I used unzip (version 6.00) to unpack said zip-bomb and it gave me error, "error: invalid zip file with overlapped components (possible zip bomb)"

I used zip-bomb "zbsm.zip" (https://www.bamsoftware.com/hacks/zipbomb/zbsm.zip) made for following article about making zip-bombs (warning, it unpacks to about 5.5 GB, use only for educational purposes and at your own risk!!! The same goes for the article, use it only for educational purposes and experiment at your own risk): https://www.bamsoftware.com/hacks/zipbomb/

I suggest, that libzip should throw error like unzip at such zip files.

**Comment by dillof** [comment]
Overlapping data is not explicitly forbidden by the ZIP specification, and you would be surprised at the amount of borderline valid zip archives created by various tools. 

Catching most zip bombs without also catching archives in real-world use requires more effort than we are able to put in.

Also, the standard version of unzip does not catch zip bombs either, Debian's version contains a patch explicitly for this.
