### ISSUE TITLE
Passing an already open source to zip_open_from_source() is unspecified and inconsistent

### ISSUE THREAD

**Issue by QrczakMK** [nih-at/libzip#355]
**Describe the Bug**
https://github.com/nih-at/libzip/blob/main/lib/zip_source_open.c#L48

This indicates that if an already open source is passed to `zip_open_from_source()`, which calls `zip_source_open()`, then this fails only if the source is not seekable.

This is likely to be able to seek to the beginning. But such seek is not actually performed, only internal variables like `bytes_read` are reset. What is the intended behavior? Also, perhaps the source is at position 0, in which case supporting seeking is not needed.

Also, recently introduced `ZIP_SOURCE_SUPPORTS_REOPEN` might be relevant. Even if arbitrary seeking is not supported, perhaps the source should be closed and opened.

**Expected Behavior**
Either passing an already open source to `zip_open_from_source()` and/or `zip_source_open()` should be disallowed (then it should unconditionally fail instead of checking for seekability), or it should be allowed if it is possible to bring the source to the initial state (then the seek to 0 should be performed, or it should not be required to be supported if the current position is 0, or the source could be closed and reopened if that is supported).

**Observed Behavior**
I only looked at the source.

**libzip Version**
Repository at head.

**Comment by dillof** [comment]
`zip_open_from_source()` always fails for sources that don't support seeking, regardless of whether they are already open.

If a source does not support seeking, it doesn't make sense for two users to open it at the same time, since they would get in each other's way when reading data.
