### ISSUE TITLE
Getter for zip_set_file_compression()

### ISSUE THREAD

**Issue by QrczakMK** [nih-at/libzip#358]
**Description**
`zip_set_file_compression()` sets the compression algorithm and level which will be used when the archive is closed.

There is no direct way to get these values. `zip_stat_index()` returns the current compression algorithm, and in the case of changed data they return whatever `ZIP_SOURCE_STAT` returned, only possibly with updated modification time if `zip_file_set_mtime()` was used:
https://github.com/nih-at/libzip/blob/401ef3dd977066bc8f9b9ae53ce60934501b47d0/lib/zip_stat_index.c#L58

I would like to get these values without redundantly tracking them myself.

Use case:
* A client of my API creates a new empty entry to be written to. It gets a `ZipWriter::Iterator`.
* Optionally the client sets the compression algorithm (e.g. to `ZIP_CM_STORE`). This calls `zip_set_file_compression()`.
* The client prepares data to write. The writing class accumulates data in memory, and will call `zip_file_replace()` when writing is done. Data are normally accumulated compressed (and they get uncompressed if compression turned out to be ineffective). But if the compression algorithm was forced to `ZIP_CM_STORE`, then it is better to accumulate uncompressed data — likely the client knows that they are incompressible, and they will be stored uncompressed anyway. The problem is that the writing class cannot detect whether `zip_set_file_compression()` was called — it only knows `ZipWriter::Iterator`, from which it gets an index and the archive.

**Solution**
I think `zip_stat_index()` should not be changed to return these values, because they do not correspond to `comp_size`, nor to what would be read with `ZIP_FL_COMPRESSED`.

So perhaps a new function like `zip_get_file_compression()` could be provided, so that the caller can know if the compression algorithm and level for writing the given entry are left as defaults or were forced to concrete values.

**Describe alternatives you've considered**
I can track myself for which indices a different compression algorithm was forced (and which one), remembering to update that whenever that might change (`zip_set_file_compression()`, `zip_delete()`, `zip_unchange()`, `zip_unchange_all()`). This is brittle and requires more logic on my side.

I can skip the optimization of not compressing data which will be stored uncompressed anyway. But if I wanted to support other algorithms than deflate, ensuring that data are accumulated using the right compression algorithm gets more important — recompressing from deflate to zstd if data could have been accumulated as zstd in the first place is silly.

**Comment by dillof** [comment]
We've fixed `zip_stat_index()` to return the correct compression method, even when it has been changed. This should do what you want. When the compression method has been changed, comp_size is set to invalid (since we don't know it).

**Comment by QrczakMK** [comment]
Thank you. Unfortunately after adding an empty file, created with `zip_source_buffer(zip, NULL, 0, 0)` (which reserves the slot for adding actual contents later and gets the index if it was added by name), the compression method is `ZIP_CM_STORE`, not `ZIP_CM_DEFAULT`, which does not allow to distinguish whether `zip_set_file_compression(ZIP_CM_STORE)` was then called or not. How to add dummy contents in a way which keeps the compression method `ZIP_CM_DEFAULT` for now?

**Comment by dillof** [comment]
Good catch. In that case, `zip_stat_index()` now doesn't sets `ZIP_STAT_COMP_METHOD` in valid. 

If you explicitly set it to `ZIP_CM_STORE`, `ZIP_STAT_COMP_METHOD` is valid and `comp_method` is `ZIP_CM_STORE`.

**Comment by QrczakMK** [comment]
Thank you, I verified that it works as expected.

**Comment by QrczakMK** [comment]
Eh, this is insufficient because `zip_stat_index()` does not provide the the compression level — so in the current state the compression settings must still be tracked separately.

**Comment by dillof** [comment]
The compression level isn't known for existing files and is of very limited use as most applications just use the default.

Why do you need to track the compression level? I understand that you want to track the compression method, but do you really intend to use different compression flags?

**Comment by QrczakMK** [comment]
I am making a C++ API for working with zip files.

It involves the following types, among others, and simplified:
* `ZipWriter` — An open archive which supports writing. Internally owns a `zip_t*`.
* `ZipWriter::Iterator` — Refers to a file in an archive. Internally refers to a `ZipWriter` and contains an index.
* `ZipFileWriter` — Accumulates data to be written to a file in an archive. Will write them when it is closed (using `zip_file_replace()`). Internally contains a `ZipWriter::Iterator`. Ideally data should be accumulated using the same compression as will eventually be used.
* `Reader` and `Writer` — like `std::istream` and `std::ostream` but better (https://github.com/google/riegeli).

There are two strategies to add a file to an archive: by passing a `Reader` which provides our data, or by obtaining a `Writer` and writing our data to it.

Involved methods:
* `ZipWriter::AddFile()` — Creates an entry with the given name, which will read data from a `Reader` (or some other provider of `zip_source_t*`), returns `ZipWriter::Iterator` for further modifications of the file which was added.
* `ZipWriter::CreateFile()` — Creates an entry with the given name (empty for now), returns a `ZipWriter::Iterator`.
* `ZipWriter::Iterator::SetCompressionMethod()` — Overrides the compession method, returns `*this` for convenience of chaining.
* `ZipFileWriter` can be constructed from `ZipWriter::Iterator`. This can be implicit: various contexts which need a `Writer`, a `ZipWriter::Iterator` is implicitly wrapped in `ZipFileWriter`.

Hence there are two ways to add a file with contents as a string:
1. `zip_writer.AddFile(filename, StringReader(contents))`
2. `Write(contents, zip_writer.CreateFile(filename))`

If compression method is to be overridden:
1. `zip_writer.AddFile(filename, StringReader(contents)).SetCompressionMethod(method, level)`
2. `Write(contents, zip_writer.CreateFile(filename).SetCompressionMethod(method, level))`

The implementation of 1 is straightforward. `ZipWriter::Iterator::SetCompressionMethod()` just calls `zip_set_file_compression()`.

For 2 the problem is the in `ZipFileWriter` (which is implicit here, this is the same as `Write(contents, ZipFileWriter(zip_writer.CreateFile(…)))`). It needs to know how to compress the data. Possibilities:
* Compression method was not overridden — Compress with deflate (with the default compression level). If compression turned out to reduce data size, pass compressed data, otherwise pass a `zip_source_t` which decompresses the data back.
* Compression method was forced to `ZIP_CM_STORE` — Do not compress (and do not compute CRC if libzip will not use it anyway).
* Compression method was forced to `ZIP_CM_DEFLATE` — Compress with deflate (with the same compression level was was passed to `SetCompressionMethod()`), and always pass compressed data.
* Compression method was forced to something else — Compress with the appropriate algorithm if we know how to do that.

For that to work, it needs to know whether `ZipWriter::Iterator::SetCompressionMethod()` was called and with what arguments. The information is stored in `struct zip_entry`. I need to either get that information back from libzip, or redundantly remember for which indices `ZipWriter::Iterator::SetCompressionMethod()` was called with what arguments.

**Comment by dillof** [comment]
So the problem is that you want to compress the data yourself, with parameters that were passed earlier? In that case, you should keep track of these parameters yourself. You don't need to pass them on to libzip at all in that case.

Sorry, but this is too much of an edge case to extend the libzip API for. We try to keep it reasonably small.
