### ISSUE TITLE
`zip_close()` does not make use of `stat.crc` if provided for uncompressed data, recomputes it instead

### ISSUE THREAD

**Issue by QrczakMK** [nih-at/libzip#359]
**Description**
The caller might have provided CRC of data which will use `ZIP_CM_STORE`, e.g. because CRC was computed anyway before it was known which compression method will be used.

A reasonable logic for a caller which accumulates data in memory, for default compression:
* Compute CRC and compress data with deflate on the fly, with the assumption that compressed data will be used in the archive.
* Once data are ready, if the compressed size turns out to be greater than uncompressed size, it is better to use `ZIP_CM_STORE` after all. So the caller provides a source which uncompresses data back — compression was wasted, we could not have known that. But the CRC was already computed, it can be trivially provided.

https://github.com/nih-at/libzip/blob/71887a39a7113c6c1a1a9ef0604206ff04538557/lib/zip_close.c#L388-L389

Libzip does not make use of CRC in such case. It can recompute it so it will recompute it.

**Solution**
It would be more efficient to trust CRC if provided by the caller. It is trusted anyway in the case of compressed data.

**Describe alternatives you've considered**
This is just an optimization.

**Comment by dillof** [comment]
If the provided CRC is incorrect and libzip uses it without recomputing it, it would create an invalid zip file. We think the small performance gain is not worth the risk of corrupting data.

**Comment by QrczakMK** [comment]
OK, but you can still create an invalid zip file when a source provides invalid compressed data (or with invalid crc).

**Comment by dillof** [comment]
True, but in that case libzip can't efficiently ensure the validity (or at all, if the compression method is not supported by libzip directly). Calculating the CRC is cheap, so we do it.
