### ISSUE TITLE
Please make zip_source_t refcounting thread-safe

### ISSUE THREAD

**Issue by QrczakMK** [nih-at/libzip#360]
**Description**
A common assumption about reference counted objects is that adding and removing references can be done in separate threads without synchronization.

This in particular applies to C++ `std::shared_ptr` and this is the default for `boost::intrusive_ref_counter`.

This should be applied to `zip_source_keep()` and `zip_source_free()`.

**Solution**
Make `refcount` in `struct zip_source` atomic.

I don’t know if `<stdatomic.h>` can be assumed to be present (C11). If so, `refcount` is `_Atomic(unsigned)`, `zip_source_keep()` does:
```
atomic_fetch_add_explicit(&src->refcount, 1, memory_order_relaxed);
```

And `zip_source_free()`:
```
if (atomic_load_explicit(&src->refcount, memory_order_acquire) > 1 &&
    atomic_fetch_sub_explicit(&src->refcount, 1, memory_order_acq_rel) > 1) {
    return;
}
```

**Describe alternatives you've considered**
If reference counting performed by libzip is not atomic, and `zip_source_t` is to be wrapped in a library which wants to provide regular thread safety guarantees regarding wrapped sources, then the wrapper must provide its own synchronization, while making assumptions about which sources given to `zip_t` or obtained from `zip_t` can have their reference counts adjusted by which operations.

In my design a wrapped source is associated with an *origin*. For a directly constructed source, the origin is the object which provides the operations. For a source obtained by `zip_source_zip_file()`, the origin is the origin of the archive, i.e. the origin of the source previously passed to `zip_open_from_source()` (unless this is a source we added and `ZIP_FL_UNCHANGED` is not being used). The origin is asked for failure details, which can be richer than `errno` value (https://github.com/abseil/abseil-cpp/blob/master/absl/status/status.h). The origin also hosts a mutex, so that separate files from the same zip archive can be safely accessed concurrently — they all share the origin of the archive, so libzip operations on distinct files of the archive are not actually called concurrently (I believe this is required).

`zip_close()` accesses refcounts of all sources previously given to `zip_t`, while the sources might have refcounts concurrently adjusted by separate threads. This means that the wrapper needs to:
* Lock not only the mutex of the archive, but also all mutexes corresponding to origins of all sources added to the archive (in some deterministic order, e.g. sorted by addresses, with duplicates removed, to avoid deadlocks if another thread does the same with a different set of sources — even if the given source should not be accessed concurrently, different sources sharing the same origin can).
* Call `zip_close()`.
* Whenever `zip_close()` calls out to a callback of some source, the callback needs to unlock all these mutexes (communicated somehow to it, e.g. using a thread-local variable), lock again only the mutex corresponding to the given source, before performing an operation specific to that source, and afterwards undo unlock the mutex and lock all previously unlocked mutexes. This ensures that during an operation on a source, only the mutex corresponding to that source is locked by the current thread. But this has a cost of *O(N²)* where *N* is the number of distinct origins of sources added to the archive (this is the number of sources if they are e.g. standalone files). And this is quite complicated.

If libzip’s refcounts are thread-safe, the wrapper of `zip_close()` would not need to lock all mutexes of the sources at the same time, only the single mutex of the archive, and closing the archive has a cost of *O(N)*. The mutex must still be exchanged in any callback though.

Also, in the current state wrapping `zip_file_add()` with `ZIP_FL_OVERWRITE` must be performed in a roundabout way, because it may access a source whose index is not a priori known. So it needs to lock the mutex of the archive, call `zip_name_locate()`, and if it turns out that a source is being overwritten, then it must unlock the mutex of the archive and lock up to 3 mutexes (sorted and with duplicates removed): of the archive, of the old source, and of the new source. If libzip’s refcounts are thread-safe, the wrapper of `zip_file_add()` can lock 2 mutexes for the whole duration of the operation: of the archive and of the old source, remembering to arrange for them to be exchanged in the callback of the old source if its last reference is dropped.

**Comment by dillof** [comment]
We're currently aiming at compatibility with C89, so `stdatomic.h` can't be assumed, but we could make use of it if it is present. You can then require it for your wrapper, which should be good enough.

However, I don't quite understand the gain. If you want to do anything with a source except call `zip_source_free()` or `zip_source_keep()` on it, you still have to synchronise access to it, so I don't see how that would help in the case of `zip_close()`.

The thread safety model of libzip does not match your intended model. Since we don't want libzip to depend on any multithreading implementation, that will not change. So the question is, can you adjust yours to more closely match libzip's?

**Comment by QrczakMK** [comment]
It is fine if only `zip_source_free()` and `zip_source_keep()` are valid concurrently. Even though it is unlikely in practice that some other thread would concurrently copy or drop a wrapped source handle, disallowing that would break standard assumptions about what is valid concurrently, so I need to emulate that.

I can cope with the existing model, it is just more complicated and leads to quadratic complexity of `zip_close()`.

In the existing model I need to track ownership of stored sources, mirroring what libzip does, and `ZIP_SOURCE_FREE` does nothing. I need to know when libzip might call `zip_source_free()` or `zip_source_keep()` on my sources (e.g. `zip_file_replace()` touches the old source stored at the given index; `zip_discard()` touches all stored sources), and lock all mutexes associated with their origins around the operation. I also need to know when libzip might call source callbacks (in particular `zip_close()` calls that on all stored sources), and arrange to exchange locked mutexes in that case, so that the implementation of the callback sees only the given source locked — as it might legitimately access sources which share origins with other stored sources, and they should not be locked.

If `zip_source_free()` and `zip_source_keep()` are atomic, then I can rely on libzip’s ownership tracking more, I can let it decide which sources it touches in a particular operation, and I don’t need to proactively lock their mutexes — although I would still store sources corresponding to indices myself, for failure propagation. `zip_close()` and `zip_discard()` would need only a single mutex locked beforehand. OTOH the callback of `zip_source_free()` becomes significant, and thus I need to arrange to potentially exchange locked mutexes inside all operations which might call `zip_source_free()` on my sources.

**Comment by dillof** [comment]
From what I understand about your setup, I think it might be easier to only pass the sources to libzip before calling `zip_close()` and keep them and the desired compression settings in your own structs until then.

**Comment by QrczakMK** [comment]
I support e.g. `zip_stat_index()` and `zip_source_zip_file()` (as methods of `ZipReader::Iterator`), with libzip semantics: get the new sources if they have been added or replaced and `ZIP_FL_UNCHANGED` was not specified (when obtaining the `Iterator`). `ZipWriter` derives from `ZipReader` and `ZipWriter::Iterator` derives from `ZipReader::Iterator`.

So yes, that would be possible, at the cost of emulating even more behavior myself instead of getting it from libzip. For example `ZipReader::Iterator::Stat()`, if the source is new, would fill out the name, index, and update modification time, like `zip_stat_index()` does. This means I would need to keep track of overridden modification times. I would likely need to keep track of the mapping from entry names, so that name conflict failures from `zip_file_add()` are reported immediately instead of delayed to `zip_close()`. This is getting too complicated, although that would be an interesting alternative.

In the current state (work in progress) I keep track of added sources for atomicity of reference counting and for failure propagation, and of overridden compression method / compression level for buffering appropriately compressed data.

(This is already quite complicated because I support sources implicitly keeping the archive alive. The caller can obtain the source corresponding to an entry, forget about the archive without closing it, and read from the source. Or even from multiple such sources in multiple threads — they lock the mutex of their origin, i.e. of the archive. The archive gets freed by `zip_discard()` when the last such source is dropped.)

**Comment by dillof** [comment]
I've given this more thought, and it won't work: If a source is open for reading when `zip_source_free()` is called on its last reference, then it will call `zip_source_close()` on it, which in turn will call `zip_source_close()` on the lower source for layered sources, which is neither locked nor guaranteed not to be reachable from another thread.

(I'm not sure if libzip actually does this yet, but it will once we've cleaned up the handling of source references.)
