### ISSUE TITLE
Removing a `zip_source_t` is too sticky

### ISSUE THREAD

**Issue by QrczakMK** [nih-at/libzip#362]
**Describe the Bug**
One can think of `zip_source_t` as specifying the location of bytes.

Let’s consider a source which cannot be physically removed, as it corresponds to a string-like object in memory. Its `ZIP_SOURCE_REMOVE` truncates it to empty (for consistency its `ZIP_SOURCE_ACCEPT_EMPTY` returns 1).

Let’s consider a program which writes an archive to this source, and the archive happens to be empty. Then it writes another archive to the same source.

**Expected Behavior**
The archive can be written again.

**Observed Behavior**
`zip_open_from_source()` calls `_zip_file_exists()` which calls `zip_source_stat()`. This kind of source will always “exist”. Then `zip_open_from_source()` calls `zip_source_open()` which checks `src->write_state == ZIP_SOURCE_WRITE_REMOVED` and fails.

Note that the analogous program behavior would work with a file-based source, because the second time it will be considered to not exist.

A workaround is to avoid reusing a `zip_source_t` if such scenario may occur, but I believe it should work.

**libzip Version**
1.9.2

**Operating System**
Linux.

**Additional context**
I encountered a similar issue before when emulating `ZIP_AFL_CREATE_OR_KEEP_FILE_FOR_EMPTY_ARCHIVE` for libzip 1.9.2. Even if `ZIP_SOURCE_REMOVE` is tweaked to create an empty archive, it cannot be opened again without changing `write_state`, which cannot be done with the public API. Pretending that the archive does not exist in that state would not work correctly if the intended semantics of later reopening is to see possible changes made in the meantime to the archive by independent code.

**Comment by dillof** [comment]
I've changed `zip_source_stat()` to return the same error as `zip_source_file` does for non-existing files.
