### ISSUE TITLE
`zipmerge` recompresses file with `deflate` even if `store` produces a smaller in-archive file size and was already used

### ISSUE THREAD

**Issue by illwieckz** [nih-at/libzip#363]
**Describe the Bug**

`zipmerge` recompresses file with `deflate` even if `store` produces a smaller in-archive file size and was already used.

**Expected Behavior**

`zipmerge` would save the file with `store` if that produces a smaller file, especially if that was the format used in the merged archive.

**Observed Behavior**

I own a file that is known to not compress with deflate, as deflate even produces a larger file than the uncompressed on.

It's the `lm_0000.webp` file from `map-antares_1.0.3.dpk` from `unvanquished_0.54.0.zip` release (that WebP file is attached).

I made a zip with `7z -tzip -mx=0 a lm_0000.webp.store.zip lm_0000.webp` to archive this file without compressing it

After merging this zip into another zip, the merged zipped file use deflate algorithm and the in-archive size is larger.

The same would happen if I make a file with `zip --compression-method store lm_0000.webp.store.zip lm_0000.webp` and merge it after that.

**To Reproduce**

Get the attached `lm_0000.webp.store.zip` zip archive containing a `lm_0000.webp` WebP image file.

Then, run this command to merge this zip archive into a new zip archive:

```
$ zipmerge lm_0000.webp.merge.zip lm_0000.webp.store.zip
```

Looking at zip details, once merged, archived file is using `deflate` algorithm and is actually larger:

```
$ zipinfo lm_0000.webp.store.zip
Archive:  lm_0000.webp.store.zip
Zip file size: 730572 bytes, number of entries: 1
-rw-r--r--  6.3 unx   730414 bx stor 23-Jan-29 18:30 lm_0000.webp
1 file, 730414 bytes uncompressed, 730414 bytes compressed:  0.0%
```

```
$ zipinfo lm_0000.webp.merge.zip
Archive:  lm_0000.webp.merge.zip
Zip file size: 730687 bytes, number of entries: 1
-rw-r--r--  6.3 unx   730414 bx defX 23-Jan-29 18:30 lm_0000.webp
1 file, 730414 bytes uncompressed, 730529 bytes compressed:  0.0%
```

**libzip Version**

Commit 8cffbf50744b18e5275b2ea36f707efc1c2c4e8c

**Operating System**

Ubuntu 22.10, Linux 5.15.0, GCC 12.2.0.

**Test Files**

[lm_0000.webp.store.zip](https://github.com/nih-at/libzip/files/10903397/lm_0000.webp.store.zip)

**Comment by 0-wiz-0** [comment]
Use `zipmerge -k` if you don't want to compress uncompressed files (available since https://github.com/nih-at/libzip/commit/d8eed76e188d03bb61b9b0bee69e49a0b9f11f4a).
