### ISSUE TITLE
Add minimum permissions for workflows

### ISSUE THREAD

**Issue by gabibguti** [nih-at/libzip#364]
**Description**
Add minimum permissions to workflows to keep your workflows safe against supply-chain attacks. 
I checked and this feature is not mentioned in TODO.md.

**Solution**
I'd like us to set minimum permissions for each workflow, granting only the necessary permissions based on the actions used. I see `CIFuzz` and `build` workflows do not need many permissions, only `contents: read` to read the repository. `CodeQL` workflow needs a few more permissions to perform `github/codeql-action/init` and `github/codeql-action/autobuild` actions. I can open a PR if you agree to make the changes more clear.

This setting is considered good-practice and recommended by [GitHub](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) itself and by other security tools, such as [Scorecards](https://github.com/ossf/scorecard) and [StepSecurity](https://github.com/step-security).

**Describe alternatives you've considered**
None.

**Additional context**
I'm Gabriela and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by 0-wiz-0** [comment]
This sounds good, please go ahead with the PR! Thank you.

**Comment by 0-wiz-0** [comment]
I've merged the changes - thanks for the contribution!
