### ISSUE TITLE
Reference actions by commit SHA

### ISSUE THREAD

**Issue by gabibguti** [nih-at/libzip#377]
**Description**
Referencing actions by commit SHA in workflows to keep your repository safe against supply-chain attacks.
As for now, I didn't find this feature mentioned in TODO.md.

**Solution**
I'd like us to reference actions by commit SHA in workflows to ensure we are using an immutable version. Actions referenced by tags and branches are vulnerable to attacks, such as moving a tag to a malicious commit, pushing a malicious commit to the branch, or typosquatting.

While each reference has its advantages and disadvantages, GitHub acknowledges that [using commit SHAs is more reliable](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-shas), as does [Scorecard](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies) security tool.

Currently, this repository uses actions referenced by tags and branches, such as `actions/upload-artifact@v1` and `google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master`. If you agree, I can open a PR to change these references to commit SHAs.

**Describe alternatives you've considered**
None.

**Additional context**
Hi again! I'm Gabriela, I recently suggested https://github.com/nih-at/libzip/issues/364, and I work on behalf of Google and the OpenSSF suggesting supply-chain security changes :)

**Comment by 0-wiz-0** [comment]
Hi again!
We've actually recently be talking about this internally.
Right now, we have not even tagged all workflows we use, but use master for some of them.
If we used the git hashes and/or tags everywhere, we'd have to monitor that new versions of the workflows are available.
How do other projects do that?

On the other hand, we don't see an effective attack potential here - we are using workflows for fuzzing and CI, not for creating releases. So we might just not get correct information about the build or fuzz status. What other possible problems do you see here?

**Comment by gabibguti** [comment]
> If we used the git hashes and/or tags everywhere, we'd have to monitor that new versions of the workflows are available.
How do other projects do that?

You can use dependabot or renovatebot. These bots can be configured to update only workflows, and they can identify commit SHA + comments updates.

```
e.g.
uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # v3.1.1
updates to
uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
```

**Comment by gabibguti** [comment]
> On the other hand, we don't see an effective attack potential here - we are using workflows for fuzzing and CI, not for creating releases. So we might just not get correct information about the build or fuzz status. What other possible problems do you see here?

In fact, none! Since we already restricted most permissions in workflows, the potential of attacks is lowered. The one possible attack I see is an attacker being able to change your Code Scanning / Dependabot alerts. Overall, it would be more of a preventive measure.

**Comment by 0-wiz-0** [comment]
Hm, I looked a bit at the docs for dependabot/renovatebot and it doesn't look clear to me how to use them or how appropriate they are for our case.
Anyway, you can send pull requests and we'll merge them.
If you have some for dependabot/renovatebot, I'd appreciate it too.

**Comment by gabibguti** [comment]
> Hm, I looked a bit at the docs for dependabot/renovatebot and it doesn't look clear to me how to use them or how appropriate they are for our case.

Here's how you would configure dependabot to update GitHub actions:
https://github.com/gabibguti/libzip/blob/main/.github/dependabot.yml

And here's how you would configure renovatebot to update GitHub actions (and Dockerfiles but we could restrict it with more settings):
https://github.com/gabibguti/libzip/blob/main/.github/renovate.json

When dependabot identifies an action update, the PR would look like this one:
https://github.com/gabibguti/libzip/pull/5/files

When renovatebot identifies an action update or when you trigger it, the PR would look like this one:
https://github.com/gabibguti/libzip/pull/2/files

Since dependabot and renovatebot can be configured to update only GitHub actions, I believe they would be appropriate for this case where we'd like to reference actions by commit SHA but keep only updating the SHAs and not touching other dependencies. Does it make sense?

**Comment by dillof** [comment]
Since we are not using anything produced by the build (except for the build log in case of errors), we don't think the added complexity is worth it. Also, we're only using actions from GitHub, Google, and the vcpkg team, which have easier and harder to detect ways to screw up our build.

I understand why this makes sense in other contexts, where the automated builds play a more central role.

Sorry if this caused you wasted effort, but we don't take decisions with security implications lightly.
