### ISSUE TITLE
pkg-config file does not use Libs/Libs.private correctly

### ISSUE THREAD

**Issue by lachs0r** [nih-at/libzip#38]
The `Libs:` line should only contain the shared libraries required to use libzip (i.e. just libzip itself). `Libs.private` should contain libraries required for static linking, i.e. the dependencies.

In particular, `-lbz2` should be under `Libs.private` and not under `Libs` – otherwise, it breaks linking in many cases.

**Comment by dillof** [comment]
Thanks, merged.
