### ISSUE TITLE
Support deflate with preset dictionary

### ISSUE THREAD

**Issue by yairlenga** [nih-at/libzip#380]
**Description**
The 'deflate' method can take a dictionary to improve compression. This can be extremely useful to improve compression - for my case - large number (1M) or relatively small files (40K each). The request is to allow passing a dictionary to the "add_file" (and related replace_file, add_dir, ...) to specify the dictionary.

**Solution**
On extraction, the inflate method must be called, and only then it indicate which dictionary is needed. Two possible path:
* The caller will have to set the dictionary upfront, and if there is a failure (no dictionary, or dictionary mismatch), there should be an option to retrieve the dictionary ID (adler-32 value)
* Add a callback to allow retrieval of the dictionary

Other methods (zstd) allow for preset dictionary - so ideally the error code should indicate also the algorithm that need the dictionary, as different methods support different structure/id of a dictionary. Likewise, if callback is being implemented, it should pass the algorithms and the required dictionary ID.

Suggesting starting with the single file/single dictionary solution - and leaving the callback (which is needed for the multi-file extraction)

zip_set_dictionary(za, int compression_method void *dictionary, int dict_size)

Which will apply to all future operations on za.

**Describe alternatives you've considered**
More complex solution using callback can be implemented to allow more flexibility - in particular, supporting multiple different dictionaries. Also, might be beneficial to capture the dictionary ID in a field - making it easier to proactively specify the dictionary before attempting to decompress the file.

**Additional context**
Potential saving from preset dictionary can be significant. In my case, each file has lot of shared "headers" which will shrink to practically nothing. Smaller files = less time to read = more time to process.

**Comment by dillof** [comment]
The zip specification has no provision for using custom dictionaries. Also, producing archives that cannot be decompressed without knowledge of the custom dictionary used in compression are not generally useful.

As such, this is also out of scope of libzip.

**Comment by yairlenga** [comment]
Dieterת

Thanks for taking time to review my request. Before making final decision - would like to provide few additional details that can address the points that you identified:

1. Agree that ZIP does not cover detailed on dictionary based compression. However, it does provide placeholders for extra fields, that can be attached to the Zip. Those fields are used with other functions - specifically encryption - to store meta data, certificates, and other meta data.

2. I agree that there is limited use to generating ZIP files where content can not be extracted. However - there is simple implementation that address this. The dictionary can be stored in the Zip archive, and each entry that uses the dictionary can provide (in "extra field") the dictionary that is needed. Given than one dictionary can reduce the size of many entries, it's a clear trade-off toward more efficient compression - which is what ZIP is about.

3. Would be nice to explore using different compression method (e.g. "DEFLATE-DICT") to avoid attempt (and failures) to extract entries that expect a dictionary without providing one.

Personal note: I've been coding in "C" for more than 10 years. If this functionality can be integrated - into the library - I will be more than happy to contribute time to design, implementation, testing - and submit (or collaborating) in preparing code for review.

Hope you will reconsider. If there are other concerns - will be happy to discuss.

Regards,
Yair

**Comment by yairlenga** [comment]
One more comment - trying to keep size manageable. I recently read about various extensions to the ZIP format - where extra fields and/or "hidden" files (starting with ".") are added to a regular ZIP to provide extra performance for specific use cases. For example the SOZip (Seek Optimized ZIP). Following some of the ideas in those extensions, the DEFLATE-DICT can be implemented as:

Entry for foo.txt
     Extra Field: DICT, Value "dict-12345678"    (where 12345678 is the adler number of the dictionary)
     deflate-stream, using above dict ,potentially, with distinct compression method.

Entry for "dict-12345678"
     deflate (or stored) dictionary.

Same functionality will also work to improve performance of zstd (based on my limited understanding).

**Comment by dillof** [comment]
Pioneering new extensions is not a goal of libzip.

If there are existing extensions that already have support in other major zip implementation (or at least others have expressed their willingness to implement these extensions), we will consider adding support for them in libzip.

If you are trying to develop a new extension and get it established (by getting other major zip implementations on board), I'll be willing to provide feedback on your proposal.
