### ISSUE TITLE
zip_open fails with symbolic link on Windows

### ISSUE THREAD

**Issue by ktakahashimtb** [nih-at/libzip#382]
**Describe the Bug**
On Windows, zip_open fails when a path to a symbolic link is given, which points to a zip file.

**Expected Behavior**
zip_open opens the .zip file referenced by the symbolic link

**Observed Behavior**
zip_open fails with error code 28 (ZIP_ER_OPNOTSUPP).

**To Reproduce**
``` c
int error = 0;
const char* path_to_symbolic_link = ...;
zip_open(path_to_symbolic_link, ZIP_RDONLY, &error);
```
To create a symbolic link on Windows, 1) open command prompt with Admin privilege, 2) run "mklink \<name\> \<target\>"

**libzip Version**
v1.7.0 and newer

**Operating System**
Windows

**Test Files**
Any zip file.

**Additional context**
Not sure if this is supposed to work or not, but I see it worked up until version 1.6.1.
On version 1.7.3, the returned error code is 19 (ZIP_ER_NOZIP) instead.

**Comment by 0-wiz-0** [comment]
No, I don't think he is.
But that's a good idea - removing `| FILE_ATTRIBUTE_REPARSE_POINT` there might improve the situation for symlinks.
@ktakahashimtb  Can you please give this a try?

**Comment by ktakahashimtb** [comment]
@0-wiz-0 Would you like to know how updating the file via symlink works on Windows in general or how libzip updates the file?  

If it's the former, I tried notepad and ms word, and the *target* of the symlink is updated not the symlink file itself.   

If the latter, my workaround seems to open the archive in readonly mode so my attempt of updating and overwriting the file did not do the trick.  `zip_open` has this issue to begin with so I cannot open the archive to modify and save.  I'm a newbie using libzip so I'm not sure if there are other ways to update archive with libzip calls.  Any suggestion?

**Comment by ktakahashimtb** [comment]
@0-wiz-0 I have a good news to share 😄 

Spent some time trying to make `zip_open` work with removing `FILE_ATTRIBUTE_REPARSE_POINT` and a few more tweaking.

With `GetFileAttributesEx` call, [the size of the file we receive is the size of the symbolic file itself, not the target](https://learn.microsoft.com/en-us/windows/win32/fileio/symbolic-link-effects-on-file-systems-functions#getfileattributesex).

We can instead first get the file handle by calling `CreateFile` ([which returns the HANDLE of the target if we don't specify FILE_FLAG_OPEN_REPARSE_POINT](https://learn.microsoft.com/en-us/windows/win32/fileio/symbolic-link-effects-on-file-systems-functions#createfile-and-createfiletransacted).  Then, call [GetFileInformationByHandle](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileinformati`onbyhandle), which returns the same kind of information (size, attributes, timestamp) as `GetFileAttributesEx`.

With this change, I can now both read and write to the target file of the symlink.

**Comment by 0-wiz-0** [comment]
That's good progress. 
I was expecting that the symlink would be replaced with a file, that's why I asked...
Please let us know if you make progress on that end as well - we're looking forward to your patch 😃

**Comment by dillof** [comment]
Feedback timeout.
