### ISSUE TITLE
Bypassing Linux file cache

### ISSUE THREAD

**Issue by christophgil** [nih-at/libzip#396]
**Description**

Thanks for this stable and powerful library.

I am developing ZIPsFS, a fuse based file system on Linux which automatically expands ZIP files.
In our department, we are reading scientific files of several GB size range. 
They are bundled together with several meta files in one Zip. We have many ten-thousands of  huge Zip-files 
which are read at a high rate.

To avoid (double)   file bufferung I would like to be able to read a zip entry bypassing the Linux  file cache.

**Solution**
AFAIK this is normaly  done with flag O_DIRECT in open() under Linux.
O_DIRECT is not portable and MacOs and Windows is different.

To my understanding, simply adding O_DIRECT alone would not be enough. 
Buffer size being multiples of 512 and alignment also needs to be taken care for.

Would you be able to add support for this?

Many thanks

Christoph

**Comment by dillof** [comment]
You can add support for this yourself, without modifying libzip, by creating a custom source via `zip_source_function_crreate()` and passing that source to `zip_open_from_source()`.

**Comment by christophgil** [comment]
Hi Dieter,
Great, that is cool I will try this approach.

Thanks so much
Christoph

**Comment by dillof** [comment]
You're welcome. If you need help, feel free to contact us.

**Comment by christophgil** [comment]
Hi Dieter,

I am back  from holiday and ready to look into this again.

My project is getting mature and I am fine-tuning performance.

See  https://github.com/christophgil/ZIPsFS

I roughly understand how a zip_source  call back function is made.

Do you have a minimal example which I could use as a skeleton or a tutorial?
Something like  printing a zip entry data with a path in argv[2] of a zip
file with a path given in argv[1] to stdout?

Cheers
Christoph

**Comment by dillof** [comment]
Not directly, but the man page for `zip_open` has an example how to open a zip archive, and the function `cat_impl_backend` in src/ziptool.c prints the contents of a file to stdout.

**Comment by christophgil** [comment]
Hi Dieter,

It looks as  zip_source_function_create() is not used in src/ziptool.c ???

One more question:  Is using own zip_sources affecting performance as
opposed to using
normal files or file streams?

I want to use O_DIRECT to prevent large files filling the disk cache.

Maybe  as an alternative I could kick out files from the Disk Cache after
all operation finished.
Maybe this could be easier than using O_DIRECT with my own zip source.

What do you think?

Best
Christoph

**Comment by dillof** [comment]
Ah, sorry, we don't really have a good example for using `zip_source_function()`. `read_file()` in lib/zip_source_file_common.c is the part of libzip that implements the standard file sources and is probably the closest we have.

I know very little about file cache management, sorry.

**Comment by christophgil** [comment]
Hi Dieter,
I am also new to cache management.
O_DIRECT is  indeed scary (See
https://www.ibm.com/docs/en/storage-scale/5.0.5?topic=applications-considerations-use-direct-io-o-direct
).
For the moment I will use a less dangerous solution based on fadvise:

After completely reading the ZIP entry, I run the following:

     const int fd=open(path,O_RDONLY);
     if (fd>0){
       posix_fadvise(fd,0,0,POSIX_FADV_DONTNEED);
       execl("/usr/bin/vmtouch","vmtouch","-v",path);
     }

It seems to work as vmtouch indicates that the file is really not in cache
any more.

If beneficial for performance, I might come back to O_DIRECT at a later
time.
For now I am probably happy with fadvise.

Best

Christoph
