### ISSUE TITLE
ETA for 1.10.1

### ISSUE THREAD

**Issue by remicollet** [nih-at/libzip#397]
Hi,

Have you some estimated plan for the 1.10.1 release?

No pressure, as everybody I prefer release when ready (and stable) than bad things done in urgency, and I understand dev time is precious

Context: I have some related changes pending in zip extension for PHP (LENGTH_TO_END/LENGTH_UNCHECKED) which is planned to be released immediately "after" libzip 1.10.1, my question is about inclusion in PHP 8.3 (RC planed for end of August, GA for end of November)

**Comment by dillof** [comment]
A libzip release in the second half of August seems reasonable.

**Comment by remicollet** [comment]
thanks

**Comment by dillof** [comment]
We just released 1.10.1 which includes this change.

**Comment by remicollet** [comment]
Thanks, but version reports is still 1.10.0 (in zipconf.h) :(
