### ISSUE TITLE
Incorrect .pc file with 1.10.0 versus 1.9.2

### ISSUE THREAD

**Issue by heitbaum** [nih-at/libzip#399]
**Describe the Bug**
.pc file with 1.10.0 has the following incorrect line.
`Libs.private:  -lzstdbz2 -lzstdlzma -lzstdZLIB::ZLIB`

**Expected Behavior**
- compile should have the correct Libs.private

**Observed Behavior**
A clear and concise description of what actually happened.
- incorrect generation of .pc file

**To Reproduce**
Short program or code snippet that reproduces the problem.
- compile lib zip 1.10.0 and check the .pc file.

**libzip Version**
Version of libzip or revision repository used.
1.10.0

**Operating System**
Operating system and version, used compiler.
LibreELEC 12.0

**Test Files**
If applicable, attach and describe zip archives that trigger the problem.

**Additional context**
1.9.2
```
prefix=/usr
exec_prefix=${prefix}
bindir=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

zipcmp=${bindir}/zipcmp

Name: libzip
Description: library for handling zip archives
Version: 1.9.2
Libs:  -L${libdir} -lzip
Libs.private:  -lbz2 -llzma -lz
Cflags: -I${includedir}
```

1.10.0
```
prefix=/usr
exec_prefix=${prefix}
bindir=${prefix}/bin
libdir=${prefix}/lib
includedir=${prefix}/include

zipcmp=${bindir}/zipcmp

Name: libzip
Description: library for handling zip archives
Version: 1.10.0
Libs:  -L${libdir} -lzip
Libs.private:  -lzstdbz2 -lzstdlzma -lzstdZLIB::ZLIB
Cflags: -I${includedir}
```

**Comment by 0-wiz-0** [comment]
I can't reproduce this.
Please debug this in your environment.
Take a look at [CMakeLists](https://github.com/nih-at/libzip/blob/ecb4043db21718f5d19b80701bd1e693e566775a/CMakeLists.txt#L354) where ZLIB::ZLIB is replaced in the pkg-config file - find out how that breaks for you.

**Comment by heitbaum** [comment]
Found it.

https://github.com/nih-at/libzip/commit/8c432330fb408037356dba17732e26f589b564c3#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR351

it is the “blank” zstd regex.

**Comment by dktapps** [comment]
Shouldn't that replacement be gated by an `ENABLE_ZSTD` check?

**Comment by 0-wiz-0** [comment]
Please try git head (https://github.com/nih-at/libzip/commit/ccf2ce42926c04648da8fda3c9cfdb7805aa4894), which follows @dktapps's suggestion.

**Comment by dktapps** [comment]
Working for me, thanks!
