### ISSUE TITLE
How to extract non-English file name from zip file?

### ISSUE THREAD

**Issue by sinall** [nih-at/libzip#4]
I failed to use libzippp to extract non-English file name from zip file. I tried to replace zip_open with windows_open in its source, but still doesn't work.
Environment: Win10 + VS2015 + zip archived by 7zip.

**Comment by 0-wiz-0** [comment]
For questions, please use the mailing list.
You need to convert file names to UTF-8 before you can use them; I guess you have UTF-16 file names.
See the man page for `zip_name_locate` for more details about encodings and zip archives:
https://nih.at/libzip/zip_name_locate.html

**Comment by SlySven** [comment]
That link has, of-course rotted, it should now point to: https://libzip.org/documentation/zip_name_locate.html ...! :grinning:
