### ISSUE TITLE
Still a corner case failure with if(ENABLE_ZSTD)

### ISSUE THREAD

**Issue by heitbaum** [nih-at/libzip#404]
I looked at this further today. Whilst there is a workaround by setting ENABLE_ZSTD=OFF the following code still has the chance of erroring. There is an alternative fix in that line 251 could be updated to cause a hard failure, not passthru.

https://github.com/nih-at/libzip/blob/210b09d9d2d0f4c0bbc64f92ad45c1ac53598fec/CMakeLists.txt#L241-L253

Line 353 should really be conditioned by zstd_FOUND or zstd_TARGET, as if zstd is not found then the incorrect .pc file is still generated.

https://github.com/nih-at/libzip/blob/210b09d9d2d0f4c0bbc64f92ad45c1ac53598fec/CMakeLists.txt#L352-L354

**Comment by 0-wiz-0** [comment]
Thanks, fixed
