### ISSUE TITLE
Unfriendly for decompressing windos zip, zip_ Open error=21

### ISSUE THREAD

**Issue by 1397436824** [nih-at/libzip#412]
**Describe the Bug**
Unfriendly for decompressing windos zip, zip_ Open error=21

**Expected Behavior**
zip_ Open error=21

**Observed Behavior**
Compress a more complex directory in Windows and use this library to decompress it。
The Linux zip tool can be decompressed, but the library reported an error

**Comment by 0-wiz-0** [comment]
21 is the error for inconsistent archives.
You could provide an example file, then we can take a look at it, but without that, there is nothing we can do.

**Comment by 0-wiz-0** [comment]
No feedback.
