### ISSUE TITLE
No rule to make target 'zlib.h', needed by 'lib/libzip.dll'

### ISSUE THREAD

**Issue by t1m013y** [nih-at/libzip#423]
**Compiler Error**
```
mingw32-make[2]: *** No rule to make target 'zlib.h', needed by 'lib/libzip.dll'.  Stop.
mingw32-make[1]: *** [CMakeFiles\Makefile2:216: lib/CMakeFiles/zip.dir/all] Error 2
mingw32-make: *** [makefile:145: all] Error 2
```

**libzip Version**
1.10.1 [2023-08-23]

**Operating System and Compiler**
- Windows 11
- cmake version 3.28.2
- GNU Make 4.3 (mingw32-make)
- gcc (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 11.3.0

`cmake -DCMAKE_C_COMPILER=C:/mingw64/bin/gcc.exe -G "MinGW Makefiles" -DZLIB_INCLUDE_DIR="C:/Program Files (x86)/zlib/include/" -DZLIB_LIBRARY=zlib.h ..`

**Autodetected Configuration**
[CMakeCache.txt](https://github.com/nih-at/libzip/files/14102454/CMakeCache.txt)

**Comment by 0-wiz-0** [comment]
I'm sorry, we don't support Windows, but `-DZLIB_LIBRARY=zlib.h` is definitely wrong. `zlib.h` is a header file, not a library.

**Comment by t1m013y** [comment]
What should I pass to `ZLIB_LIBRARY` instead of `zlib.h`?

**Comment by 0-wiz-0** [comment]
I don't know, but probably the path to the zlib.dll file or whatever the shared library is called on Windows.

**Comment by t1m013y** [comment]
Please advice any Windows alternatives for libzip (I'm making Windows app so I need Windows-compatible library)

**Comment by dillof** [comment]
We are not Windows developers, we can't help you there.

**Comment by 0-wiz-0** [comment]
libzip is Windows compatible - you can use e.g. the [vcpkg](https://vcpkg.roundtrip.dev/ports/libzip) for it.

**Comment by t1m013y** [comment]
Ok. Thanks
