### ISSUE TITLE
Creating ZIP archives is not properly handling wchar_t on Windows 11/x64.

### ISSUE THREAD

**Issue by jjYBdx4IL** [nih-at/libzip#430]
The following creates the typical garbled filenames when there is a missing conversion between MultiByte and WideChars:

```
    if ((src = zip_source_win32w_create(zipFile.wstring().c_str(), 0, -1, &error)) == NULL) {
        ...
    }

    if ((za = zip_open_from_source(src, ZIP_CREATE, &error)) == NULL) {
        ...
    }
```

The same source works properly when trying to access Unicode files for archiving, though. It's just the zip file's name itself that's mishandled.

**Comment by dillof** [comment]
`std::wstring::c_str()` does not work for strings containing non-ASCII characters, see https://stackoverflow.com/questions/246806/i-want-to-convert-stdstring-into-a-const-wchar-t
