### ISSUE TITLE
Crash with illegal instruction under Windows 11 x64 ARM virtualization

### ISSUE THREAD

**Issue by RCECoder** [nih-at/libzip#431]
**Describe the Bug**
`zip_source_file_common_new` function causes an exception of 0xC000001D (STATUS_ILLEGAL_INSTRUCTION)
Offensive code: len = ZIP_LENGTH_TO_END

**Expected Behavior**
The Exception should be handled.

**Observed Behavior**
The exception is not handled like in Windows x64. It does not recover after hitting the instruction `LDS EDI,ECX` (Which is what len = ZIP_LENGTH_TO_END is being translated to)
My guess is that Windows ARM does not handle this instruction properly.

**To Reproduce**

```
int err = 0;
zip* z = zip_open("test.zip", 0, &err);
zip_set_default_password(z, "pass");
//Search for the file of given name
const char* name = "test.exe";
struct zip_stat st;
zip_stat_init(&st);
zip_stat(z, name, 0, &st);

//Alloc memory for its uncompressed contents
char* contents = new char[1000];

//Read the compressed file
zip_file* f = zip_fopen(z, name, 0);

```

**libzip Version**
1.10.1

**Operating System**
Windows 11 x64 ARM
Visual Studio 2022 with MSVC compiler.

**Test Files**
Any zip file.

Note: The compiled exe is x86 not native ARM.

**Comment by 0-wiz-0** [comment]
The line `len = ZIP_LENGTH_TO_END` just assigns 0 to an integer variable.
libzip is written in C, so it doesn't throw or catch exceptions.
I'm sorry, you'll have to debug this a bit more yourself. Perhaps start with adding error checking (the code you pasted has none, I hope your real code has much more).
