### ISSUE TITLE
Fix documentation of `zip_source_win32handle`

### ISSUE THREAD

**Issue by fdegros** [nih-at/libzip#432]
The [documentation of `zip_source_win32handle` and `zip_source_win32handle_create`](https://libzip.org/documentation/zip_source_win32handle.html) mentions the `fname` parameter in three places.

However, these documented functions don't take any `fname` parameter. I suspect these references to `fname` come from another function documentation.

**Comment by 0-wiz-0** [comment]
Fixed, thanks!
