### ISSUE TITLE
writing zip file fails

### ISSUE THREAD

**Issue by ChrisAm1224** [nih-at/libzip#435]
I've just pulled the main branch and my zip writing is failing. I've tracked it down to commit ac29119bee5261dd2152b9c8c2c897a6203ad8ad ("Don’t convert time stamps from DOS to Unix and back."). This new code in lib/zip_close.c passes st.mtime to _zip_u2d_time even when the flag ZIP_STAT_MTIME is not set:

            time_t mtime;
            if (st.valid & ZIP_STAT_MTIME) {
                mtime = st.mtime;
            }
            else {
                time(&mtime);
            }
            if (_zip_u2d_time(st.mtime, &de->last_mod, &za->error) < 0) {
                return -1;
            }

I think it should pass mtime, not st.mtime.

**Comment by 0-wiz-0** [comment]
Thank you, fixed!

**Comment by ChrisAm1224** [comment]
Thanks for the quick fix
