### ISSUE TITLE
Using the libzip library to package files suddenly increases CPU load

### ISSUE THREAD

**Issue by fightingLKH** [nih-at/libzip#437]
The CPU load suddenly increases when using the libzip library to package files. Zip_set_file_compression (zip, index,ZIP_CM_STORE,1)， It is set to only perform packaging operations without compression, but the CPU load will increase. The packaged file is approximately 50MB in size

**Comment by dillof** [comment]
By how much does the CPU usage increase? libzip is reading and writing data, and calculating CRCs, so some CPU usage is expected.

Also, could you please provide the source code for relevant portions of the program you're using.

**Comment by fightingLKH** [comment]
Here is my core code. In the zip_set_file_compression() function, the parameter ZIP_CM_STORE was passed in, which only performs packaging operations without compression. If the file is around 40MB, The CPU load will increase by 20%. If the file size is 300M, The CPU load will increase by 50%. May I ask if there are any solutions or improvement codes? Please provide them. Thank you!
zip_source* srcfile=zip_source_file(zip,filePath.c_str(),0,-1);
index=zip_file_add(zip, (currentDir+ entry->d_name).c_str(), srcfile, ZIP_FL_ENC_GUESS);
zip_set_file_compression(zip,index,ZIP_CM_STORE,1)

**Comment by dillof** [comment]
CPU is there to be used, so the percentage increase alone doesn't say much. For how long does it stay at that usage level? Can you try the same operation with some other archival program, like the zip command line tool, and compare usage levels and times?

**Comment by fightingLKH** [comment]
The increase in CPU load will affect the normal operation of other modules, which is not allowed. We hope that when using libzip for packaging, there will be minimal changes in CPU load. Can we handle this through multi-threaded technology? However, I did not see any interfaces for multi-threaded operations on the official website of libzip.

**Comment by dillof** [comment]
No, libzip does not support multi-threaded access to an archive.

Without detailed knowledge of your setup and requirements, I'm afraid I can't help you. If you profile libzip and find a section that is inefficient, we'll gladly look into it.
