### ISSUE TITLE
memory leak in _zip_source_window_new

### ISSUE THREAD

**Issue by jmalmari** [nih-at/libzip#44]
The `window` context it reserves is never freed. Caught with valgrind. Adding `ZIP_SOURCE_FREE` to its `zip_source_make_command_bitmap` call seems to fix it.

**Comment by 0-wiz-0** [comment]
Can you please provide the code (fragment) which you were using?

**Comment by jmalmari** [comment]
Sorry, I don't know the exact test code anymore and I can't reproduce the leak with the one I have. With this uncertainty, it's probably not worth investigating further unless you can see there's something fishy afoot (For instance, why does zip_source_buffer.c:read_data() "ZIP_SOURCE_SUPPORTS" the ZIP_SOURCE_FREE but zip_source_window.c:window_read() doesn't?).

The test created custom function source (zip_source_function_create), made a zip_t out of it (zip_open_from_source), and read one file entry from it before closing the zip. But with just this, the ZIP_SOURCE_FREE command for zip_source_window.c:window_read() is called just fine when closing the zip.

**Comment by dillof** [comment]
zip_source_window already includes ZIP_SOURCE_FREE in its supported commands bitmap (via ZIP_ZIP_SOURCE_SUPPORTS_SEEKABLE).
