### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Neustradamus** [nih-at/libzip#444]
Dear @nih-at team, @dillof, @0-wiz-0,

It is possible to create a new release build?

The latest is 1.10.1 (2023-08-23):
- https://github.com/nih-at/libzip/releases
- https://github.com/nih-at/libzip/tags

Thanks in advance.

**Comment by dillof** [comment]
We just released version 1.11.

**Comment by Neustradamus** [comment]
@dillof: Thanks a lot :)
