### ISSUE TITLE
Related issues with the use of the zip_degistersprogres_callback () function

### ISSUE THREAD

**Issue by fightingLKH** [nih-at/libzip#463]
I want to know the calling rules and frequency of the progress callback function, which is called when zip_close() is used to register the progress callback function, that is, how many times it will be called and how often it will be called. For example, when filing a relatively large file, is this progress callback function called in batches according to file size?

**Comment by dillof** [comment]
According to the documentation:

The callback function is called during [zip_close(3)](https://libzip.org/documentation/zip_close.html) in regular intervals (after every zip archive entry that's completely written to disk, and while writing data for entries).

So for large files, it will be called while writing that file, not only after it is done.

**Comment by fightingLKH** [comment]
Thank you for your reply！
What I mean is that during the archiving period, callback functions are called based on the write size or time, such as calling once when writing 1M data. What is the rule for this.

**Comment by dillof** [comment]
This is not documented on purpose, so we can change it later without breaking any promises.

**Comment by fightingLKH** [comment]
Can I know the call strategy for this function in zip_close？
