### ISSUE TITLE
Amazon Linux 2 Unable to install libzip and libzip5 together

### ISSUE THREAD

**Issue by ajoseph-godaddy** [nih-at/libzip#467]
**Describe the Bug**
Attempting to use multiple versions of PHP requires me to have libzip and libzip5 both installed. This is expected per the description. However when attempting to install either I get the following error:
`Transaction check error:
  file /usr/lib64/libzip.so.5 from install of libzip5-1.10.1-1.el7.remi.x86_64 conflicts with file from package libzip-1.3.2-1.amzn2.0.1.x86_64`

**Expected Behavior**
Install should succeed and both versions should be installed.

**Observed Behavior**
The error shown above

**To Reproduce**
yum install libzip libzip5

**libzip Version**
1.3.2

**Operating System**
Amazon Linux 2

**Test Files**
NA

**Additional context**
NA

**Comment by 0-wiz-0** [comment]
This is a packaging problem. Please report this at your distribution's bug tracker instead. Thanks.
