### ISSUE TITLE
GetSecurityInfo no longer called in zip_source_file_win32_named.c 

### ISSUE THREAD

**Issue by helmutw-copadata** [nih-at/libzip#473]
The ifdef checks added to zip_source_file_win32_named.c with #436 are broken.
This causes ACL_UNSUPPORTED to be defined when compiling for standard windows application or libraries (Desktop Apps).
Therefore GetSecurityInfo is not called in zip_source_file_win32_named.c, line123. This changes the runtime behavior.

**Comment by 0-wiz-0** [comment]
Windows is not our expertise.
What would the correct check look like?

**Comment by 0-wiz-0** [comment]
@sykhro can you please verify that the version above is ok for GDK?

**Comment by dillof** [comment]
We're now checking if the function GetSecurityInfo exists. Hopefully the API partitioning is sane enough to not define that function if it's not available.

Please let us know if it works for you.

**Comment by 0-wiz-0** [comment]
Thanks for testing. Perhaps @sykhro or someone else will let us know if it broke GDK.

**Comment by sykhro** [comment]
I have missed the previous email, my apologies. The current solution should work fine on GDK, the function is only declared for Desktop and UWP partitions.
