### ISSUE TITLE
Provide compatibility support for non-standard files

### ISSUE THREAD

**Issue by lindyer** [nih-at/libzip#476]
Can it provide compatibility support for non-standard files? Some zip files may not be archived completely according to the standard, such as lacking standard file headers, etc. Some compression software such as 7zip do a better job and can open attached documents.
The problem file is nested in the zip file, in order to upload it to GitHub.
[249421.zip](https://github.com/user-attachments/files/17991689/249421.zip)

**Comment by 0-wiz-0** [comment]
I looked at the included `*.ofd` file.
This is just a broken ZIP archive.
At the start it has 9 bytes that do not belong to the zip archive, but the internal references that point to local headers say that the first entry should start at byte 0, not at byte 9. So all the offsets are wrong.
We will not add support for this kind of broken zip archive, sorry.
