### ISSUE TITLE
zip read file will change `\n` to `\r\n`

### ISSUE THREAD

**Issue by nicolgo** [nih-at/libzip#477]
**Describe the Bug**
I have a json file in a zip, when I open the zip and read the json file, the `\n` will be converted to `\r\n`.  code and zip file attached. is there something wrong when I read the file?

**Expected Behavior**
`\n` should not be `\r\n`

**Observed Behavior**
my json file changed

**To Reproduce**
Short program or code snippet that reproduces the problem.
```
  int err_code = 0;
  const std::string zippath = "C:/tmp/111.zip";
  zip_t *archive = zip_open(zippath.c_str(), ZIP_RDONLY, &err_code);
  zip_int64_t file_count = zip_get_num_entries(archive, 0);
  zip_stat_t stat;
  zip_file_t *archive_file = nullptr;
  std::map<std::string, std::vector<char>> map_name_buf;
  for (zip_int64_t i = 0; i < file_count; ++i) {
    if (0 != zip_stat_index(archive, i, 0, &stat)) {
      err_code = -1;
    } else {
      archive_file = zip_fopen_index(archive, i, ZIP_FL_ENC_UTF_8);
      if (!archive_file) {
        err_code = -1;
      } else {
        std::vector<char> tmp_buff;
        tmp_buff.resize(stat.size);
        if (0 > zip_fread(archive_file, tmp_buff.data(), tmp_buff.size())) {
          err_code = -1;
        } else {
          std::string str_file_path = stat.name;
          map_name_buf[str_file_path] = tmp_buff;
        }
      }
      zip_fclose(archive_file);
    }
  }
```

**libzip Version**
Version of libzip or revision repository used.

**Operating System**
Windows11

**Test Files**
If applicable, attach and describe zip archives that trigger the problem.
[111.zip](https://github.com/user-attachments/files/17991773/111.zip)

**Additional context**

**Comment by dillof** [comment]
This conversion took place while creating the zip archive:

$ unzip -p ~/Downloads/111.zip  | hexdump | less 
0000000 0d7b 200a 2220 6966 7372 5f74 616e 656d 
0000010 3a22 2220 6f4a 6e68 2c22 **0a0d** 2020 6c22

It has nothing to do with libzip.
