### ISSUE TITLE
Cmake doesn't work, Why?

### ISSUE THREAD

**Issue by sukhchainn** [nih-at/libzip#52]
When configuring CMake it generates "Incomplete files : Configuring incomplete, errors occurred!",

CMake Error at G:/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  G:/CMake/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  G:/CMake/share/cmake-3.9/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:174 (FIND_PACKAGE)

**Comment by 0-wiz-0** [comment]
The error message is
`Could NOT find ZLIB (missing: ZLIB_INCLUDE_DIR)`
so it does not find zlib. Install zlib, and tell cmake where to look for it (possibly by setting `ZLIB_ROOT`).

**Comment by sukhchainn** [comment]
Thank you

**Comment by sukhchainn** [comment]
So I will have to install it in the compiler's bin directory?
or I can just simply make it and then place it in a separate folder?
