### ISSUE TITLE
What should I do now?

### ISSUE THREAD

**Issue by sukhchainn** [nih-at/libzip#53]
Could NOT find NETTLE (missing: NETTLE_LIBRARY NETTLE_INCLUDE_DIR) 
Could NOT find GnuTLS (missing: GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR) 
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) 
Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:188 (MESSAGE):
  -- bzip2 library not found; bzip2 support disabled

CMake Warning at CMakeLists.txt:207 (MESSAGE):
  -- neither OpenSSL nor GnuTLS found; AES support disabled

Configuring done
Generating done

**Comment by 0-wiz-0** [comment]
I'm sorry, this is not a support forum for cmake. Just read the output, and read `INSTALL.md`, that should give you some hints what to install first.

**Comment by sukhchainn** [comment]
Atleast tell me what is OpenSSL or GnuTLS?

I have successfully installed bzip2 but having difficulty in configuring GnuTLS.
Can I move to OpenSSL without installing GnuTLS?
