### ISSUE TITLE
This is important one!

### ISSUE THREAD

**Issue by sukhchainn** [nih-at/libzip#54]
Is it important to download and configure both OpenSSL and GnuTLS
or I can just go with OpenSSL that I have right now.

please tell me its just one step ahead.

**Comment by dillof** [comment]
Please read the provided documentation.

From INSTALL.md:

> For AES (encryption) support, you need one of these cryptographic libraries,
> listed in order of preference:
> 
> - Apple's CommonCrypto (available on macOS and iOS)
> - [OpenSSL](https://www.openssl.org/)
> - [GnuTLS](https://www.gnutls.org/).

yours,
Dillo

**Comment by sukhchainn** [comment]
Sorry to bother you for so long.
Now the issue is resolved by downloading GnuWin32 from sourceforge.net , the problem was that
I have windows and the required libraries were not present in it, so I had to download.
The procedure of downloading and installing these libraries was not working because they also had dependencies. 

All the dependencies are now completed by installing GetGnuWin32.exe from sourceforge.
I am writing this so that nobody faces the same problem as me.
