### ISSUE TITLE
Failing to get comment with some zips

### ISSUE THREAD

**Issue by elvisangelaccio** [nih-at/libzip#57]
[addonsu-15.1-arm64-signed.zip](https://github.com/nih-at/libzip/files/2217292/addonsu-15.1-arm64-signed.zip)

Consider the attached zip (or any other zip file downloaded from lineageos.org).

If I use `zip_get_archive_comment(archive, nullptr, ZIP_FL_ENC_GUESS)` I get the following string:

```
signed by SignApk 0é♣ô♠○*åHå≈♪☺•☻áé♣ä0é♣Ç☻☺☺1♂0○♠♣+♫♥☻→♣ 0♂♠○*åHå≈♪☺•☺áé♥╖0é♥│0é☻¢á♥☻☺☻☻○ ß♦‼╟s├┼O0♪♠○*åHå≈♪☺☺♣♣ 0p1♂0○♠♥U♦♠‼☻US1‼0◄♠♥U♦◘♀◙Washington1►0♫♠♥U♦•♀•Seattle1↕0►♠♥U♦◙♀○LineageOS1↕0►♠♥U♦♂♀○LineageOS1↕0►♠♥U♦♥♀○LineageOS0▲↨♪170107042125Z↨♪440525042125Z0p1♂0○♠♥U♦♠‼☻US1‼0◄♠♥U♦◘♀◙Washington1►0♫♠♥U♦•♀•Seattle1↕0►♠♥U♦◙♀○LineageOS1↕0►♠♥U♦♂♀○LineageOS1↕0►♠♥U♦♥♀○LineageOS0é☺\"0♪♠○*åHå≈♪☺☺☺♣ ♥é☺☼ 0é☺◙☻é☺☺ ªM╙ß°B♥Å≡?g╕Θ┐○S☼┬æ<╡>6T╟Ä┬♪╝ï▲q‼bîÑ½└å♣`╦D,←Q∙ïm╬^Y─É7≥⌂d⌠è∩♦É½Ö►o◘•ó‼♫→ï:¼╪4µV≡àK`&w╢l {¶┬╨┬ì♪╞‼A▐dìç¥╡Ü₧yß(ês→;▒╞▼╡ÅrZ└q▐↕╢►ô▐╠Và¼$t╬Γ╧\"≡ΣK≥◘A♪æ┼╤÷◙ºöUHé+¡ujpα■↨╚?5σ·Y╛M╥┤F♦Å¢B3!å ◙ñ~╙£!♪Θ²ÿ∟Uq₧╚≤♀¬─A\\!`_‼⌡}♫═≡h,HNöVtìδΦ♫/.♂∟⌠⌂╣]Æ ⌠g>▬÷7ü≤▓╟═KÉ@A½δ]°PYÖ☻♥☺ ☺úP0N0↔♠♥U↔♫♦▬♦¶rû2'╓lLM_áæj┬,y<╘_C\\0▼♠♥U↔#♦↑0▬Ç¶rû2'╓lLM_áæj┬,y<╘_C\\0♀♠♥U↔‼♦♣0♥☺☺ 0♪♠○*åHå≈♪☺☺♣♣ ♥é☺☺ è$~☺╔╟.qg▐┬Iô≥?S£•aî(↓εM>«û╥â↨:δß↕Fö♣──ÇR∩▲╟/)I¼♠w┤₧¼PU╛ó■u¿▌=ⁿï<╧ê√►─á┬w¥┬å▲Ç┤E↕î↑H\\Γ┤┤≈O≡8ÆGe¢SåW#t╨∙┐&╠┬aτâ9|úÇìZ↓▐&°█ä┘*╞ç+♂█╞◙╟hΣ¼t╤Bτ≥┼╒┴╩╗╩]←¬█Æ2R▒¢áò♥p╒Vp|7├Ö╔6ª~◘²↨H╬Ñemè▌⌂ó↨~╓0ymìα·ΘW♂'J♦Y○ä╒└e■0zSFδTû.A⌡Ç╤ñHF1↕Γ╒⌠æú¢╣∙óá╩┼à\\(ú_╜▒¡JjΩ▓«ó∙♣nsⁿHw7δ1é☺ñ0é☺á☻☺☺0}0p1♂0○♠♥U♦♠‼☻US1‼0◄♠♥U♦◘♀◙Washington1►0♫♠♥U♦•♀•Seattle1↕0►♠♥U♦◙♀○LineageOS1↕0►♠♥U♦♂♀○LineageOS1↕0►♠♥U♦♥♀○LineageOS☻○ ß♦‼╟s├┼O0○♠♣+♫♥☻→♣ 0♪♠○*åHå≈♪☺☺☺♣ ♦é☺ z#┐╒└äÑ@►∙╬f◙c♫ƒ╙└àτZnα1t ¬u◄µ0┐02◄Öë:⌂èï‼├X╞¡°bO♀M→?5♥╙♀ë±aæ*à¿(ò≥h╒Öq<@[╣Eá%♦'╝gbuY╞±5\"«|╬╣4½♥☻k☻Erjj/⌡₧§<╜α5╟w≈I░┤3└╠▀,O╚π↔∙▄≈/πw╧╠|▬h☼?c$≈▐9µRgDm◄v+╣N«7π1►°«¢!`¥_û∩╬○6Knƒ⌠]!└▀╙ïè≥▒╧@┌+▌ ≡╘Å╔l╖T+└\"OæoCâ~↑à╟-ùö⌐▌eÆ♪Å♦π○`zÉ≥â▀0╛♂╞║Θp╕⌡î÷¥▼╤Φ↨├,╥jd▒▲♀│↕·╩ö¥♣  »♣
```

instead of just:

```
signed by SignApk
```

**Comment by 0-wiz-0** [comment]
This is not a bug in libzip.
The archive comment for this archive is 1455 bytes. After the "signed by SignApk" part is a zero byte and then the other 1400+ bytes follow. If you just print them with `printf`, you won't see anything after the zero byte, but it's there.

**Comment by elvisangelaccio** [comment]
Hmm, somehow I don't get the zero byte, and even

    printf("%s\n", zip_get_archive_comment(archive, nullptr, ZIP_FL_ENC_GUESS));

does show the very same string I pasted in my first comment. Could it be a problem with my locale?

**Comment by 0-wiz-0** [comment]
`printf` stops writing when it encounters a zero byte (strings in C are zero-terminated).
You should pass a pointer to a variable instead of nullptr and look at the returned length to find out how big the comment is.

**Comment by 0-wiz-0** [comment]
So what does (untested, something like):
````
char *foo=zip_get_archive_comment(archive, nullptr, ZIP_FL_ENC_GUESS)
printf("%x\n", foo[strlen("signed by SignApk")]);
````
print?

**Comment by elvisangelaccio** [comment]
That snippet prints `ffffffe2`.

I should probably mention that I'm using this code from a C++ program, not sure if related. I'll try again with a minimal test program in C.

**Comment by 0-wiz-0** [comment]
I'm sorry, you're right. I misunderstood.
There was a bug in libzip. CP437 '0' was not translated to UTF-8 '0'.
I've just pushed a commit that should fix this, please let me know if it fixes the problem for you.

**Comment by elvisangelaccio** [comment]
Yes, the fix works for me. Thanks!
