### ISSUE TITLE
Pass options when adding as external project in CMakeLists.txt

### ISSUE THREAD

**Issue by tchapi** [nih-at/libzip#69]
Hi,

Not sure if this is a bug or a misinterpretation on my side. I'm using CMake to add libzip as an external project to my code.

In my CMakeLists.txt, among other things, I include libzip like that : 

```
set(LIBZIP_BUILD_DIR ${CMAKE_CURRENT_BINARY_DIR}/external-lib-libzip)
ExternalProject_Add(
    project_libzip
    GIT_REPOSITORY https://github.com/nih-at/libzip/
    GIT_TAG rel-1-5-1
    PREFIX ${LIBZIP_BUILD_DIR}
    CMAKE_ARGS "-DBUILD_TOOLS=OFF" "-DCMAKE_INSTALL_PREFIX=${LIBZIP_BUILD_DIR}" "-DBUILD_REGRESS=OFF"  "-DBUILD_EXAMPLES=OFF" "-DBUILD_DOC=OFF"
)
add_library(libzip STATIC IMPORTED)
```
What I'm trying to achieve here is to build libzip from source, **without the examples, docs, regress and tools** (since I don't need them). To this avail, I'm passing the following options in `CMAKE_ARGS` :  `BUILD_DOC BUILD_EXAMPLES BUILD_REGRESS BUILD_TOOLS`

When I run `cmake` and then `make` for my target, I get the following warning : 

```
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_DOC
    BUILD_EXAMPLES
    BUILD_REGRESS
    BUILD_TOOLS
```

And thus all the examples, etc, are built. The twist here is that the `CMAKE_INSTALL_PREFIX` is correctly taken into account (and no warning is issued for this option).

Is this a problem in this repo's CMakeLists.txt or is this me not understanding how all this should work ?

Thanks a lot for your time !
BR

**Comment by codylico** [comment]
_I just happen to be following the repository; I am not a contributor, so feel free to ignore me if I am wrong._

It looks like those `BUILD...` variables were introduced after the `rel-1-5-1` release. Maybe there should be a new release `rel-1-5-2` (at some point) to account for the missing variables?

I guess that a commit ID would have to be used instead until such a release emerges.

**Comment by tchapi** [comment]
Oh. You're right, I'm silly ... thanks a lot !
