### ISSUE TITLE
SFX is gone after modification.

### ISSUE THREAD

**Issue by hungte** [nih-at/libzip#72]
If I want to update ZIP archives with SFX (created by zip XX.zip DIR; cat XX.zip >> sfx.sh; zip -A sfx.sh), after zip_open, zip_file_add, zip_close, the output becomes a pure ZIP archive without SFX. Other zip (like infozip) will keep SFX unchanged.

Is there any way so we can keep SFX unchanged? For example adding an flag to indicate we have to copy anything before first entry of CDIR?

**Comment by hungte** [comment]
A quick question: what should be the behavior when someone opens archive and then closes, without calling the APIs above?

I'm thinking what to be stored in the zip structure.

**Comment by 0-wiz-0** [comment]
In that case the existing SFX loader should be preserved (just like archive comments are preserved when they are not touched).

**Comment by 0-wiz-0** [comment]
Close this for now. It's an open item in the `TODO.md` file.
