### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by 1265578519** [nih-at/libzip#73]
[root@new_centos6 libzip-1.5.1]# ./configure
-bash: ./configure: 没有那个文件或目录
[root@new_centos6 libzip-1.5.1]# make
make: *** 没有指明目标并且找不到 makefile。 停止。
[root@new_centos6 libzip-1.5.1]#

**Comment by 0-wiz-0** [comment]
Yes, libzip switched to using `cmake` to build.
See https://github.com/nih-at/libzip/blob/master/INSTALL.md
