### ISSUE TITLE
configure: WARNING: Libzip >= 1.2.0 needed for encryption support

### ISSUE THREAD

**Issue by acodercat** [nih-at/libzip#74]
configure: WARNING: Libzip >= 1.2.0 needed for encryption support

**Comment by dillof** [comment]
Could you please provide more context?

**Comment by acodercat** [comment]
[https://stackoverflow.com/questions/48700453/docker-image-build-with-php-zip-extension-shows-bundled-libzip-is-deprecated-w](url)

**Comment by dillof** [comment]
Please take this up with the maintainer of the docker image.
