### ISSUE TITLE
Libzip overriding the file mode when writing

### ISSUE THREAD

**Issue by arcanis** [nih-at/libzip#77]
What's the rational behind [the following lines](https://github.com/nih-at/libzip/blob/ff55682b2cb85f3bd53813cddc7c6afb94c7572c/lib/zip_source_filep.c#429)?

	mask = umask(022);
	umask(mask);
	/* not much we can do if chmod fails except make the whole commit fail */
	(void)chmod(ctx->fname, 0666 & ~mask);

In particular, why is the libzip overriding the file mode with the umask after closing it even if the destination existed before? Shouldn't this only apply to newly created files (but then the chmod would be useless since the umask will already be applied at file creation).

**Comment by 0-wiz-0** [comment]
We normalize the file mode so it has the same r/w permissions as before. We don't think x or other permissions are useful for zip archives.
Do you have a particular problem with this code?

**Comment by arcanis** [comment]
I was in a weird situation (libzip compiled to emscripten running under electron/vscode) where my umask was bogus. This was causing my archives to be changed to chmod `000` after being modified.

I haven't yet found the cause 😕

**Comment by arcanis** [comment]
Btw, regarding "so it has the same r/w permissions as before", is that really the case? The `umask` return value isn't necessarily the same as the file permissions, right?

Let's say the file is 444 but my umask is 644, won't that cause the file to be silently changed to 644 as soon as the libzip edits it?

**Comment by 0-wiz-0** [comment]
Yeah, you're right, we're not maintaining the file permissions from before.

**Comment by 0-wiz-0** [comment]
Fixed, thanks for the report!
