### ISSUE TITLE
Winzip AES broken in some cases

### ISSUE THREAD

**Issue by TCHessen** [nih-at/libzip#78]
How to reproduce the bug: (tested with 1.4.0 and 1.5.1)

./ziptool -n test-aes256.zip add_file file test3 0 8169 set_file_encryption 0 AES-256 12345678
./ziptool -c test-aes256.zip set_password 12345678 cat 0 > test3-test

Result: can't read file at index '0': CRC error

I figured out that the reason seems to be that the result of the last round of aes encryption is equal than the buffer size of 8192 bytes, but I have not the time to go deeper.

Testcase: [test3.zip](https://github.com/nih-at/libzip/files/2779841/test3.zip)
```
md5sum test3: 5f8d76ad2c584fe68ce9e88175ce964a
sha1sum test3 d201cf445b5f10bf50cbce9379e3ed0ca023a41a

```

**Comment by 0-wiz-0** [comment]
Fixed, thanks for the report!
