### ISSUE TITLE
CMAKE_MODULE_PATH

### ISSUE THREAD

**Issue by malytomas** [nih-at/libzip#79]
https://github.com/nih-at/libzip/blob/ff55682b2cb85f3bd53813cddc7c6afb94c7572c/CMakeLists.txt#L6

CMAKE_MODULE_PATH  is an array and the path should be appended to it rather than overriding it. This will allow users to set the variable in command line or superprojects to inject their own paths to search in.

**Comment by 0-wiz-0** [comment]
Fixed, thanks!
