### ISSUE TITLE
cmake: building with cmake does not generate linux man pages

### ISSUE THREAD

**Issue by asavah** [nih-at/libzip#8]
Building from git on linux:
```
CMake Error at man/cmake_install.cmake:36 (file):
  file INSTALL cannot find "/home/asavah/kross/src/libzip/man/zipcmp.man".
Call Stack (most recent call first):
  cmake_install.cmake:46 (include)
```
mandoc is present,
building with autotools is fine, man pages are generated and installed.

**Comment by 0-wiz-0** [comment]
That's a known problem. I tried writing the code for that but it's not finished, see the block starting at https://github.com/nih-at/libzip/blob/master/man/CMakeLists.txt#L148

Test pull requests very welcome!

**Comment by 0-wiz-0** [comment]
I've fixed this two ways. cmake can be used to build the man pages (`update-man` target) and the generated man pages are now also included in the repository (so that `git archive` includes them).
They were always included in the distribution tarballs.
