### ISSUE TITLE
zip_set_file_compression with ZIP_CM_DEFAULT and compression level > 0

### ISSUE THREAD

**Issue by varqox** [nih-at/libzip#80]
Hello,
I think I have found a bug. When one creates an empty zip archive and adds a file to it and then tries to set the compression level of ZIP_CM_DEFAULT, the compression level does not change. E.g.
```c
#include <assert.h>
#include <stdlib.h>
#include <zip.h>

int main() {
	int err;
	zip_t *zip = zip_open("test.zip", ZIP_CREATE | ZIP_TRUNCATE, &err);
	assert(zip);

	int buff_len = 4e6;
	char *buff = malloc(buff_len);
	assert(buff);
	srand(42);
	for (int i = 0; i < buff_len; ++i)
		buff[i] = rand() & 3;

	zip_source_t *zs = zip_source_buffer(zip, buff, buff_len, 1);
	assert(zs);

	int idx = zip_file_add(zip, "foobar", zs, 0);
	assert(idx != -1);

	// Try uncommenting the line below and see how much the running time has changed
	assert(0 == zip_set_file_compression(zip, idx, ZIP_CM_DEFAULT, 1));
	// assert(0 == zip_set_file_compression(zip, idx, ZIP_CM_DEFLATE, 1));

	assert(0 == zip_close(zip));
	return 0;
}
```
When you uncomment the line that sets DEFLATE compression with level 1, you should see a dramatic decrease in running time (faster compression). But as the documentation says, when compression method is ZIP_CM_DEFAULT and compressing is chosen instead of storing, the deflate algorithm is used. So why there is such a dramatic change in running time? If I understand the documentation correctly it should be the same.

I dug deeper and I think I found the faulty code: https://github.com/nih-at/libzip/blob/master/lib/zip_set_file_compression.c#L60-L76
It seems that if a new file is added to the archive, then setting its compression level for ZIP_CM_DEFAULT is completely ignored (line 70).

Is that the expected behavior? If it is, then IMO, it is a good idea to mention it in the documentation.

Regards,
Krzysztof

**Comment by 0-wiz-0** [comment]
`ZIP_CM_DEFAULT` leaves the decision to libzip. It can decide to store the file or compress it. It is not a choice of a particular algorithm, so there is no point giving it arguments and they are not kept.
`ZIP_CM_DEFLATE` is a choice of a particular algorithm, so flags can be set and kept.
I've added a sentence to the `zip_set_file_compression` man page that flags are ignored for `ZIP_CM_DEFAULT`.
Thanks for the bug report!
