### ISSUE TITLE
Can I use lib zip to get file permission

### ISSUE THREAD

**Issue by Joezc** [nih-at/libzip#81]
Is there a way I can get permission information of a file in archives without extracting it? 

Seems `zip_stat` do this work but it does not support permission information.

**Comment by 0-wiz-0** [comment]
The base format only includes the MS-DOS attributes, which nowadays are worthless. You currently cannot get this information using libzip.
Info-ZIP defined some extra fields with attribute information, depending on the operating system. You can read these using the libzip extra fields API, see `zip_file_extra_field_get()` and `zip_file_extra_field_get_by_id()`. The extra fields are described in `docs/appnote.iz`.
