### ISSUE TITLE
No timezone set causes opening zip files with many entries to be slow on Linux

### ISSUE THREAD

**Issue by aeubanks** [nih-at/libzip#84]
Zip file created with:
$ cd $(mktemp -d)
$ for i in $(seq 1 10000); do touch $i; done
$ zip -r /tmp/bigzip.zip .

$ cat test.c
#include <zip.h>

int main(int argc, char** argv)
{
  if (argc < 2) { printf("need path to zip\n"); return 1; }
  zip_t* z = zip_open(argv[1], 0, NULL);
  if (z == NULL) { printf("NULL zip_open\n"); return 1; }
}

$ gcc test.c -lzip
$ strace -fc -estat ./a.out /tmp/bigzip.zip
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.041797           4     10001           stat
------ ----------- ----------- --------- --------- ----------------
100.00    0.041797                 10001           total
$ TZ= strace -fc -estat ./a.out /tmp/bigzip.zip
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.000010           5         2           stat
------ ----------- ----------- --------- --------- ----------------
100.00    0.000010                     2           total

When the TZ env var is empty, glibc goes and stats /etc/localtime, once for each entry in the zip file. For zip files with lots of entries, this slows down a lot.
But when the TZ env var is set, glibc caches the result (I think).
This probably has to do the modification time for a zip entry. I think it's happening in _zip_d2u_time() at a call to mktime()?

Maybe there could be an option to not need/convert the modification time? Or some other change around timezones/mktime()?

**Comment by 0-wiz-0** [comment]
Thanks for the report. That is interesting, but I don't think that is something that we'll address in libzip.

Set up your environment so that glibc can cache the timezone, or report it upstream to glibc to speed this up. Or change the code in `zip_dirent.c` that converts the DOS timestamp to a Unix one in your local copy.
