### ISSUE TITLE
docs improvement related to source lifetime

### ISSUE THREAD

**Issue by malytomas** [nih-at/libzip#87]
Hi,
I would like to suggest adding a statement to documentation that zip_file_add _extends_ lifetime of the source, and therefore the lifetime of the _buffer_ backing up the source must be extended too. This possibly also applies to zip_file_replace.

I would also welcome an explanation of when is the source released. Function zip_close is obvious, but I am not sure about functions zip_file_replace, zip_delete or zip_unchange (with the same file).

My initial (wrong) understanding was that the function zip_file_add "uses" the source and releases it before it returns.

I understand why it works the way it does now, but it took me quite a lot of time to got it. I hope this might help some other programmers to use this library with ease. The library is awesome :D

Thanks

**Comment by 0-wiz-0** [comment]
libzip is C code, so the concept of lifetime extension sounds weird to me – we're not talking about objects.
The `zip_source` man page already describes that it's reference counted. Once you pass a `zip_source` to a libzip  function(like `zip_open_from_source` or `zip_file_add`), you give up ownership of it and it's libzip's task to handle the memory. You only need to free it if the function call returns an error.

If you feel the documentation needs improvements, please supply a diff to the man pages. It's not clear to me what would need to be improved to make it clearer.
