### ISSUE TITLE
Set mtime through utc

### ISSUE THREAD

**Issue by arcanis** [nih-at/libzip#89]
It seems like the libzip [uses `localtime`](https://github.com/nih-at/libzip/blob/master/lib/zip_dirent.c#L1071) in order to set the mtime values. This behavior is causing issues when generating zip archives with fixed mtime, as it will cause the stored value to change based on the timezone of the computer that generated the file.

In our case (the Yarn package manager), it causes our cache files to not pass their checksum validations depending on the timezones of the machines who 1/ generated the files and 2/ validated them.

Switching to `gmtime` by default might be a breaking change, but would it be possible to have a flag to let the libzip know that in some cases the mtime is meant to be interpreted as UTC?

**Comment by HAT-DK** [comment]
I agree; In the current state, mtime is not useful for me neither 8(

**Comment by 0-wiz-0** [comment]
The behavior is intended to be compatible with what InfoZip unzip does. The PKZIP file format description doesn't specify this detail, and InfoZip unzip is the standard Unix implementation.

The conversion is done when opening the file. If you want to interpret the time in a different way, you can easily do it without libzip's help - just manually apply the offset of your local timezone to UTC before writing to the file/after reading it.

IIRC, the time is also only exact to 2s (not 1s). If you really care about time stamps, you should use the Extended Timestamp Extra Field (0x5455) instead – see the included `doc/appnote.iz` file for details.

**Comment by arcanis** [comment]
Fwiw I don't actually care about the timestamp - what I care about is producing deterministic archives that end up with the exact same checksum for the same operations. In this context, having two computers generate two different archives depending on the timezone cannot work.

Given that it's a mandatory behaviour for us, we're currently relying on [patching the sources](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-libzip/artifacts/build.sh#L36).

**Comment by 0-wiz-0** [comment]
We have added a `zip_file_set_dostime` function that allows setting the values in the zip archive directly. This should address your request.
