### ISSUE TITLE
zip_fopen works with error ZIP_ER_ZLIB on Windows

### ISSUE THREAD

**Issue by flipback** [nih-at/libzip#9]
I have a problem trying to read a ZIP archive by using zip_fopen function:

```C
    auto archive = cip_server.get_archive_name();
    if ((zip_archive = zip_open(archive.c_str(), 0, &err)) == NULL) {
    	LOG_ERROR("Error: can't open zip archive.");
        GoToIdleState();
        return;
    }

    for (uint32_t i = 0; i < zip_get_num_entries(zip_archive, 0); i++) {
        struct zip_stat zip_stat;

        if (zip_stat_index(zip_archive, i, 0, &zip_stat) == 0) {
            LOG_INFO("Start uncompressing archive file");

            LOG_DEBUG_FMT("Zip Entry Name: [%s], ", zip_stat.name);
            LOG_DEBUG_FMT("Entry Size: [%llu], ", zip_stat.size);
            LOG_DEBUG_FMT("mtime: [%u]/n", (unsigned int)zip_stat.mtime);
            struct zip_file *zip_file = zip_fopen(zip_archive, zip_stat.name, 0);
            if (zip_file == NULL) {
            	zip_error_t* error = zip_get_error(zip_archive);
                LOG_ERROR_FMT("ERROR Zip: can't open uncompress entry in archive: %i",  zip_error_code_zip(error));
            	zip_error_fini(error);
                has_error = true;
                break;
            }
/* unrelated part of code */
```

This code shows message `ERROR Zip: can't open uncompress entry in archive: 13` after it has tried to read an entry of the archive. I use it on Linux and don't have any problems. but it doesn't work on Windows at all. Do you have any ideas what I do wrong?

Thanks,

**Comment by 0-wiz-0** [comment]
You can use `zip_strerror()` to get an error message string for the error.
If you already know the index, like here, I suggest using `zip_fopen_index()` instead.

I'm not using Windows myself, but I don't think there is a principal problem on that platform. You'll have to debug it.

You could also try asking for help on the mailing list, there are some Windows users there.

Please only use github issues when you're sure you found a bug in libzip. Thanks.
