### ISSUE TITLE
Defines for printing 64 values are incorrect and causes warnings

### ISSUE THREAD

**Issue by HAT-DK** [nih-at/libzip#90]
The 2 defines 'PRId64' and 'PRIu64' are not correct and causes warnings on linux x64.
Please update them to:

#ifndef PRId64
#ifdef _MSC_VER
#define PRId64 "I64d"
#else
#ifdef __x86_64__
#define PRId64 "ld"
#else
#define PRId64 "lld"
#endif
#endif
#endif

#ifndef PRIu64
#ifdef _MSC_VER
#define PRIu64 "I64u"
#else
#ifdef __x86_64__
#define PRIu64 "lu"
#else
#define PRIu64 "llu"
#endif
#endif
#endif

**Comment by 0-wiz-0** [comment]
Can you please instead find out why the `PRId64` and `PRIu64` defines are not defined for your compiler? I would expect that Linux x86_64 supplies them.

**Comment by HAT-DK** [comment]
I guess cause of this: https://stackoverflow.com/a/18719205

**Comment by 0-wiz-0** [comment]
libzip is plain C though. Are you using it from C++?

**Comment by HAT-DK** [comment]
Correct, I'm using the GNU 7.3.0 compiler with the pedantic option

**Comment by 0-wiz-0** [comment]
Please try commit b7a911d3b1dd6317a254d816d66f9926d839ff9f.

**Comment by HAT-DK** [comment]
Thanks, works great!

**Comment by 0-wiz-0** [comment]
Thanks for testing!
