### ISSUE TITLE
zip_open() opens archive without close-on-exec flag set

### ISSUE THREAD

**Issue by varqox** [nih-at/libzip#94]
It would be nice if at least specifying such option as ZIP_CLOEXEC caused zip_open() to set close-on-exec flag on the opened file descriptor. Without it set, the opened file descriptor survives exec() and remains open in the new process, unless it is carefully closed (which is hard to achieve in larger applications).
Is it possible to do something about it?

**Comment by dillof** [comment]
Actually, setting O_CLOEXEC is alway the right thing to do, we'll set it unconditionally.

**Comment by 0-wiz-0** [comment]
We've implemented this in git head, thanks for the suggestion!
