### ISSUE TITLE
libzip-1.5 fails to compile on linux with musl-libc with error:zipcmp.c:(.text+0xd74): undefined reference to `fts_read' and 'fts_close'

### ISSUE THREAD

**Issue by stefson** [nih-at/libzip#98]
the last version known to work is libzip-1.3

this is the full build.log [build.log.gz](https://github.com/nih-at/libzip/files/3144415/build.log.gz)

I tried both clang-7 and gcc-8.2.0, to no avail.

**Comment by dillof** [comment]
The problem is that fts.h is found, but fts_open() et. al. are not present. Could you please check the man page for fts_open, wether it needs additional libraries?

**Comment by stefson** [comment]
The problem is, that musl doesn't have an own fts implementation. Turns out I had a copy installed which was borrowed from netbsd, removing that and the compile of libzip is working again. Your config scripts detects fts as missing, and does something magic it seems :-)
