### ISSUE TITLE
build by cmake error

### ISSUE THREAD

**Issue by jjasoncool** [nih-at/libzip#99]
I have build libzip by cmake 3.14.3
my os is centos 7.6
my install step is below:
`mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/libzip -DBUILD_SHARED_LIBS=ON .. && make install`

but when I use 
[jason@jason bin]$ ./zipcmp
./zipcmp: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
![圖片](https://user-images.githubusercontent.com/24731867/57465472-43931000-72b1-11e9-98af-35d351aaa294.png)

Is there have any parameter to let build file to find the lib in it's own folder? (/usr/local/libzip/lib64)
I have read install.md, but it still doesn't work.

Thank you.

**Comment by 0-wiz-0** [comment]
Tell your ld where to find the libraries.
A random page from the first page of Google:
https://www.tecmint.com/understanding-shared-libraries-in-linux/

**Comment by jjasoncool** [comment]
thanks a lot
